export default {
  'a priori': 'a priori',
  'aberrant': 'aberrante',
  'abject': 'abyecto',
  'ablaze': 'en llamas',
  'able': 'capaz',
  'aboard': 'a bordo',
  'above': 'encima',
  'abreast': 'al tanto',
  'abrupt': 'abrupto',
  'absent': 'ausente',
  'absolute': 'absoluto',
  'abstract': 'abstracto',
  'abstruse': 'abstruso',
  'absurd': 'absurdo',
  'abundant': 'abundante',
  'accurate': 'preciso',
  'acquiescent': 'conforme',
  'actual': 'real',
  'acute': 'agudo',
  'ad hoc': 'ad hoc',
  'ad infinitum': 'ad infinitum',
  'adamant': 'inflexible',
  'adept': 'experto',
  'adequate': 'adecuado',
  'adverse': 'adverso',
  'affectionate': 'cariñoso',
  'affluent': 'adinerado',
  'afraid': 'asustado',
  'against': 'en contra',
  'aggressive': 'agresivo',
  'agile': 'ágil',
  'agreeable': 'agradable',
  'ahead': 'adelante',
  'alcoholic': 'alcohólico',
  'alight': 'encendido',
  'alike': 'parecido',
  'alive': 'vivo',
  'alkaline': 'alcalino',
  'all': 'todo',
  'alone': 'solo',
  'aloof': 'distante',
  'alright': 'bien',
  'alternate': 'alterno',
  'ample': 'amplio',
  'angry': 'enojado',
  'antiquated': 'anticuado',
  'antique': 'antiguo',
  'antsy': 'inquieto',
  'appalled': 'horrorizado',
  'appalling': 'espantoso',
  'apparent': 'aparente',
  'appetizing': 'apetitoso',
  'appropriate': 'apropiado',
  'approximate': 'aproximado',
  'apt': 'apto',
  'arbitrary': 'arbitrario',
  'archival': 'de archivo',
  'arrogant': 'arrogante',
  'articulate': 'elocuente',
  'artificial': 'artificial',
  'artsy': 'artístico',
  'ashen': 'ceniciento',
  'asleep': 'dormido',
  'astute': 'astuto',
  'attractive': 'atractivo',
  'auditory': 'auditivo',
  'austere': 'austero',
  'authentic': 'auténtico',
  'autoimmune': 'autoinmune',
  'avant garde': 'vanguardista',
  'average': 'promedio',
  'awake': 'despierto',
  'aware': 'consciente',
  'awesome': 'genial',
  'awkward': 'torpe',
  'backwards': 'hacia atrás',
  'bad': 'malo',
  'bald': 'calvo',
  'bankrupt': 'en quiebra',
  'bare': 'desnudo',
  'barren': 'estéril',
  'bawdy': 'obsceno',
  'beautiful': 'hermoso',
  'behind': 'detrás',
  'belated': 'tardío',
  'beloved': 'querido',
  'below': 'abajo',
  'beneath': 'debajo',
  'beneficial': 'beneficioso',
  'benign': 'benigno',
  'bent': 'doblado',
  'beside': 'al lado',
  'bestselling': 'superventas',
  'beyond': 'más allá',
  'big': 'grande',
  'bigtime': 'importante',
  'bipartisan': 'bipartidista',
  'bitter': 'amargo',
  'bizarre': 'extraño',
  'black': 'negro',
  'bland': 'insípido',
  'blind': 'ciego',
  'blithe': 'despreocupado',
  'blond': 'rubio',
  'bloody': 'sangriento',
  'blue': 'azul',
  'blunt': 'franco',
  'bogus': 'falso',
  'bold': 'audaz',
  'boldface': 'en negrita',
  'bona fide': 'de buena fe',
  'bonafide': 'de buena fe',
  'bouncy': 'saltarín',
  'brand new': 'flamante',
  'brash': 'descarado',
  'brave': 'valiente',
  'breathtaking': 'impresionante',
  'bright': 'brillante',
  'brilliant': 'brillante',
  'brisk': 'enérgico',
  'broad': 'ancho',
  'bronze': 'de bronce',
  'brown': 'marrón',
  'buck naked': 'en cueros',
  'buff': 'musculoso',
  'burly': 'corpulento',
  'busy': 'ocupado',
  'cagey': 'cauteloso',
  'calm': 'tranquilo',
  'cardiac': 'cardíaco',
  'careful': 'cuidadoso',
  'celebate': 'célibe',
  'certain': 'cierto',
  'cheap': 'barato',
  'cheery': 'alegre',
  'cheesy': 'cursi',
  'chewy': 'masticable',
  'chilly': 'frío',
  'chintzy': 'cutre',
  'circumspect': 'circunspecto',
  'civil': 'civil',
  'clean': 'limpio',
  'clear': 'claro',
  'clever': 'listo',
  'clockwise': 'en sentido horario',
  'close': 'cercano',
  'cloudy': 'nublado',
  'coarse': 'áspero',
  'coercive': 'coercitivo',
  'cogent': 'convincente',
  'cognizant': 'consciente',
  'cold': 'frío',
  'colonial': 'colonial',
  'colossal': 'colosal',
  'comatose': 'comatoso',
  'commensurate': 'proporcional',
  'common': 'común',
  'compassionate': 'compasivo',
  'complete': 'completo',
  'compulsory': 'obligatorio',
  'concave': 'cóncavo',
  'conceited': 'engreído',
  'concise': 'conciso',
  'condescending': 'condescendiente',
  'conducive': 'propicio',
  'congruent': 'congruente',
  'conjoint': 'conjunto',
  'conjugal': 'conyugal',
  'conjugate': 'conjugado',
  'consequent': 'consiguiente',
  'constant': 'constante',
  'consummate': 'consumado',
  'contradictory': 'contradictorio',
  'contrary': 'contrario',
  'contrite': 'contrito',
  'cool': 'genial',
  'corporate': 'corporativo',
  'correct': 'correcto',
  'corrupt': 'corrupto',
  'costly': 'costoso',
  'counterclockwise': 'en sentido antihorario',
  'counterfeit': 'falsificado',
  'covert': 'encubierto',
  'cowardly': 'cobarde',
  'coy': 'esquivo',
  'cozy': 'acogedor',
  'crafty': 'astuto',
  'craven': 'cobarde',
  'crazed': 'enloquecido',
  'creepy': 'espeluznante',
  'crisp': 'crujiente',
  'crucial': 'crucial',
  'cruel': 'cruel',
  'crystal clear': 'clarísimo',
  'crystalline': 'cristalino',
  'cuddly': 'tierno',
  'curly': 'rizado',
  'curmudgeonly': 'gruñón',
  'customary': 'habitual',
  'cute': 'lindo',
  'cutesy': 'cursi',
  'daily': 'diario',
  'damp': 'húmedo',
  'dangerous': 'peligroso',
  'dapper': 'elegante',
  'dark': 'oscuro',
  'de facto': 'de facto',
  'dead': 'muerto',
  'deadly': 'mortal',
  'deadpan': 'inexpresivo',
  'deaf': 'sordo',
  'dear': 'querido',
  'deceased': 'difunto',
  'deep': 'profundo',
  'defiant': 'desafiante',
  'definite': 'definido',
  'defuse': 'difuso',
  'degenerate': 'degenerado',
  'deliberate': 'deliberado',
  'delicate': 'delicado',
  'delightful': 'encantador',
  'demure': 'recatado',
  'dense': 'denso',
  'dependent': 'dependiente',
  'derelict': 'abandonado',
  'desperate': 'desesperado',
  'despondent': 'abatido',
  'destitute': 'indigente',
  'desultory': 'inconexo',
  'devoid': 'desprovisto',
  'devout': 'devoto',
  'didactic': 'didáctico',
  'difficult': 'difícil',
  'diffuse': 'difuso',
  'dim': 'tenue',
  'dire': 'terrible',
  'direct': 'directo',
  'dirty': 'sucio',
  'discreet': 'discreto',
  'discrete': 'discreto',
  'diseased': 'enfermo',
  'disjoint': 'disjunto',
  'disparate': 'dispar',
  'distant': 'distante',
  'distinct': 'distinto',
  'divergent': 'divergente',
  'diverse': 'diverso',
  'divine': 'divino',
  'dizzy': 'mareado',
  'docile': 'dócil',
  'dominant': 'dominante',
  'done': 'hecho',
  'dormant': 'inactivo',
  'doting': 'cariñoso',
  'double': 'doble',
  'doubtful': 'dudoso',
  'dreary': 'sombrío',
  'drowsy': 'somnoliento',
  'drunk': 'borracho',
  'dry': 'seco',
  'due': 'debido',
  'dull': 'aburrido',
  'dumb': 'tonto',
  'eager': 'ansioso',
  'early': 'temprano',
  'earthly': 'terrenal',
  'east': 'este',
  'eastern': 'oriental',
  'easy': 'fácil',
  'easygoing': 'relajado',
  'eerie': 'inquietante',
  'efficient': 'eficiente',
  'elaborate': 'elaborado',
  'elderly': 'anciano',
  'elegant': 'elegante',
  'elicit': 'ilícito',
  'eloquent': 'elocuente',
  'emergent': 'emergente',
  'eminent': 'eminente',
  'empty': 'vacío',
  'en route': 'en camino',
  'en suite': 'con baño privado',
  'enamored': 'enamorado',
  'enough': 'suficiente',
  'entire': 'entero',
  'equal': 'igual',
  'erect': 'erguido',
  'erstwhile': 'antiguo',
  'essential': 'esencial',
  'ethereal': 'etéreo',
  'everyday': 'cotidiano',
  'evil': 'malvado',
  'exact': 'exacto',
  'exempt': 'exento',
  'expedient': 'conveniente',
  'explicit': 'explícito',
  'express': 'expreso',
  'exquisite': 'exquisito',
  'extra': 'adicional',
  'extravagant': 'extravagante',
  'extreme': 'extremo',
  'exuberant': 'exuberante',
  'exultant': 'exultante',
  'fabled': 'legendario',
  'faint': 'débil',
  'fake': 'falso',
  'false': 'falso',
  'famed': 'famoso',
  'familiar': 'familiar',
  'fancy': 'lujoso',
  'far off': 'lejano',
  'far reaching': 'de gran alcance',
  'far': 'lejano',
  'fast paced': 'trepidante',
  'fast': 'rápido',
  'faulty': 'defectuoso',
  'faux': 'de imitación',
  'fed up': 'harto',
  'feeble': 'débil',
  'feminine': 'femenino',
  'fertile': 'fértil',
  'fervent': 'ferviente',
  'fierce': 'feroz',
  'fiery': 'ardiente',
  'final': 'final',
  'financial': 'financiero',
  'finite': 'finito',
  'firm': 'firme',
  'flagrant': 'flagrante',
  'flat': 'plano',
  'flirty': 'coqueto',
  'flowery': 'florido',
  'fluent': 'fluido',
  'fluorescent': 'fluorescente',
  'foamy': 'espumoso',
  'folksy': 'campechano',
  'fond': 'aficionado',
  'foolish': 'tonto',
  'for keeps': 'para siempre',
  'foregoing': 'anterior',
  'foreign': 'extranjero',
  'foreseeable': 'previsible',
  'forgetful': 'olvidadizo',
  'formal': 'formal',
  'former': 'anterior',
  'fortunate': 'afortunado',
  'forward': 'adelante',
  'foul': 'asqueroso',
  'fragile': 'frágil',
  'fragrant': 'fragante',
  'frail': 'frágil',
  'frantic': 'frenético',
  'free': 'libre',
  'frequent': 'frecuente',
  'fresh': 'fresco',
  'fretful': 'inquieto',
  'friendly': 'amistoso',
  'frilly': 'con volantes',
  'fringe': 'marginal',
  'frozen': 'congelado',
  'frugal': 'frugal',
  'full': 'lleno',
  'fun': 'divertido',
  'funny': 'gracioso',
  'furry': 'peludo',
  'gainful': 'remunerado',
  'gauche': 'torpe',
  'gaudy': 'chillón',
  'gay': 'gay',
  'generic': 'genérico',
  'gentle': 'suave',
  'genuine': 'genuino',
  'ghastly': 'horrible',
  'ghostly': 'fantasmal',
  'giant': 'gigante',
  'giddy': 'eufórico',
  'gigantic': 'gigantesco',
  'glad': 'contento',
  'glib': 'simplista',
  'global': 'global',
  'gloomy': 'sombrío',
  'golden': 'dorado',
  'good': 'bueno',
  'goofy': 'bobo',
  'graceful': 'grácil',
  'grand': 'grandioso',
  'grateful': 'agradecido',
  'gratis': 'gratis',
  'gray': 'gris',
  'greasy': 'grasiento',
  'great': 'estupendo',
  'greedy': 'codicioso',
  'green': 'verde',
  'grey': 'gris',
  'grim': 'sombrío',
  'grisly': 'espeluznante',
  'grizzled': 'canoso',
  'groovy': 'genial',
  'gross': 'asqueroso',
  'gruesome': 'horripilante',
  'guilty': 'culpable',
  'gung ho': 'entusiasta',
  'hairy': 'peludo',
  'hallowed': 'sagrado',
  'handsome': 'guapo',
  'handsy': 'toquetón',
  'handy': 'útil',
  'happy': 'feliz',
  'hard up': 'sin dinero',
  'hard': 'duro',
  'hardcore': 'extremo',
  'hardworking': 'trabajador',
  'hardy': 'resistente',
  'harsh': 'severo',
  'hateful': 'odioso',
  'heady': 'embriagador',
  'hearty': 'abundante',
  'heavenly': 'celestial',
  'heavy': 'pesado',
  'hefty': 'considerable',
  'hellish': 'infernal',
  'helpful': 'servicial',
  'hesitant': 'vacilante',
  'high': 'alto',
  'highfalutin': 'pretencioso',
  'hilly': 'montañoso',
  'hispanic': 'hispano',
  'hoary': 'vetusto',
  'hollow': 'hueco',
  'home made': 'casero',
  'homely': 'poco agraciado',
  'homesick': 'nostálgico',
  'honest': 'honesto',
  'honorary': 'honorario',
  'horrific': 'horrible',
  'hostile': 'hostil',
  'hot': 'caliente',
  'hourly': 'por hora',
  'huge': 'enorme',
  'humane': 'humanitario',
  'humble': 'humilde',
  'humid': 'húmedo',
  'hungry': 'hambriento',
  'ice cold': 'helado',
  'icy': 'helado',
  'idle': 'ocioso',
  'ignorant': 'ignorante',
  'ill': 'enfermo',
  'illegal': 'ilegal',
  'illegitimate': 'ilegítimo',
  'illicit': 'ilícito',
  'illiterate': 'analfabeto',
  'immature': 'inmaduro',
  'immediate': 'inmediato',
  'immense': 'inmenso',
  'imminent': 'inminente',
  'impartial': 'imparcial',
  'impending': 'inminente',
  'imperfect': 'imperfecto',
  'implicit': 'implícito',
  'impolite': 'descortés',
  'important': 'importante',
  'improper': 'impropio',
  'in front': 'delante',
  'in situ': 'in situ',
  'in vitro': 'in vitro',
  'inaccurate': 'impreciso',
  'inadequate': 'inadecuado',
  'inane': 'necio',
  'inappropriate': 'inapropiado',
  'incomplete': 'incompleto',
  'inconsiderate': 'desconsiderado',
  'incorrect': 'incorrecto',
  'indefinite': 'indefinido',
  'independent': 'independiente',
  'indeterminate': 'indeterminado',
  'indie': 'independiente',
  'indirect': 'indirecto',
  'indoor': 'interior',
  'indulgent': 'indulgente',
  'inept': 'inepto',
  'inert': 'inerte',
  'inferior': 'inferior',
  'infinite': 'infinito',
  'influential': 'influyente',
  'infrared': 'infrarrojo',
  'infrequent': 'infrecuente',
  'ingrown': 'encarnado',
  'inhibitory': 'inhibidor',
  'initial': 'inicial',
  'innate': 'innato',
  'inner': 'interno',
  'inordinate': 'desmesurado',
  'insane': 'loco',
  'insecure': 'inseguro',
  'inside': 'dentro',
  'insignificant': 'insignificante',
  'insoluble': 'insoluble',
  'insolvent': 'insolvente',
  'insubordinate': 'insubordinado',
  'intact': 'intacto',
  'intellegent': 'inteligente',
  'intense': 'intenso',
  'interdependent': 'interdependiente',
  'intermediate': 'intermedio',
  'intimate': 'íntimo',
  'invaluable': 'invaluable',
  'ipso facto': 'ipso facto',
  'irate': 'furioso',
  'irrelevant': 'irrelevante',
  'jaded': 'hastiado',
  'jittery': 'nervioso',
  'jolly': 'alegre',
  'juicy': 'jugoso',
  'junior': 'júnior',
  'kaput': 'estropeado',
  'keen': 'entusiasta',
  'kind': 'amable',
  'kindly': 'bondadoso',
  'knowing': 'cómplice',
  'lame': 'patético',
  'languid': 'lánguido',
  'lapsed': 'caducado',
  'large': 'grande',
  'last': 'último',
  'late': 'tarde',
  'lately': 'últimamente',
  'lay': 'laico',
  'lean': 'magro',
  'leery': 'receloso',
  'left wing': 'de izquierda',
  'legal': 'legal',
  'legendary': 'legendario',
  'legitimate': 'legítimo',
  'lesser': 'menor',
  'lethal': 'letal',
  'lewd': 'lascivo',
  'lighthearted': 'desenfadado',
  'lightweight': 'ligero',
  'likely': 'probable',
  'lil': 'pequeñito',
  'limp': 'flojo',
  'literal': 'literal',
  'literary': 'literario',
  'literate': 'alfabetizado',
  'little': 'pequeño',
  'live': 'en vivo',
  'lively': 'animado',
  'lofty': 'elevado',
  'lonely': 'solitario',
  'long': 'largo',
  'longstanding': 'de larga data',
  'longterm': 'a largo plazo',
  'longtime': 'de toda la vida',
  'loose': 'suelto',
  'loud': 'ruidoso',
  'lousy': 'pésimo',
  'loutish': 'grosero',
  'lovely': 'encantador',
  'low': 'bajo',
  'lower': 'inferior',
  'lowly': 'humilde',
  'loyal': 'leal',
  'lucky': 'afortunado',
  'lumbering': 'torpe',
  'macabre': 'macabro',
  'macho': 'macho',
  'mad': 'enojado',
  'magenta': 'magenta',
  'main': 'principal',
  'mainstream': 'convencional',
  'major': 'importante',
  'makeshift': 'improvisado',
  'mammalian': 'mamífero',
  'mammoth': 'gigantesco',
  'mandatory': 'obligatorio',
  'many': 'muchos',
  'maritime': 'marítimo',
  'masculine': 'masculino',
  'mature': 'maduro',
  'maverick': 'inconformista',
  'meager': 'escaso',
  'mean': 'malo',
  'measly': 'miserable',
  'meaty': 'carnoso',
  'mediocre': 'mediocre',
  'meek': 'manso',
  'mega': 'mega',
  'mellow': 'relajado',
  'menacing': 'amenazante',
  'mere': 'mero',
  'merry': 'alegre',
  'metropolitan': 'metropolitano',
  'middle aged': 'de mediana edad',
  'mild': 'suave',
  'mindblowing': 'alucinante',
  'mini': 'mini',
  'minor': 'menor',
  'moderate': 'moderado',
  'modern': 'moderno',
  'modest': 'modesto',
  'moist': 'húmedo',
  'moldy': 'mohoso',
  'monochrome': 'monocromo',
  'monthly': 'mensual',
  'moody': 'temperamental',
  'moot': 'discutible',
  'morbid': 'morboso',
  'most': 'la mayoría',
  'muddy': 'fangoso',
  'multifaceted': 'multifacético',
  'multiple': 'múltiple',
  'mundane': 'mundano',
  'mute': 'mudo',
  'naive': 'ingenuo',
  'naked': 'desnudo',
  'narrow': 'estrecho',
  'nausiating': 'nauseabundo',
  'naval': 'naval',
  'near': 'cercano',
  'nearby': 'cercano',
  'neat': 'ordenado',
  'necessary': 'necesario',
  'neighborly': 'amigable',
  'nerdy': 'nerd',
  'new': 'nuevo',
  'newlywed': 'recién casado',
  'next': 'próximo',
  'nibbly': '',
  'nice': 'agradable',
  'nightly': 'nocturno',
  'nimble': 'ágil',
  'no more': 'no más',
  'noble': 'noble',
  'noisy': 'ruidoso',
  'nonchalant': 'despreocupado',
  'nondescript': 'anodino',
  'nonprofit': 'sin fines de lucro',
  'nonstop': 'continuo',
  'normal': 'normal',
  'north': 'norte',
  'northeast': 'noreste',
  'northern': 'norteño',
  'northwest': 'noroeste',
  'nosy': 'entrometido',
  'notable': 'notable',
  'nuanced': 'matizado',
  'nude': 'desnudo',
  'numb': 'entumecido',
  'obediant': 'obediente',
  'obedient': 'obediente',
  'obese': 'obeso',
  'obligated': 'obligado',
  'obscene': 'obsceno',
  'obscure': 'oscuro',
  'observant': 'observador',
  'obsolete': 'obsoleto',
  'odd': 'raro',
  'off guard': 'desprevenido',
  'offbeat': 'poco convencional',
  'offhand': 'espontáneo',
  'offline': 'desconectado',
  'oily': 'aceitoso',
  'ok': 'bien',
  'okay': 'bien',
  'old fashioned': 'anticuado',
  'old school': 'de la vieja escuela',
  'old': 'viejo',
  'on board': 'a bordo',
  'onboard': 'a bordo',
  'one on one': 'uno a uno',
  'ongoing': 'en curso',
  'online': 'en línea',
  'open': 'abierto',
  'orange': 'naranja',
  'orderly': 'ordenado',
  'organic': 'orgánico',
  'orotund': 'grandilocuente',
  'other': 'otro',
  'outdoor': 'al aire libre',
  'outer': 'externo',
  'outside': 'exterior',
  'over': 'terminado',
  'overall': 'general',
  'overboard': 'por la borda',
  'overdue': 'atrasado',
  'overhand': 'por encima',
  'overhead': 'aéreo',
  'overnight': 'de la noche a la mañana',
  'overseas': 'en el extranjero',
  'overt': 'manifiesto',
  'overweight': 'con sobrepeso',
  'overwrought': 'exaltado',
  'own': 'propio',
  'painful': 'doloroso',
  'pale': 'pálido',
  'paranoid': 'paranoico',
  'part time': 'a tiempo parcial',
  'partial': 'parcial',
  'partisan': 'partidista',
  'passionate': 'apasionado',
  'peaceful': 'pacífico',
  'pent up': 'reprimido',
  'perfect': 'perfecto',
  'permanent': 'permanente',
  'pert': 'descarado',
  'pertinent': 'pertinente',
  'perverse': 'perverso',
  'petite': 'menudo',
  'phony': 'falso',
  'picayune': 'insignificante',
  'pink': 'rosa',
  'placid': 'plácido',
  'plaid': 'a cuadros',
  'plain': 'sencillo',
  'pleasant': 'agradable',
  'pointy': 'puntiagudo',
  'polite': 'educado',
  'poor': 'pobre',
  'populist': 'populista',
  'precise': 'preciso',
  'preexisting': 'preexistente',
  'pregnant': 'embarazada',
  'premature': 'prematuro',
  'prepaid': 'prepagado',
  'present': 'presente',
  'pricey': 'caro',
  'prickly': 'espinoso',
  'prima': 'prima',
  'primary': 'primario',
  'prime': 'primordial',
  'prior': 'previo',
  'pristine': 'impecable',
  'private': 'privado',
  'probable': 'probable',
  'profane': 'profano',
  'profound': 'profundo',
  'profuse': 'profuso',
  'prominent': 'prominente',
  'prompt': 'puntual',
  'proper': 'adecuado',
  'proportionate': 'proporcionado',
  'proud': 'orgulloso',
  'proven': 'probado',
  'proximate': 'próximo',
  'public': 'público',
  'punjabi': 'punyabí',
  'puny': 'enclenque',
  'pure': 'puro',
  'purple': 'morado',
  'puzzled': 'perplejo',
  'quack': 'charlatán',
  'quaint': 'pintoresco',
  'quarterly': 'trimestral',
  'quick': 'rápido',
  'quiet': 'callado',
  'rabid': 'rabioso',
  'racial': 'racial',
  'ragged': 'andrajoso',
  'rainy': 'lluvioso',
  'rampant': 'desenfrenado',
  'random': 'aleatorio',
  'rapid': 'rápido',
  'rare': 'raro',
  'raw': 'crudo',
  'ready': 'listo',
  'real': 'real',
  'recalcitrant': 'recalcitrante',
  'recent': 'reciente',
  'recondite': 'recóndito',
  'red': 'rojo',
  'redundant': 'redundante',
  'relevant': 'relevante',
  'reluctant': 'reacio',
  'remote': 'remoto',
  'renowned': 'renombrado',
  'replicate': 'replicado',
  'reprobate': 'réprobo',
  'resistant': 'resistente',
  'resolute': 'resuelto',
  'resonant': 'resonante',
  'retarded': 'retrasado',
  'rheumatoid': 'reumatoide',
  'rich': 'rico',
  'right wing': 'de derecha',
  'right': 'correcto',
  'rightful': 'legítimo',
  'ripe': 'maduro',
  'ritzy': 'lujoso',
  'rival': 'rival',
  'robust': 'robusto',
  'romantic': 'romántico',
  'roomy': 'espacioso',
  'rosy': 'rosado',
  'rotten': 'podrido',
  'rough': 'áspero',
  'round': 'redondo',
  'royal': 'real',
  'rude': 'grosero',
  'sacred': 'sagrado',
  'sad': 'triste',
  'safe': 'seguro',
  'saintly': 'santo',
  'salty': 'salado',
  'same': 'mismo',
  'satisfactory': 'satisfactorio',
  'savvy': 'astuto',
  'scanty': 'escaso',
  'scarce': 'escaso',
  'scarlet': 'escarlata',
  'scary': 'aterrador',
  'scathing': 'mordaz',
  'scholarly': 'erudito',
  'scientific': 'científico',
  'secondary': 'secundario',
  'secure': 'seguro',
  'sedate': 'sosegado',
  'seemly': 'decoroso',
  'select': 'selecto',
  'self sufficient': 'autosuficiente',
  'selfish': 'egoísta',
  'sensory': 'sensorial',
  'separate': 'separado',
  'serene': 'sereno',
  'severe': 'severo',
  'sexy': 'sexy',
  'shady': 'sospechoso',
  'shallow': 'superficial',
  'shameful': 'vergonzoso',
  'sharp': 'afilado',
  'sheer': 'puro',
  'shiny': 'brillante',
  'short': 'corto',
  'shrill': 'estridente',
  'shy': 'tímido',
  'sick': 'enfermo',
  'sickly': 'enfermizo',
  'significant': 'significativo',
  'silly': 'tonto',
  'simple': 'simple',
  'sincere': 'sincero',
  'single': 'soltero',
  'sinister': 'siniestro',
  'skilled': 'hábil',
  'skin deep': 'superficial',
  'skinny': 'flaco',
  'sleek': 'elegante',
  'sleepy': 'somnoliento',
  'slender': 'esbelto',
  'slick': 'pulido',
  'slight': 'leve',
  'slim': 'delgado',
  'slimy': 'viscoso',
  'slippery': 'resbaladizo',
  'slipshod': 'descuidado',
  'slow': 'lento',
  'sly': 'astuto',
  'small': 'pequeño',
  'smart': 'inteligente',
  'smelly': 'apestoso',
  'smooth': 'liso',
  'smug': 'presumido',
  'snobbish': 'esnob',
  'so called': 'supuesto',
  'social': 'social',
  'soft': 'blando',
  'sold out': 'agotado',
  'solemn': 'solemne',
  'solid': 'sólido',
  'soluble': 'soluble',
  'somber': 'sombrío',
  'soon': 'pronto',
  'sophisticated': 'sofisticado',
  'sordid': 'sórdido',
  'sore': 'adolorido',
  'sorry': 'arrepentido',
  'soundproof': 'insonorizado',
  'sour': 'agrio',
  'south': 'sur',
  'southeast': 'sureste',
  'southern': 'sureño',
  'southwest': 'suroeste',
  'soviet': 'soviético',
  'spare': 'de repuesto',
  'sparkly': 'brillante',
  'sparse': 'escaso',
  'special': 'especial',
  'specific': 'específico',
  'speedy': 'veloz',
  'spicy': 'picante',
  'spirited': 'animoso',
  'splendid': 'espléndido',
  'spot on': 'exacto',
  'sprightly': 'vivaz',
  'spry': 'ágil',
  'squeamish': 'aprensivo',
  'stale': 'rancio',
  'stalwart': 'incondicional',
  'stark': 'crudo',
  'stately': 'majestuoso',
  'statutory': 'estatutario',
  'steadfast': 'firme',
  'steady': 'estable',
  'steep': 'empinado',
  'sterile': 'estéril',
  'stern': 'severo',
  'stiff': 'rígido',
  'still': 'quieto',
  'stout': 'robusto',
  'straight forward': 'sencillo',
  'straight': 'recto',
  'straightforward': 'sencillo',
  'strange': 'extraño',
  'stray': 'callejero',
  'strict': 'estricto',
  'stringent': 'riguroso',
  'strong': 'fuerte',
  'strung out': 'drogado',
  'stubborn': 'terco',
  'stupid': 'estúpido',
  'sturdy': 'resistente',
  'stylish': 'elegante',
  'subdued': 'apagado',
  'sublime': 'sublime',
  'subpar': 'deficiente',
  'subsequent': 'posterior',
  'substandard': 'deficiente',
  'substantial': 'sustancial',
  'subtle': 'sutil',
  'suburban': 'suburbano',
  'succinct': 'sucinto',
  'sudden': 'repentino',
  'sui generis': 'sui géneris',
  'super duper': 'súper',
  'super': 'súper',
  'superb': 'magnífico',
  'superficial': 'superficial',
  'supervisory': 'de supervisión',
  'supreme': 'supremo',
  'sure': 'seguro',
  'surly': 'hosco',
  'surreal': 'surrealista',
  'suspect': 'sospechoso',
  'sweet': 'dulce',
  'swift': 'veloz',
  'symbolic': 'simbólico',
  'talented': 'talentoso',
  'tall': 'alto',
  'tame': 'manso',
  'tart': 'ácido',
  'tasteful': 'de buen gusto',
  'tawdry': 'chabacano',
  'teenage': 'adolescente',
  'temperate': 'templado',
  'temporary': 'temporal',
  'tender': 'tierno',
  'tense': 'tenso',
  'terrific': 'estupendo',
  'tertiary': 'terciario',
  'testy': 'irritable',
  'thick': 'grueso',
  'thin': 'delgado',
  'thirsty': 'sediento',
  'thorny': 'espinoso',
  'thoughtful': 'considerado',
  'tidy': 'ordenado',
  'tight': 'apretado',
  'timely': 'oportuno',
  'tiny': 'diminuto',
  'tip top': 'de primera',
  'tired': 'cansado',
  'together': 'juntos',
  'tolerant': 'tolerante',
  'top notch': 'de primera',
  'top': 'superior',
  'torpid': 'aletargado',
  'total': 'total',
  'tough': 'duro',
  'tranquil': 'tranquilo',
  'transparent': 'transparente',
  'trenchant': 'mordaz',
  'trendy': 'de moda',
  'trite': 'trillado',
  'true': 'verdadero',
  'ugly': 'feo',
  'ultimate': 'máximo',
  'ultra': 'ultra',
  'unabated': 'sin disminuir',
  'unappealing': 'poco atractivo',
  'unassuming': 'modesto',
  'unattended': 'desatendido',
  'unauthorized': 'no autorizado',
  'unbecoming': 'impropio',
  'unchallenged': 'indiscutido',
  'uncharted': 'inexplorado',
  'unchecked': 'sin control',
  'uncircumcised': 'incircunciso',
  'unconvincing': 'poco convincente',
  'undecided': 'indeciso',
  'under': 'debajo',
  'underage': 'menor de edad',
  'undercover': 'encubierto',
  'underhand': 'turbio',
  'underlying': 'subyacente',
  'underneath': 'debajo',
  'underprivileged': 'desfavorecido',
  'undersized': 'de tamaño insuficiente',
  'underwater': 'submarino',
  'underway': 'en marcha',
  'underweight': 'bajo de peso',
  'undisclosed': 'no revelado',
  'undisputed': 'indiscutible',
  'undocumented': 'indocumentado',
  'undue': 'indebido',
  'unemployed': 'desempleado',
  'unending': 'interminable',
  'uneven': 'desigual',
  'unexpected': 'inesperado',
  'unexplained': 'inexplicado',
  'unfair': 'injusto',
  'unfinished': 'inacabado',
  'unforeseen': 'imprevisto',
  'unguarded': 'desprotegido',
  'unheard': 'inaudito',
  'uninsured': 'sin seguro',
  'uninterested': 'desinteresado',
  'uninterrupted': 'ininterrumpido',
  'uninvited': 'no invitado',
  'unique': 'único',
  'universal': 'universal',
  'unknown': 'desconocido',
  'unmarried': 'soltero',
  'unmatched': 'inigualable',
  'unmet': 'insatisfecho',
  'unnamed': 'sin nombre',
  'unnoticed': 'inadvertido',
  'unopposed': 'sin oposición',
  'unpaid': 'no remunerado',
  'unparalleled': 'sin igual',
  'unprecedented': 'sin precedentes',
  'unrecognized': 'no reconocido',
  'unregulated': 'no regulado',
  'unrelated': 'no relacionado',
  'unrelenting': 'implacable',
  'unrequited': 'no correspondido',
  'unreserved': 'sin reservas',
  'unresolved': 'sin resolver',
  'unruly': 'rebelde',
  'unseen': 'invisible',
  'unsettled': 'inestable',
  'unsightly': 'antiestético',
  'unsold': 'sin vender',
  'unspent': 'sin gastar',
  'unspoken': 'tácito',
  'unsupervised': 'sin supervisión',
  'unsuspecting': 'desprevenido',
  'untapped': 'sin explotar',
  'untested': 'no probado',
  'untold': 'incalculable',
  'untouched': 'intacto',
  'unused': 'sin usar',
  'unwanted': 'no deseado',
  'unwarranted': 'injustificado',
  'unwieldy': 'engorroso',
  'up front': 'por adelantado',
  'up to date': 'actualizado',
  'upbeat': 'optimista',
  'upper': 'superior',
  'uppity': 'altanero',
  'upscale': 'de lujo',
  'upset': 'molesto',
  'upside down': 'al revés',
  'uptight': 'tenso',
  'urban': 'urbano',
  'urgent': 'urgente',
  'useful': 'útil',
  'usual': 'usual',
  'utter': 'absoluto',
  'uttermost': 'extremo',
  'vacant': 'vacante',
  'vagrant': 'vagabundo',
  'vague': 'vago',
  'vain': 'vanidoso',
  'valuable': 'valioso',
  'vast': 'vasto',
  'vengeful': 'vengativo',
  'verdant': 'frondoso',
  'versatile': 'versátil',
  'vibrant': 'vibrante',
  'vice versa': 'viceversa',
  'vigilant': 'vigilante',
  'vile': 'vil',
  'volatile': 'volátil',
  'vulgar': 'vulgar',
  'wanton': 'desenfrenado',
  'warm': 'cálido',
  'wary': 'cauteloso',
  'wasteful': 'derrochador',
  'watery': 'aguado',
  'weak': 'débil',
  'weary': 'cansado',
  'weatherproof': 'resistente a la intemperie',
  'wee': 'pequeñito',
  'weekly': 'semanal',
  'weird': 'raro',
  'well off': 'acomodado',
  'western': 'occidental',
  'wet': 'mojado',
  'whacked out': 'chiflado',
  'whiny': 'llorón',
  'white': 'blanco',
  'whole': 'entero',
  'wholesale': 'al por mayor',
  'wicked': 'malvado',
  'wide': 'ancho',
  'widespread': 'generalizado',
  'wild': 'salvaje',
  'wily': 'astuto',
  'win win': 'ganar-ganar',
  'windy': 'ventoso',
  'wiry': 'nervudo',
  'wise': 'sabio',
  'wistful': 'melancólico',
  'womanly': 'femenino',
  'wooden': 'de madera',
  'woozy': 'mareado',
  'worthwhile': 'que vale la pena',
  'wound': 'enrollado',
  'wounded': 'herido',
  'wrong': 'equivocado',
  'wrought': 'forjado',
  'wry': 'irónico',
  'yearly': 'anual',
  'yellow': 'amarillo',
  'young': 'joven',
  'zany': 'disparatado',
}
