export default {
  'a lot': 'mucho',
  'abroad': 'en el extranjero',
  'ad nauseam': 'ad náuseam',
  'again': 'otra vez',
  'all but': 'casi',
  'all that': 'tan',
  'almost': 'casi',
  'already': 'ya',
  'also': 'también',
  'always': 'siempre',
  'anymore': 'ya no',
  'anyway': 'de todos modos',
  'alongside': 'junto a',
  'apart': 'aparte',
  'aside': 'aparte',
  'as soon': 'tan pronto',
  'at best': 'en el mejor de los casos',
  'at large': 'en general',
  'at least': 'al menos',
  'at most': 'a lo sumo',
  'at worst': 'en el peor de los casos',
  'away': 'lejos',
  'by far': 'por mucho',
  'by now': 'ya',
  'de jure': 'de iure',
  'de trop': 'de más',
  'definitely': 'definitivamente',
  'directly': 'directamente',
  'en masse': 'en masa',
  'enough': 'bastante',
  'for example': 'por ejemplo',
  'for good': 'para siempre',
  'for sure': 'seguro',
  'forever': 'para siempre',
  'fully': 'completamente',
  'further': 'más',
  'furthermore': 'además',
  'hence': 'por lo tanto',
  'indeed': 'en efecto',
  'instead': 'en cambio',
  'just about': 'casi',
  'just': 'solo',
  'likewise': 'igualmente',
  'kinda': 'medio',
  'maybe': 'quizás',
  'meanwhile': 'mientras tanto',
  'awhile': 'un rato',
  'more': 'más',
  'moreover': 'además',
  'newly': 'recientemente',
  'no longer': 'ya no',
  'not only': 'no solo',
  'not withstanding': 'no obstante',
  'of course': 'por supuesto',
  'often': 'a menudo',
  'once again': 'una vez más',
  'once more': 'otra vez',
  'once': 'una vez',
  'only': 'solo',
  'par excellence': 'por excelencia',
  'per se': 'per se',
  'perhaps': 'quizás',
  'point blank': 'a quemarropa',
  'quite': 'bastante',
  'randomly': 'al azar',
  'rather': 'más bien',
  'really': 'realmente',
  'so': 'tan',
  'somehow': 'de alguna manera',
  'sometimes': 'a veces',
  'somewhat': 'algo',
  'sort of': 'más o menos',
  'seldom': 'rara vez',
  'such': 'tal',
  'then': 'entonces',
  'thus': 'así',
  'too': 'también',
  'totally': 'totalmente',
  'twice': 'dos veces',
  'up to': 'hasta',
  'upwards of': 'más de',
  'tiny bit': 'un poquito',
  'very': 'muy',
  'well': 'bien',
  'backward': 'hacia atrás',
  'hella': 'súper',
  'by no means': 'de ninguna manera',
  'altogether': 'completamente',
  'outright': 'rotundamente',
  'ultimately': 'finalmente',
}
