export default {
  'a': 'un',
  'an': 'un',
  'another': 'otro',
  'any': 'cualquier',
  'both': 'ambos',
  'each': 'cada',
  'else': 'más',
  'every': 'cada',
  'few': 'pocos',
  'least': 'menos',
  'much': 'mucho',
  'neither': 'ninguno',
  'own': 'propio',
  'plenty': 'mucho',
  'some': 'algunos',
  'several': 'varios',
  'that': 'eso',
  'the': 'el',
  'these': 'estos',
  'this': 'esto',
  'those': 'esos',
  'various': 'varios',
  'whatever': 'lo que sea',
  'whichever': 'cualquiera',
  'it': 'eso',
  'they': 'ellos',
  'i': 'yo',
  'them': 'ellos',
  'you': 'tú',
  'she': 'ella',
  'me': 'mí',
  'he': 'él',
  'him': 'él',
  'us': 'nosotros',
  'we': 'nosotros',
  'her': 'su',
  'hers': 'suya',
  'his': 'su',
  'its': 'su',
  'mine': 'mío',
  'my': 'mi',
  'none': 'ninguno',
  'our': 'nuestro',
  'ours': 'nuestro',
  'thy': 'tu',
  'their': 'su',
  'theirs': 'suyo',
  'your': 'tu',
  'yours': 'tuyo',
  'whatsoever': '',
  'whichsoever': '',
  'whoever': 'quienquiera',
  'whom': 'quien',
  'whomever': 'quienquiera',
  'whomsoever': 'quienquiera',
  'whose': 'cuyo',
  'whosesoever': '',
  'whosoever': 'quienquiera',
  'whenever': 'cuando sea',
  'although': 'aunque',
  'and': 'y',
  'because': 'porque',
  'before': 'antes',
  'but': 'pero',
  'if': 'si',
  'how': 'cómo',
  'nor': 'ni',
  'now': 'ahora',
  'or': 'o',
  'since': 'desde',
  'though': 'aunque',
  'while': 'mientras',
  'yet': 'todavía',
  'amen': 'amén',
  'argh': 'agh',
  'boo': 'bu',
  'brr': 'brr',
  'bye': 'chao',
  'congratulations': 'felicidades',
  'dammit': 'maldición',
  'damn': 'maldición',
  'damnit': 'maldición',
  'dang': 'caray',
  'drat': 'rayos',
  'duh': 'obvio',
  'eww': 'puaj',
  'fuck': 'joder',
  'goodbye': 'adiós',
  'gosh': 'caramba',
  'haha': 'jaja',
  'hello': 'hola',
  'hey': 'oye',
  'hi': 'hola',
  'holy': 'santo',
  'hooray': 'hurra',
  'huh': 'eh',
  'lol': 'jajaja',
  'meh': 'bah',
  'mmm': 'mmm',
  'nah': 'nah',
  'nope': 'no',
  'oh': 'oh',
  'oops': 'ups',
  'ouch': 'ay',
  'ow': 'ay',
  'phew': 'uf',
  'phooey': 'bah',
  'please': 'por favor',
  'shit': 'mierda',
  'tsk': 'ts',
  'ugh': 'uf',
  'uh huh': 'ajá',
  'uh oh': 'uy',
  'whew': 'uf',
  'whoa': 'vaya',
  'wtf': 'qué demonios',
  'ya': 'sí',
  'yay': 'yupi',
  'yeah': 'sí',
  'yep': 'sip',
  'yes': 'sí',
  'yikes': 'uy',
  'yipee': 'yupi',
  'heck': 'caray',
  'yippee': 'yupi',
  'yuck': 'puaj',
  'yup': 'sip',
  'about': 'sobre',
  'across': 'a través de',
  'after': 'después',
  'along': 'a lo largo de',
  'amid': 'entre',
  'amidst': 'entre',
  'among': 'entre',
  'amongst': 'entre',
  'apropos': 'a propósito',
  'around': 'alrededor',
  'as': 'como',
  'at': 'en',
  'atop': 'encima de',
  'barring': 'salvo',
  'besides': 'además',
  'between': 'entre',
  'bout': 'sobre',
  'by': 'por',
  'despite': 'a pesar de',
  'down': 'abajo',
  'during': 'durante',
  'except': 'excepto',
  'for': 'para',
  'from': 'de',
  'in': 'en',
  'into': 'en',
  'notwithstanding': 'no obstante',
  'of': 'de',
  'off': '',
  'on': 'sobre',
  'onto': 'sobre',
  'out': 'fuera',
  'than': 'que',
  'thereby': 'así',
  'through': 'a través de',
  'throughout': 'por todo',
  'thru': 'a través de',
  'till': 'hasta',
  'towards': 'hacia',
  'unlike': 'a diferencia de',
  'until': 'hasta',
  'up': 'arriba',
  'upon': 'sobre',
  'versus': 'contra',
  'via': 'vía',
  'whereas': 'mientras que',
  'with': 'con',
  'within': 'dentro de',
  'without': 'sin',
}
