export default {
  'a priori': 'a priori',
  'aberrant': 'aberrante',
  'abject': 'abjeto',
  'ablaze': 'em chamas',
  'able': 'capaz',
  'aboard': 'a bordo',
  'above': 'acima',
  'abreast': 'lado a lado',
  'abrupt': 'abrupto',
  'absent': 'ausente',
  'absolute': 'absoluto',
  'abstract': 'abstrato',
  'abstruse': 'abstruso',
  'absurd': 'absurdo',
  'abundant': 'abundante',
  'accurate': 'preciso',
  'acquiescent': 'aquiescente',
  'actual': 'real',
  'acute': 'agudo',
  'ad hoc': 'ad hoc',
  'ad infinitum': 'ad infinitum',
  'adamant': 'inflexível',
  'adept': 'hábil',
  'adequate': 'adequado',
  'adverse': 'adverso',
  'affectionate': 'carinhoso',
  'affluent': 'abastado',
  'afraid': 'com medo',
  'against': 'contra',
  'aggressive': 'agressivo',
  'agile': 'ágil',
  'agreeable': 'agradável',
  'ahead': 'à frente',
  'alcoholic': 'alcoólico',
  'alight': 'aceso',
  'alike': 'parecido',
  'alive': 'vivo',
  'alkaline': 'alcalino',
  'all': 'todo',
  'alone': 'sozinho',
  'aloof': 'reservado',
  'alright': 'bem',
  'alternate': 'alternado',
  'ample': 'amplo',
  'angry': 'bravo',
  'antiquated': 'antiquado',
  'antique': 'antigo',
  'antsy': 'inquieto',
  'appalled': 'chocado',
  'appalling': 'chocante',
  'apparent': 'aparente',
  'appetizing': 'apetitoso',
  'appropriate': 'apropriado',
  'approximate': 'aproximado',
  'apt': 'apto',
  'arbitrary': 'arbitrário',
  'archival': 'de arquivo',
  'arrogant': 'arrogante',
  'articulate': 'articulado',
  'artificial': 'artificial',
  'artsy': 'artístico',
  'ashen': 'lívido',
  'asleep': 'adormecido',
  'astute': 'astuto',
  'attractive': 'atraente',
  'auditory': 'auditivo',
  'austere': 'austero',
  'authentic': 'autêntico',
  'autoimmune': 'autoimune',
  'avant garde': 'vanguardista',
  'average': 'médio',
  'awake': 'acordado',
  'aware': 'ciente',
  'awesome': 'incrível',
  'awkward': 'desajeitado',
  'backwards': 'para trás',
  'bad': 'ruim',
  'bald': 'careca',
  'bankrupt': 'falido',
  'bare': 'descoberto',
  'barren': 'árido',
  'bawdy': 'indecente',
  'beautiful': 'lindo',
  'behind': 'atrás',
  'belated': 'atrasado',
  'beloved': 'amado',
  'below': 'abaixo',
  'beneath': 'embaixo',
  'beneficial': 'benéfico',
  'benign': 'benigno',
  'bent': 'torto',
  'beside': 'ao lado de',
  'bestselling': 'mais vendido',
  'beyond': 'além',
  'big': 'grande',
  'bigtime': 'de peso',
  'bipartisan': 'bipartidário',
  'bitter': 'amargo',
  'bizarre': 'bizarro',
  'black': 'preto',
  'bland': 'insosso',
  'blind': 'cego',
  'blithe': 'despreocupado',
  'blond': 'loiro',
  'bloody': 'sangrento',
  'blue': 'azul',
  'blunt': 'direto',
  'bogus': 'falso',
  'bold': 'ousado',
  'boldface': 'em negrito',
  'bona fide': 'genuíno',
  'bonafide': 'genuíno',
  'bouncy': 'saltitante',
  'brand new': 'novinho em folha',
  'brash': 'impetuoso',
  'brave': 'corajoso',
  'breathtaking': 'de tirar o fôlego',
  'bright': 'brilhante',
  'brilliant': 'brilhante',
  'brisk': 'enérgico',
  'broad': 'amplo',
  'bronze': 'de bronze',
  'brown': 'marrom',
  'buck naked': 'nu em pelo',
  'buff': 'sarado',
  'burly': 'corpulento',
  'busy': 'ocupado',
  'cagey': 'evasivo',
  'calm': 'calmo',
  'cardiac': 'cardíaco',
  'careful': 'cuidadoso',
  'celebate': 'celibatário',
  'certain': 'certo',
  'cheap': 'barato',
  'cheery': 'alegre',
  'cheesy': 'brega',
  'chewy': 'borrachudo',
  'chilly': 'frio',
  'chintzy': 'cafona',
  'circumspect': 'cauteloso',
  'civil': 'civil',
  'clean': 'limpo',
  'clear': 'claro',
  'clever': 'esperto',
  'clockwise': 'em sentido horário',
  'close': 'próximo',
  'cloudy': 'nublado',
  'coarse': 'áspero',
  'coercive': 'coercitivo',
  'cogent': 'convincente',
  'cognizant': 'ciente',
  'cold': 'frio',
  'colonial': 'colonial',
  'colossal': 'colossal',
  'comatose': 'comatoso',
  'commensurate': 'proporcional',
  'common': 'comum',
  'compassionate': 'compassivo',
  'complete': 'completo',
  'compulsory': 'obrigatório',
  'concave': 'côncavo',
  'conceited': 'convencido',
  'concise': 'conciso',
  'condescending': 'condescendente',
  'conducive': 'propício',
  'congruent': 'congruente',
  'conjoint': 'conjunto',
  'conjugal': 'conjugal',
  'conjugate': 'conjugado',
  'consequent': 'consequente',
  'constant': 'constante',
  'consummate': 'consumado',
  'contradictory': 'contraditório',
  'contrary': 'contrário',
  'contrite': 'arrependido',
  'cool': 'legal',
  'corporate': 'corporativo',
  'correct': 'correto',
  'corrupt': 'corrupto',
  'costly': 'caro',
  'counterclockwise': 'em sentido anti-horário',
  'counterfeit': 'falsificado',
  'covert': 'secreto',
  'cowardly': 'covarde',
  'coy': 'recatado',
  'cozy': 'aconchegante',
  'crafty': 'ardiloso',
  'craven': 'covarde',
  'crazed': 'enlouquecido',
  'creepy': 'arrepiante',
  'crisp': 'crocante',
  'crucial': 'crucial',
  'cruel': 'cruel',
  'crystal clear': 'claríssimo',
  'crystalline': 'cristalino',
  'cuddly': 'fofinho',
  'curly': 'cacheado',
  'curmudgeonly': 'rabugento',
  'customary': 'habitual',
  'cute': 'fofo',
  'cutesy': 'meloso',
  'daily': 'diário',
  'damp': 'úmido',
  'dangerous': 'perigoso',
  'dapper': 'alinhado',
  'dark': 'escuro',
  'de facto': 'de fato',
  'dead': 'morto',
  'deadly': 'mortal',
  'deadpan': 'impassível',
  'deaf': 'surdo',
  'dear': 'querido',
  'deceased': 'falecido',
  'deep': 'profundo',
  'defiant': 'desafiador',
  'definite': 'definido',
  'defuse': 'difuso',
  'degenerate': 'degenerado',
  'deliberate': 'deliberado',
  'delicate': 'delicado',
  'delightful': 'encantador',
  'demure': 'recatado',
  'dense': 'denso',
  'dependent': 'dependente',
  'derelict': 'abandonado',
  'desperate': 'desesperado',
  'despondent': 'desanimado',
  'destitute': 'miserável',
  'desultory': 'desconexo',
  'devoid': 'desprovido',
  'devout': 'devoto',
  'didactic': 'didático',
  'difficult': 'difícil',
  'diffuse': 'difuso',
  'dim': 'tênue',
  'dire': 'terrível',
  'direct': 'direto',
  'dirty': 'sujo',
  'discreet': 'discreto',
  'discrete': 'discreto',
  'diseased': 'doente',
  'disjoint': 'disjunto',
  'disparate': 'díspar',
  'distant': 'distante',
  'distinct': 'distinto',
  'divergent': 'divergente',
  'diverse': 'diverso',
  'divine': 'divino',
  'dizzy': 'tonto',
  'docile': 'dócil',
  'dominant': 'dominante',
  'done': 'feito',
  'dormant': 'adormecido',
  'doting': 'coruja',
  'double': 'duplo',
  'doubtful': 'duvidoso',
  'dreary': 'melancólico',
  'drowsy': 'sonolento',
  'drunk': 'bêbado',
  'dry': 'seco',
  'due': 'devido',
  'dull': 'maçante',
  'dumb': 'burro',
  'eager': 'ávido',
  'early': 'cedo',
  'earthly': 'terreno',
  'east': 'leste',
  'eastern': 'oriental',
  'easy': 'fácil',
  'easygoing': 'tranquilo',
  'eerie': 'sinistro',
  'efficient': 'eficiente',
  'elaborate': 'elaborado',
  'elderly': 'idoso',
  'elegant': 'elegante',
  'elicit': 'ilícito',
  'eloquent': 'eloquente',
  'emergent': 'emergente',
  'eminent': 'eminente',
  'empty': 'vazio',
  'en route': 'a caminho',
  'en suite': 'com suíte',
  'enamored': 'apaixonado',
  'enough': 'suficiente',
  'entire': 'inteiro',
  'equal': 'igual',
  'erect': 'ereto',
  'erstwhile': 'antigo',
  'essential': 'essencial',
  'ethereal': 'etéreo',
  'everyday': 'cotidiano',
  'evil': 'mau',
  'exact': 'exato',
  'exempt': 'isento',
  'expedient': 'conveniente',
  'explicit': 'explícito',
  'express': 'expresso',
  'exquisite': 'requintado',
  'extra': 'extra',
  'extravagant': 'extravagante',
  'extreme': 'extremo',
  'exuberant': 'exuberante',
  'exultant': 'exultante',
  'fabled': 'lendário',
  'faint': 'fraco',
  'fake': 'falso',
  'false': 'falso',
  'famed': 'famoso',
  'familiar': 'familiar',
  'fancy': 'chique',
  'far off': 'longínquo',
  'far reaching': 'abrangente',
  'far': 'distante',
  'fast paced': 'acelerado',
  'fast': 'rápido',
  'faulty': 'defeituoso',
  'faux': 'falso',
  'fed up': 'de saco cheio',
  'feeble': 'débil',
  'feminine': 'feminino',
  'fertile': 'fértil',
  'fervent': 'fervoroso',
  'fierce': 'feroz',
  'fiery': 'ardente',
  'final': 'final',
  'financial': 'financeiro',
  'finite': 'finito',
  'firm': 'firme',
  'flagrant': 'flagrante',
  'flat': 'plano',
  'flirty': 'paquerador',
  'flowery': 'florido',
  'fluent': 'fluente',
  'fluorescent': 'fluorescente',
  'foamy': 'espumoso',
  'folksy': 'popular',
  'fond': 'afeiçoado',
  'foolish': 'tolo',
  'for keeps': 'para valer',
  'foregoing': 'anterior',
  'foreign': 'estrangeiro',
  'foreseeable': 'previsível',
  'forgetful': 'esquecido',
  'formal': 'formal',
  'former': 'antigo',
  'fortunate': 'afortunado',
  'forward': 'atrevido',
  'foul': 'fétido',
  'fragile': 'frágil',
  'fragrant': 'perfumado',
  'frail': 'frágil',
  'frantic': 'frenético',
  'free': 'livre',
  'frequent': 'frequente',
  'fresh': 'fresco',
  'fretful': 'aflito',
  'friendly': 'amigável',
  'frilly': 'cheio de babados',
  'fringe': 'marginal',
  'frozen': 'congelado',
  'frugal': 'frugal',
  'full': 'cheio',
  'fun': 'divertido',
  'funny': 'engraçado',
  'furry': 'peludo',
  'gainful': 'remunerado',
  'gauche': 'sem jeito',
  'gaudy': 'espalhafatoso',
  'gay': 'gay',
  'generic': 'genérico',
  'gentle': 'suave',
  'genuine': 'genuíno',
  'ghastly': 'medonho',
  'ghostly': 'fantasmagórico',
  'giant': 'gigante',
  'giddy': 'eufórico',
  'gigantic': 'gigantesco',
  'glad': 'contente',
  'glib': 'superficial',
  'global': 'global',
  'gloomy': 'sombrio',
  'golden': 'dourado',
  'good': 'bom',
  'goofy': 'bobo',
  'graceful': 'gracioso',
  'grand': 'grandioso',
  'grateful': 'grato',
  'gratis': 'grátis',
  'gray': 'cinza',
  'greasy': 'gorduroso',
  'great': 'ótimo',
  'greedy': 'ganancioso',
  'green': 'verde',
  'grey': 'cinza',
  'grim': 'sombrio',
  'grisly': 'horripilante',
  'grizzled': 'grisalho',
  'groovy': 'maneiro',
  'gross': 'nojento',
  'gruesome': 'macabro',
  'guilty': 'culpado',
  'gung ho': 'empolgado',
  'hairy': 'peludo',
  'hallowed': 'sagrado',
  'handsome': 'bonito',
  'handsy': 'de mão boba',
  'handy': 'prático',
  'happy': 'feliz',
  'hard up': 'sem grana',
  'hard': 'duro',
  'hardcore': 'radical',
  'hardworking': 'trabalhador',
  'hardy': 'resistente',
  'harsh': 'severo',
  'hateful': 'odioso',
  'heady': 'inebriante',
  'hearty': 'caloroso',
  'heavenly': 'celestial',
  'heavy': 'pesado',
  'hefty': 'robusto',
  'hellish': 'infernal',
  'helpful': 'prestativo',
  'hesitant': 'hesitante',
  'high': 'alto',
  'highfalutin': 'pomposo',
  'hilly': 'montanhoso',
  'hispanic': 'hispânico',
  'hoary': 'grisalho',
  'hollow': 'oco',
  'home made': 'caseiro',
  'homely': 'feioso',
  'homesick': 'com saudade de casa',
  'honest': 'honesto',
  'honorary': 'honorário',
  'horrific': 'horrível',
  'hostile': 'hostil',
  'hot': 'quente',
  'hourly': 'de hora em hora',
  'huge': 'enorme',
  'humane': 'humano',
  'humble': 'humilde',
  'humid': 'úmido',
  'hungry': 'faminto',
  'ice cold': 'gelado',
  'icy': 'gelado',
  'idle': 'ocioso',
  'ignorant': 'ignorante',
  'ill': 'doente',
  'illegal': 'ilegal',
  'illegitimate': 'ilegítimo',
  'illicit': 'ilícito',
  'illiterate': 'analfabeto',
  'immature': 'imaturo',
  'immediate': 'imediato',
  'immense': 'imenso',
  'imminent': 'iminente',
  'impartial': 'imparcial',
  'impending': 'iminente',
  'imperfect': 'imperfeito',
  'implicit': 'implícito',
  'impolite': 'indelicado',
  'important': 'importante',
  'improper': 'impróprio',
  'in front': 'na frente',
  'in situ': 'in situ',
  'in vitro': 'in vitro',
  'inaccurate': 'impreciso',
  'inadequate': 'inadequado',
  'inane': 'fútil',
  'inappropriate': 'inapropriado',
  'incomplete': 'incompleto',
  'inconsiderate': 'desatencioso',
  'incorrect': 'incorreto',
  'indefinite': 'indefinido',
  'independent': 'independente',
  'indeterminate': 'indeterminado',
  'indie': 'indie',
  'indirect': 'indireto',
  'indoor': 'coberto',
  'indulgent': 'indulgente',
  'inept': 'inepto',
  'inert': 'inerte',
  'inferior': 'inferior',
  'infinite': 'infinito',
  'influential': 'influente',
  'infrared': 'infravermelho',
  'infrequent': 'infrequente',
  'ingrown': 'encravado',
  'inhibitory': 'inibitório',
  'initial': 'inicial',
  'innate': 'inato',
  'inner': 'interno',
  'inordinate': 'excessivo',
  'insane': 'insano',
  'insecure': 'inseguro',
  'inside': 'dentro',
  'insignificant': 'insignificante',
  'insoluble': 'insolúvel',
  'insolvent': 'insolvente',
  'insubordinate': 'insubordinado',
  'intact': 'intacto',
  'intellegent': 'inteligente',
  'intense': 'intenso',
  'interdependent': 'interdependente',
  'intermediate': 'intermediário',
  'intimate': 'íntimo',
  'invaluable': 'inestimável',
  'ipso facto': 'ipso facto',
  'irate': 'furioso',
  'irrelevant': 'irrelevante',
  'jaded': 'desiludido',
  'jittery': 'agitado',
  'jolly': 'alegre',
  'juicy': 'suculento',
  'junior': 'júnior',
  'kaput': 'pifado',
  'keen': 'aguçado',
  'kind': 'gentil',
  'kindly': 'bondoso',
  'knowing': 'sabido',
  'lame': 'sem graça',
  'languid': 'lânguido',
  'lapsed': 'não praticante',
  'large': 'grande',
  'last': 'último',
  'late': 'atrasado',
  'lately': 'ultimamente',
  'lay': 'leigo',
  'lean': 'enxuto',
  'leery': 'desconfiado',
  'left wing': 'de esquerda',
  'legal': 'legal',
  'legendary': 'lendário',
  'legitimate': 'legítimo',
  'lesser': 'menor',
  'lethal': 'letal',
  'lewd': 'lascivo',
  'lighthearted': 'leve',
  'lightweight': 'leve',
  'likely': 'provável',
  'lil': 'pequenininho',
  'limp': 'mole',
  'literal': 'literal',
  'literary': 'literário',
  'literate': 'alfabetizado',
  'little': 'pequeno',
  'live': 'ao vivo',
  'lively': 'animado',
  'lofty': 'elevado',
  'lonely': 'solitário',
  'long': 'longo',
  'longstanding': 'de longa data',
  'longterm': 'de longo prazo',
  'longtime': 'de longa data',
  'loose': 'solto',
  'loud': 'barulhento',
  'lousy': 'péssimo',
  'loutish': 'grosseiro',
  'lovely': 'adorável',
  'low': 'baixo',
  'lower': 'mais baixo',
  'lowly': 'humilde',
  'loyal': 'leal',
  'lucky': 'sortudo',
  'lumbering': 'pesadão',
  'macabre': 'macabro',
  'macho': 'machão',
  'mad': 'louco',
  'magenta': 'magenta',
  'main': 'principal',
  'mainstream': 'convencional',
  'major': 'principal',
  'makeshift': 'improvisado',
  'mammalian': 'mamífero',
  'mammoth': 'descomunal',
  'mandatory': 'obrigatório',
  'many': 'muitos',
  'maritime': 'marítimo',
  'masculine': 'masculino',
  'mature': 'maduro',
  'maverick': 'rebelde',
  'meager': 'parco',
  'mean': 'malvado',
  'measly': 'mísero',
  'meaty': 'carnudo',
  'mediocre': 'medíocre',
  'meek': 'manso',
  'mega': 'mega',
  'mellow': 'suave',
  'menacing': 'ameaçador',
  'mere': 'mero',
  'merry': 'alegre',
  'metropolitan': 'metropolitano',
  'middle aged': 'de meia-idade',
  'mild': 'ameno',
  'mindblowing': 'alucinante',
  'mini': 'mini',
  'minor': 'menor',
  'moderate': 'moderado',
  'modern': 'moderno',
  'modest': 'modesto',
  'moist': 'úmido',
  'moldy': 'mofado',
  'monochrome': 'monocromático',
  'monthly': 'mensal',
  'moody': 'temperamental',
  'moot': 'discutível',
  'morbid': 'mórbido',
  'most': 'a maioria',
  'muddy': 'enlameado',
  'multifaceted': 'multifacetado',
  'multiple': 'múltiplo',
  'mundane': 'banal',
  'mute': 'mudo',
  'naive': 'ingênuo',
  'naked': 'nu',
  'narrow': 'estreito',
  'nausiating': 'nauseante',
  'naval': 'naval',
  'near': 'próximo',
  'nearby': 'perto',
  'neat': 'caprichado',
  'necessary': 'necessário',
  'neighborly': 'cordial',
  'nerdy': 'nerd',
  'new': 'novo',
  'newlywed': 'recém-casado',
  'next': 'próximo',
  'nibbly': 'de beliscar',
  'nice': 'simpático',
  'nightly': 'noturno',
  'nimble': 'ágil',
  'no more': 'não mais',
  'noble': 'nobre',
  'noisy': 'barulhento',
  'nonchalant': 'indiferente',
  'nondescript': 'indistinto',
  'nonprofit': 'sem fins lucrativos',
  'nonstop': 'sem parar',
  'normal': 'normal',
  'north': 'norte',
  'northeast': 'nordeste',
  'northern': 'do norte',
  'northwest': 'noroeste',
  'nosy': 'bisbilhoteiro',
  'notable': 'notável',
  'nuanced': 'cheio de nuances',
  'nude': 'nu',
  'numb': 'dormente',
  'obediant': 'obediente',
  'obedient': 'obediente',
  'obese': 'obeso',
  'obligated': 'obrigado',
  'obscene': 'obsceno',
  'obscure': 'obscuro',
  'observant': 'observador',
  'obsolete': 'obsoleto',
  'odd': 'estranho',
  'off guard': 'desprevenido',
  'offbeat': 'excêntrico',
  'offhand': 'casual',
  'offline': 'offline',
  'oily': 'oleoso',
  'ok': 'ok',
  'okay': 'ok',
  'old fashioned': 'antiquado',
  'old school': 'à moda antiga',
  'old': 'velho',
  'on board': 'a bordo',
  'onboard': 'a bordo',
  'one on one': 'individual',
  'ongoing': 'em andamento',
  'online': 'online',
  'open': 'aberto',
  'orange': 'laranja',
  'orderly': 'ordeiro',
  'organic': 'orgânico',
  'orotund': 'retumbante',
  'other': 'outro',
  'outdoor': 'ao ar livre',
  'outer': 'externo',
  'outside': 'exterior',
  'over': 'acabado',
  'overall': 'geral',
  'overboard': 'ao mar',
  'overdue': 'atrasado',
  'overhand': 'por cima',
  'overhead': 'no alto',
  'overnight': 'da noite para o dia',
  'overseas': 'no exterior',
  'overt': 'manifesto',
  'overweight': 'acima do peso',
  'overwrought': 'transtornado',
  'own': 'próprio',
  'painful': 'doloroso',
  'pale': 'pálido',
  'paranoid': 'paranoico',
  'part time': 'de meio período',
  'partial': 'parcial',
  'partisan': 'partidário',
  'passionate': 'apaixonado',
  'peaceful': 'pacífico',
  'pent up': 'reprimido',
  'perfect': 'perfeito',
  'permanent': 'permanente',
  'pert': 'atrevido',
  'pertinent': 'pertinente',
  'perverse': 'perverso',
  'petite': 'miúdo',
  'phony': 'falso',
  'picayune': 'insignificante',
  'pink': 'rosa',
  'placid': 'plácido',
  'plaid': 'xadrez',
  'plain': 'simples',
  'pleasant': 'agradável',
  'pointy': 'pontudo',
  'polite': 'educado',
  'poor': 'pobre',
  'populist': 'populista',
  'precise': 'preciso',
  'preexisting': 'preexistente',
  'pregnant': 'grávida',
  'premature': 'prematuro',
  'prepaid': 'pré-pago',
  'present': 'presente',
  'pricey': 'caro',
  'prickly': 'espinhoso',
  'prima': 'primeira',
  'primary': 'primário',
  'prime': 'de primeira',
  'prior': 'anterior',
  'pristine': 'imaculado',
  'private': 'privado',
  'probable': 'provável',
  'profane': 'profano',
  'profound': 'profundo',
  'profuse': 'profuso',
  'prominent': 'proeminente',
  'prompt': 'pontual',
  'proper': 'adequado',
  'proportionate': 'proporcional',
  'proud': 'orgulhoso',
  'proven': 'comprovado',
  'proximate': 'próximo',
  'public': 'público',
  'punjabi': 'punjabi',
  'puny': 'mirrado',
  'pure': 'puro',
  'purple': 'roxo',
  'puzzled': 'perplexo',
  'quack': 'charlatão',
  'quaint': 'pitoresco',
  'quarterly': 'trimestral',
  'quick': 'rápido',
  'quiet': 'quieto',
  'rabid': 'raivoso',
  'racial': 'racial',
  'ragged': 'esfarrapado',
  'rainy': 'chuvoso',
  'rampant': 'desenfreado',
  'random': 'aleatório',
  'rapid': 'rápido',
  'rare': 'raro',
  'raw': 'cru',
  'ready': 'pronto',
  'real': 'real',
  'recalcitrant': 'recalcitrante',
  'recent': 'recente',
  'recondite': 'recôndito',
  'red': 'vermelho',
  'redundant': 'redundante',
  'relevant': 'relevante',
  'reluctant': 'relutante',
  'remote': 'remoto',
  'renowned': 'renomado',
  'replicate': 'replicado',
  'reprobate': 'depravado',
  'resistant': 'resistente',
  'resolute': 'resoluto',
  'resonant': 'ressonante',
  'retarded': 'retardado',
  'rheumatoid': 'reumatoide',
  'rich': 'rico',
  'right wing': 'de direita',
  'right': 'certo',
  'rightful': 'legítimo',
  'ripe': 'maduro',
  'ritzy': 'luxuoso',
  'rival': 'rival',
  'robust': 'robusto',
  'romantic': 'romântico',
  'roomy': 'espaçoso',
  'rosy': 'rosado',
  'rotten': 'podre',
  'rough': 'áspero',
  'round': 'redondo',
  'royal': 'real',
  'rude': 'grosseiro',
  'sacred': 'sagrado',
  'sad': 'triste',
  'safe': 'seguro',
  'saintly': 'santo',
  'salty': 'salgado',
  'same': 'mesmo',
  'satisfactory': 'satisfatório',
  'savvy': 'esperto',
  'scanty': 'escasso',
  'scarce': 'escasso',
  'scarlet': 'escarlate',
  'scary': 'assustador',
  'scathing': 'mordaz',
  'scholarly': 'acadêmico',
  'scientific': 'científico',
  'secondary': 'secundário',
  'secure': 'seguro',
  'sedate': 'pacato',
  'seemly': 'decoroso',
  'select': 'seleto',
  'self sufficient': 'autossuficiente',
  'selfish': 'egoísta',
  'sensory': 'sensorial',
  'separate': 'separado',
  'serene': 'sereno',
  'severe': 'severo',
  'sexy': 'sensual',
  'shady': 'suspeito',
  'shallow': 'raso',
  'shameful': 'vergonhoso',
  'sharp': 'afiado',
  'sheer': 'puro',
  'shiny': 'brilhante',
  'short': 'curto',
  'shrill': 'estridente',
  'shy': 'tímido',
  'sick': 'doente',
  'sickly': 'doentio',
  'significant': 'significativo',
  'silly': 'bobo',
  'simple': 'simples',
  'sincere': 'sincero',
  'single': 'solteiro',
  'sinister': 'sinistro',
  'skilled': 'habilidoso',
  'skin deep': 'superficial',
  'skinny': 'magro',
  'sleek': 'elegante',
  'sleepy': 'sonolento',
  'slender': 'esbelto',
  'slick': 'malandro',
  'slight': 'leve',
  'slim': 'esguio',
  'slimy': 'viscoso',
  'slippery': 'escorregadio',
  'slipshod': 'desleixado',
  'slow': 'lento',
  'sly': 'matreiro',
  'small': 'pequeno',
  'smart': 'inteligente',
  'smelly': 'fedorento',
  'smooth': 'liso',
  'smug': 'presunçoso',
  'snobbish': 'esnobe',
  'so called': 'suposto',
  'social': 'social',
  'soft': 'macio',
  'sold out': 'esgotado',
  'solemn': 'solene',
  'solid': 'sólido',
  'soluble': 'solúvel',
  'somber': 'sombrio',
  'soon': 'em breve',
  'sophisticated': 'sofisticado',
  'sordid': 'sórdido',
  'sore': 'dolorido',
  'sorry': 'arrependido',
  'soundproof': 'à prova de som',
  'sour': 'azedo',
  'south': 'sul',
  'southeast': 'sudeste',
  'southern': 'do sul',
  'southwest': 'sudoeste',
  'soviet': 'soviético',
  'spare': 'reserva',
  'sparkly': 'cintilante',
  'sparse': 'esparso',
  'special': 'especial',
  'specific': 'específico',
  'speedy': 'veloz',
  'spicy': 'apimentado',
  'spirited': 'animado',
  'splendid': 'esplêndido',
  'spot on': 'certeiro',
  'sprightly': 'vivaz',
  'spry': 'ágil',
  'squeamish': 'enjoado',
  'stale': 'amanhecido',
  'stalwart': 'fiel',
  'stark': 'gritante',
  'stately': 'majestoso',
  'statutory': 'estatutário',
  'steadfast': 'firme',
  'steady': 'estável',
  'steep': 'íngreme',
  'sterile': 'estéril',
  'stern': 'severo',
  'stiff': 'rígido',
  'still': 'parado',
  'stout': 'atarracado',
  'straight forward': 'direto',
  'straight': 'reto',
  'straightforward': 'direto',
  'strange': 'estranho',
  'stray': 'perdido',
  'strict': 'rigoroso',
  'stringent': 'rigoroso',
  'strong': 'forte',
  'strung out': 'chapado',
  'stubborn': 'teimoso',
  'stupid': 'estúpido',
  'sturdy': 'resistente',
  'stylish': 'estiloso',
  'subdued': 'contido',
  'sublime': 'sublime',
  'subpar': 'abaixo da média',
  'subsequent': 'subsequente',
  'substandard': 'abaixo do padrão',
  'substantial': 'substancial',
  'subtle': 'sutil',
  'suburban': 'suburbano',
  'succinct': 'sucinto',
  'sudden': 'repentino',
  'sui generis': 'sui generis',
  'super duper': 'superlegal',
  'super': 'super',
  'superb': 'soberbo',
  'superficial': 'superficial',
  'supervisory': 'de supervisão',
  'supreme': 'supremo',
  'sure': 'certo',
  'surly': 'mal-humorado',
  'surreal': 'surreal',
  'suspect': 'suspeito',
  'sweet': 'doce',
  'swift': 'veloz',
  'symbolic': 'simbólico',
  'talented': 'talentoso',
  'tall': 'alto',
  'tame': 'manso',
  'tart': 'azedo',
  'tasteful': 'de bom gosto',
  'tawdry': 'de mau gosto',
  'teenage': 'adolescente',
  'temperate': 'temperado',
  'temporary': 'temporário',
  'tender': 'terno',
  'tense': 'tenso',
  'terrific': 'fantástico',
  'tertiary': 'terciário',
  'testy': 'irritadiço',
  'thick': 'grosso',
  'thin': 'fino',
  'thirsty': 'sedento',
  'thorny': 'espinhoso',
  'thoughtful': 'atencioso',
  'tidy': 'arrumado',
  'tight': 'apertado',
  'timely': 'oportuno',
  'tiny': 'minúsculo',
  'tip top': 'tinindo',
  'tired': 'cansado',
  'together': 'junto',
  'tolerant': 'tolerante',
  'top notch': 'de primeira',
  'top': 'top',
  'torpid': 'letárgico',
  'total': 'total',
  'tough': 'durão',
  'tranquil': 'tranquilo',
  'transparent': 'transparente',
  'trenchant': 'incisivo',
  'trendy': 'da moda',
  'trite': 'batido',
  'true': 'verdadeiro',
  'ugly': 'feio',
  'ultimate': 'definitivo',
  'ultra': 'ultra',
  'unabated': 'incessante',
  'unappealing': 'pouco atraente',
  'unassuming': 'despretensioso',
  'unattended': 'desacompanhado',
  'unauthorized': 'não autorizado',
  'unbecoming': 'impróprio',
  'unchallenged': 'incontestado',
  'uncharted': 'inexplorado',
  'unchecked': 'descontrolado',
  'uncircumcised': 'incircunciso',
  'unconvincing': 'pouco convincente',
  'undecided': 'indeciso',
  'under': 'embaixo',
  'underage': 'menor de idade',
  'undercover': 'disfarçado',
  'underhand': 'sorrateiro',
  'underlying': 'subjacente',
  'underneath': 'por baixo',
  'underprivileged': 'carente',
  'undersized': 'pequeno demais',
  'underwater': 'subaquático',
  'underway': 'em andamento',
  'underweight': 'abaixo do peso',
  'undisclosed': 'não revelado',
  'undisputed': 'incontestável',
  'undocumented': 'não documentado',
  'undue': 'indevido',
  'unemployed': 'desempregado',
  'unending': 'interminável',
  'uneven': 'desigual',
  'unexpected': 'inesperado',
  'unexplained': 'inexplicado',
  'unfair': 'injusto',
  'unfinished': 'inacabado',
  'unforeseen': 'imprevisto',
  'unguarded': 'desprotegido',
  'unheard': 'inédito',
  'uninsured': 'sem seguro',
  'uninterested': 'desinteressado',
  'uninterrupted': 'ininterrupto',
  'uninvited': 'não convidado',
  'unique': 'único',
  'universal': 'universal',
  'unknown': 'desconhecido',
  'unmarried': 'solteiro',
  'unmatched': 'incomparável',
  'unmet': 'não atendido',
  'unnamed': 'sem nome',
  'unnoticed': 'despercebido',
  'unopposed': 'sem oposição',
  'unpaid': 'não pago',
  'unparalleled': 'sem igual',
  'unprecedented': 'sem precedentes',
  'unrecognized': 'não reconhecido',
  'unregulated': 'não regulamentado',
  'unrelated': 'não relacionado',
  'unrelenting': 'implacável',
  'unrequited': 'não correspondido',
  'unreserved': 'irrestrito',
  'unresolved': 'não resolvido',
  'unruly': 'indisciplinado',
  'unseen': 'invisível',
  'unsettled': 'instável',
  'unsightly': 'feio',
  'unsold': 'não vendido',
  'unspent': 'não gasto',
  'unspoken': 'não dito',
  'unsupervised': 'sem supervisão',
  'unsuspecting': 'desavisado',
  'untapped': 'inexplorado',
  'untested': 'não testado',
  'untold': 'incalculável',
  'untouched': 'intocado',
  'unused': 'não utilizado',
  'unwanted': 'indesejado',
  'unwarranted': 'injustificado',
  'unwieldy': 'difícil de manejar',
  'up front': 'franco',
  'up to date': 'atualizado',
  'upbeat': 'otimista',
  'upper': 'superior',
  'uppity': 'metido',
  'upscale': 'de alto padrão',
  'upset': 'chateado',
  'upside down': 'de cabeça para baixo',
  'uptight': 'tenso',
  'urban': 'urbano',
  'urgent': 'urgente',
  'useful': 'útil',
  'usual': 'usual',
  'utter': 'completo',
  'uttermost': 'extremo',
  'vacant': 'vago',
  'vagrant': 'errante',
  'vague': 'vago',
  'vain': 'vaidoso',
  'valuable': 'valioso',
  'vast': 'vasto',
  'vengeful': 'vingativo',
  'verdant': 'verdejante',
  'versatile': 'versátil',
  'vibrant': 'vibrante',
  'vice versa': 'vice-versa',
  'vigilant': 'vigilante',
  'vile': 'vil',
  'volatile': 'volátil',
  'vulgar': 'vulgar',
  'wanton': 'devasso',
  'warm': 'quente',
  'wary': 'cauteloso',
  'wasteful': 'esbanjador',
  'watery': 'aguado',
  'weak': 'fraco',
  'weary': 'exausto',
  'weatherproof': 'à prova de intempéries',
  'wee': 'pequenino',
  'weekly': 'semanal',
  'weird': 'esquisito',
  'well off': 'abastado',
  'western': 'ocidental',
  'wet': 'molhado',
  'whacked out': 'doidão',
  'whiny': 'chorão',
  'white': 'branco',
  'whole': 'inteiro',
  'wholesale': 'no atacado',
  'wicked': 'maligno',
  'wide': 'largo',
  'widespread': 'generalizado',
  'wild': 'selvagem',
  'wily': 'astuto',
  'win win': 'ganha-ganha',
  'windy': 'ventoso',
  'wiry': 'rijo',
  'wise': 'sábio',
  'wistful': 'saudoso',
  'womanly': 'feminino',
  'wooden': 'de madeira',
  'woozy': 'zonzo',
  'worthwhile': 'que vale a pena',
  'wound': 'enrolado',
  'wounded': 'ferido',
  'wrong': 'errado',
  'wrought': 'forjado',
  'wry': 'irônico',
  'yearly': 'anual',
  'yellow': 'amarelo',
  'young': 'jovem',
  'zany': 'maluco',
}
