export default {
  'a lot': 'muito',
  'abroad': 'no exterior',
  'ad nauseam': 'ad nauseam',
  'again': 'de novo',
  'all but': 'quase',
  'all that': 'tão',
  'almost': 'quase',
  'already': 'já',
  'also': 'também',
  'always': 'sempre',
  'anymore': 'mais',
  'anyway': 'de qualquer forma',
  'alongside': 'ao lado',
  'apart': 'separado',
  'aside': 'de lado',
  'as soon': 'assim que',
  'at best': 'na melhor das hipóteses',
  'at large': 'à solta',
  'at least': 'pelo menos',
  'at most': 'no máximo',
  'at worst': 'na pior das hipóteses',
  'away': 'longe',
  'by far': 'de longe',
  'by now': 'a essa altura',
  'de jure': 'de direito',
  'de trop': 'demais',
  'definitely': 'definitivamente',
  'directly': 'diretamente',
  'en masse': 'em massa',
  'enough': 'o suficiente',
  'for example': 'por exemplo',
  'for good': 'de vez',
  'for sure': 'com certeza',
  'forever': 'para sempre',
  'fully': 'completamente',
  'further': 'mais adiante',
  'furthermore': 'além disso',
  'hence': 'portanto',
  'indeed': 'de fato',
  'instead': 'em vez disso',
  'just about': 'praticamente',
  'just': 'apenas',
  'likewise': 'igualmente',
  'kinda': 'meio',
  'maybe': 'talvez',
  'meanwhile': 'enquanto isso',
  'awhile': 'um tempo',
  'more': 'mais',
  'moreover': 'além disso',
  'newly': 'recém',
  'no longer': 'não mais',
  'not only': 'não só',
  'not withstanding': 'não obstante',
  'of course': 'claro',
  'often': 'frequentemente',
  'once again': 'mais uma vez',
  'once more': 'mais uma vez',
  'once': 'uma vez',
  'only': 'só',
  'par excellence': 'por excelência',
  'per se': 'em si',
  'perhaps': 'talvez',
  'point blank': 'à queima-roupa',
  'quite': 'bastante',
  'randomly': 'aleatoriamente',
  'rather': 'um tanto',
  'really': 'realmente',
  'so': 'tão',
  'somehow': 'de alguma forma',
  'sometimes': 'às vezes',
  'somewhat': 'um pouco',
  'sort of': 'meio que',
  'seldom': 'raramente',
  'such': 'tão',
  'then': 'então',
  'thus': 'assim',
  'too': 'também',
  'totally': 'totalmente',
  'twice': 'duas vezes',
  'up to': 'até',
  'upwards of': 'mais de',
  'tiny bit': 'um pouquinho',
  'very': 'muito',
  'well': 'bem',
  'backward': 'para trás',
  'hella': 'pra caramba',
  'by no means': 'de forma alguma',
  'altogether': 'completamente',
  'outright': 'abertamente',
  'ultimately': 'no fim das contas',
}
