export default {
  'a': 'um',
  'an': 'um',
  'another': 'outro',
  'any': 'qualquer',
  'both': 'ambos',
  'each': 'cada',
  'else': 'mais',
  'every': 'todo',
  'few': 'poucos',
  'least': 'menos',
  'much': 'muito',
  'neither': 'nenhum',
  'own': 'próprio',
  'plenty': 'bastante',
  'some': 'alguns',
  'several': 'vários',
  'that': 'isso',
  'the': 'o',
  'these': 'estes',
  'this': 'isto',
  'those': 'aqueles',
  'various': 'diversos',
  'whatever': 'qualquer',
  'whichever': 'qualquer um',
  'it': 'isso',
  'they': 'eles',
  'i': 'eu',
  'them': 'eles',
  'you': 'você',
  'she': 'ela',
  'me': 'mim',
  'he': 'ele',
  'him': 'ele',
  'us': 'nós',
  'we': 'nós',
  'her': 'dela',
  'hers': 'dela',
  'his': 'dele',
  'its': 'seu',
  'mine': 'meu',
  'my': 'meu',
  'none': 'nenhum',
  'our': 'nosso',
  'ours': 'nosso',
  'thy': 'teu',
  'their': 'deles',
  'theirs': 'deles',
  'your': 'seu',
  'yours': 'seu',
  'whatsoever': '',
  'whichsoever': '',
  'whoever': 'quem quer que',
  'whom': 'quem',
  'whomever': 'quem quer que',
  'whomsoever': 'quem quer que',
  'whose': 'cujo',
  'whosesoever': '',
  'whosoever': 'quem quer que',
  'whenever': 'sempre que',
  'although': 'embora',
  'and': 'e',
  'because': 'porque',
  'before': 'antes',
  'but': 'mas',
  'if': 'se',
  'how': 'como',
  'nor': 'nem',
  'now': 'agora',
  'or': 'ou',
  'since': 'desde',
  'though': 'embora',
  'while': 'enquanto',
  'yet': 'ainda',
  'amen': 'amém',
  'argh': 'argh',
  'boo': 'bu',
  'brr': 'brr',
  'bye': 'tchau',
  'congratulations': 'parabéns',
  'dammit': 'droga',
  'damn': 'droga',
  'damnit': 'droga',
  'dang': 'caramba',
  'drat': 'poxa',
  'duh': 'dã',
  'eww': 'eca',
  'fuck': 'porra',
  'goodbye': 'adeus',
  'gosh': 'nossa',
  'haha': 'haha',
  'hello': 'olá',
  'hey': 'ei',
  'hi': 'oi',
  'holy': 'santo',
  'hooray': 'viva',
  'huh': 'hein',
  'lol': 'kkk',
  'meh': 'tanto faz',
  'mmm': 'mmm',
  'nah': 'nem',
  'nope': 'não',
  'oh': 'ah',
  'oops': 'ops',
  'ouch': 'ai',
  'ow': 'ai',
  'phew': 'ufa',
  'phooey': 'ora',
  'please': 'por favor',
  'shit': 'merda',
  'tsk': 'tsc',
  'ugh': 'aff',
  'uh huh': 'aham',
  'uh oh': 'xi',
  'whew': 'ufa',
  'whoa': 'opa',
  'wtf': '',
  'ya': 'é',
  'yay': 'eba',
  'yeah': 'é',
  'yep': 'sim',
  'yes': 'sim',
  'yikes': 'eita',
  'yipee': 'oba',
  'heck': 'droga',
  'yippee': 'oba',
  'yuck': 'eca',
  'yup': 'sim',
  'about': 'sobre',
  'across': 'através',
  'after': 'depois',
  'along': 'ao longo',
  'amid': 'em meio a',
  'amidst': 'em meio a',
  'among': 'entre',
  'amongst': 'entre',
  'apropos': 'a propósito',
  'around': 'ao redor',
  'as': 'como',
  'at': 'em',
  'atop': 'em cima de',
  'barring': 'salvo',
  'besides': 'além de',
  'between': 'entre',
  'bout': 'sobre',
  'by': 'por',
  'despite': 'apesar de',
  'down': 'baixo',
  'during': 'durante',
  'except': 'exceto',
  'for': 'para',
  'from': 'de',
  'in': 'em',
  'into': 'para dentro',
  'notwithstanding': 'não obstante',
  'of': 'de',
  'off': 'fora',
  'on': 'em',
  'onto': 'sobre',
  'out': 'fora',
  'than': 'do que',
  'thereby': 'assim',
  'through': 'através',
  'throughout': 'por todo',
  'thru': 'através',
  'till': 'até',
  'towards': 'em direção a',
  'unlike': 'ao contrário de',
  'until': 'até',
  'up': 'cima',
  'upon': 'sobre',
  'versus': 'contra',
  'via': 'via',
  'whereas': 'ao passo que',
  'with': 'com',
  'within': 'dentro de',
  'without': 'sem',
}
