export default {
  'zero': 'zero',
  'one': 'um',
  'two': 'dois',
  'three': 'três',
  'four': 'quatro',
  'five': 'cinco',
  'six': 'seis',
  'seven': 'sete',
  'eight': 'oito',
  'nine': 'nove',
  'ten': 'dez',
  'eleven': 'onze',
  'twelve': 'doze',
  'thirteen': 'treze',
  'fourteen': 'quatorze',
  'fifteen': 'quinze',
  'sixteen': 'dezesseis',
  'seventeen': 'dezessete',
  'eighteen': 'dezoito',
  'nineteen': 'dezenove',
  'twenty': 'vinte',
  'thirty': 'trinta',
  'forty': 'quarenta',
  'fourty': 'quarenta',
  'fifty': 'cinquenta',
  'sixty': 'sessenta',
  'seventy': 'setenta',
  'eighty': 'oitenta',
  'ninety': 'noventa',
  'thousands': 'milhares',
  'millions': 'milhões',
  'billions': 'bilhões',
  'trillions': 'trilhões',
  'hundred': 'cem',
  'thousand': 'mil',
  'million': 'milhão',
  'billion': 'bilhão',
  'trillion': 'trilhão',
  'quadrillion': 'quatrilhão',
  'quintillion': 'quintilhão',
  'sextillion': 'sextilhão',
  'septillion': 'septilhão',
  'zeroth': 'zerésimo',
  'first': 'primeiro',
  'second': 'segundo',
  'third': 'terceiro',
  'fourth': 'quarto',
  'fifth': 'quinto',
  'sixth': 'sexto',
  'seventh': 'sétimo',
  'eighth': 'oitavo',
  'ninth': 'nono',
  'tenth': 'décimo',
  'eleventh': 'décimo primeiro',
  'twelfth': 'décimo segundo',
  'thirteenth': 'décimo terceiro',
  'fourteenth': 'décimo quarto',
  'fifteenth': 'décimo quinto',
  'sixteenth': 'décimo sexto',
  'seventeenth': 'décimo sétimo',
  'eighteenth': 'décimo oitavo',
  'nineteenth': 'décimo nono',
  'twentieth': 'vigésimo',
  'thirtieth': 'trigésimo',
  'fortieth': 'quadragésimo',
  'fourtieth': 'quadragésimo',
  'fiftieth': 'quinquagésimo',
  'sixtieth': 'sexagésimo',
  'seventieth': 'septuagésimo',
  'eightieth': 'octogésimo',
  'ninetieth': 'nonagésimo',
}
