export default {
  'a lot': 'molto',
  'abroad': 'all\'estero',
  'ad nauseam': 'ad nauseam',
  'again': 'di nuovo',
  'all but': 'quasi',
  'all that': 'così tanto',
  'almost': 'quasi',
  'already': 'già',
  'also': 'anche',
  'always': 'sempre',
  'anymore': 'più',
  'anyway': 'comunque',
  'alongside': 'accanto',
  'apart': 'a parte',
  'aside': 'da parte',
  'as soon': 'appena',
  'at best': 'nel migliore dei casi',
  'at large': 'in generale',
  'at least': 'almeno',
  'at most': 'al massimo',
  'at worst': 'nel peggiore dei casi',
  'away': 'via',
  'by far': 'di gran lunga',
  'by now': 'ormai',
  'de jure': 'de jure',
  'de trop': 'di troppo',
  'definitely': 'sicuramente',
  'directly': 'direttamente',
  'en masse': 'in massa',
  'enough': 'abbastanza',
  'for example': 'per esempio',
  'for good': 'per sempre',
  'for sure': 'di sicuro',
  'forever': 'per sempre',
  'fully': 'pienamente',
  'further': 'ulteriormente',
  'furthermore': 'inoltre',
  'hence': 'quindi',
  'indeed': 'infatti',
  'instead': 'invece',
  'just about': 'quasi',
  'just': 'solo',
  'likewise': 'allo stesso modo',
  'kinda': 'un po\'',
  'maybe': 'forse',
  'meanwhile': 'nel frattempo',
  'awhile': 'per un po\'',
  'more': 'più',
  'moreover': 'inoltre',
  'newly': 'di recente',
  'no longer': 'non più',
  'not only': 'non solo',
  'not withstanding': 'ciononostante',
  'of course': 'certo',
  'often': 'spesso',
  'once again': 'ancora una volta',
  'once more': 'ancora una volta',
  'once': 'una volta',
  'only': 'solo',
  'par excellence': 'per eccellenza',
  'per se': 'di per sé',
  'perhaps': 'forse',
  'point blank': 'a bruciapelo',
  'quite': 'abbastanza',
  'randomly': 'casualmente',
  'rather': 'piuttosto',
  'really': 'davvero',
  'so': 'così',
  'somehow': 'in qualche modo',
  'sometimes': 'a volte',
  'somewhat': 'alquanto',
  'sort of': 'più o meno',
  'seldom': 'raramente',
  'such': 'tale',
  'then': 'allora',
  'thus': 'dunque',
  'too': 'anche',
  'totally': 'totalmente',
  'twice': 'due volte',
  'up to': 'fino a',
  'upwards of': 'oltre',
  'tiny bit': 'un pochino',
  'very': 'molto',
  'well': 'bene',
  'backward': 'all\'indietro',
  'hella': 'troppo',
  'by no means': 'in nessun modo',
  'altogether': 'del tutto',
  'outright': 'completamente',
  'ultimately': 'alla fine',
}
