export default {
  'a': 'un',
  'an': 'un',
  'another': 'altro',
  'any': 'qualsiasi',
  'both': 'entrambi',
  'each': 'ciascuno',
  'else': 'altro',
  'every': 'ogni',
  'few': 'pochi',
  'least': 'meno',
  'much': 'molto',
  'neither': 'nessuno dei due',
  'own': 'proprio',
  'plenty': 'molto',
  'some': 'alcuni',
  'several': 'parecchi',
  'that': 'quello',
  'the': 'il',
  'these': 'questi',
  'this': 'questo',
  'those': 'quelli',
  'various': 'vari',
  'whatever': 'qualunque',
  'whichever': 'qualunque',
  'it': 'esso',
  'they': 'loro',
  'i': 'io',
  'them': 'loro',
  'you': 'tu',
  'she': 'lei',
  'me': 'me',
  'he': 'lui',
  'him': 'lui',
  'us': 'noi',
  'we': 'noi',
  'her': 'suo',
  'hers': 'suo',
  'his': 'suo',
  'its': 'suo',
  'mine': 'mio',
  'my': 'mio',
  'none': 'nessuno',
  'our': 'nostro',
  'ours': 'nostro',
  'thy': 'tuo',
  'their': 'loro',
  'theirs': 'loro',
  'your': 'tuo',
  'yours': 'tuo',
  'whatsoever': '',
  'whichsoever': '',
  'whoever': 'chiunque',
  'whom': 'cui',
  'whomever': 'chiunque',
  'whomsoever': 'chiunque',
  'whose': 'cui',
  'whosesoever': '',
  'whosoever': 'chiunque',
  'whenever': 'ogniqualvolta',
  'although': 'sebbene',
  'and': 'e',
  'because': 'perché',
  'before': 'prima',
  'but': 'ma',
  'if': 'se',
  'how': 'come',
  'nor': 'né',
  'now': 'ora',
  'or': 'o',
  'since': 'da',
  'though': 'però',
  'while': 'mentre',
  'yet': 'ancora',
  'amen': 'amen',
  'argh': 'argh',
  'boo': 'buu',
  'brr': 'brr',
  'bye': 'ciao',
  'congratulations': 'congratulazioni',
  'dammit': 'dannazione',
  'damn': 'dannazione',
  'damnit': 'dannazione',
  'dang': 'accidenti',
  'drat': 'accidenti',
  'duh': '',
  'eww': 'bleah',
  'fuck': 'cazzo',
  'goodbye': 'addio',
  'gosh': 'caspita',
  'haha': 'ahah',
  'hello': 'ciao',
  'hey': 'ehi',
  'hi': 'ciao',
  'holy': 'santo',
  'hooray': 'urrà',
  'huh': 'eh',
  'lol': 'lol',
  'meh': 'mah',
  'mmm': 'mmm',
  'nah': 'no',
  'nope': 'no',
  'oh': 'oh',
  'oops': 'ops',
  'ouch': 'ahi',
  'ow': 'ahi',
  'phew': 'fiù',
  'phooey': 'puah',
  'please': 'per favore',
  'shit': 'merda',
  'tsk': 'tsk',
  'ugh': 'uffa',
  'uh huh': 'mhm',
  'uh oh': 'ohi ohi',
  'whew': 'fiù',
  'whoa': 'wow',
  'wtf': 'che cazzo',
  'ya': 'sì',
  'yay': 'evviva',
  'yeah': 'sì',
  'yep': 'sì',
  'yes': 'sì',
  'yikes': 'mamma mia',
  'yipee': 'evviva',
  'heck': 'cavolo',
  'yippee': 'evviva',
  'yuck': 'che schifo',
  'yup': 'sì',
  'about': 'riguardo a',
  'across': 'attraverso',
  'after': 'dopo',
  'along': 'lungo',
  'amid': 'tra',
  'amidst': 'tra',
  'among': 'tra',
  'amongst': 'tra',
  'apropos': 'a proposito',
  'around': 'intorno',
  'as': 'come',
  'at': 'a',
  'atop': 'in cima a',
  'barring': 'salvo',
  'besides': 'oltre',
  'between': 'tra',
  'bout': 'riguardo a',
  'by': 'da',
  'despite': 'nonostante',
  'down': 'giù',
  'during': 'durante',
  'except': 'tranne',
  'for': 'per',
  'from': 'da',
  'in': 'in',
  'into': 'dentro',
  'notwithstanding': 'nonostante',
  'of': 'di',
  'off': '',
  'on': 'su',
  'onto': 'su',
  'out': 'fuori',
  'than': 'di',
  'thereby': 'così',
  'through': 'attraverso',
  'throughout': 'in tutto',
  'thru': 'attraverso',
  'till': 'fino a',
  'towards': 'verso',
  'unlike': 'a differenza di',
  'until': 'fino a',
  'up': 'su',
  'upon': 'sopra',
  'versus': 'contro',
  'via': 'tramite',
  'whereas': 'mentre',
  'with': 'con',
  'within': 'entro',
  'without': 'senza',
}
