export default {
  'a lot': 'viel',
  'abroad': 'im Ausland',
  'ad nauseam': 'bis zum Überdruss',
  'again': 'wieder',
  'all but': 'fast',
  'all that': 'so',
  'almost': 'fast',
  'already': 'schon',
  'also': 'auch',
  'always': 'immer',
  'anymore': 'nicht mehr',
  'anyway': 'sowieso',
  'alongside': 'daneben',
  'apart': 'auseinander',
  'aside': 'beiseite',
  'as soon': 'sobald',
  'at best': 'bestenfalls',
  'at large': 'auf freiem Fuß',
  'at least': 'mindestens',
  'at most': 'höchstens',
  'at worst': 'schlimmstenfalls',
  'away': 'weg',
  'by far': 'bei weitem',
  'by now': 'inzwischen',
  'de jure': 'de jure',
  'de trop': 'überflüssig',
  'definitely': 'definitiv',
  'directly': 'direkt',
  'en masse': 'en masse',
  'enough': 'genug',
  'for example': 'zum Beispiel',
  'for good': 'für immer',
  'for sure': 'sicher',
  'forever': 'für immer',
  'fully': 'völlig',
  'further': 'weiter',
  'furthermore': 'außerdem',
  'hence': 'daher',
  'indeed': 'tatsächlich',
  'instead': 'stattdessen',
  'just about': 'so gut wie',
  'just': 'nur',
  'likewise': 'ebenso',
  'kinda': 'irgendwie',
  'maybe': 'vielleicht',
  'meanwhile': 'währenddessen',
  'awhile': 'eine Weile',
  'more': 'mehr',
  'moreover': 'außerdem',
  'newly': 'neu',
  'no longer': 'nicht mehr',
  'not only': 'nicht nur',
  'not withstanding': 'trotzdem',
  'of course': 'natürlich',
  'often': 'oft',
  'once again': 'noch einmal',
  'once more': 'noch einmal',
  'once': 'einmal',
  'only': 'nur',
  'par excellence': 'par excellence',
  'per se': 'an sich',
  'perhaps': 'vielleicht',
  'point blank': 'rundheraus',
  'quite': 'ziemlich',
  'randomly': 'zufällig',
  'rather': 'eher',
  'really': 'wirklich',
  'so': 'so',
  'somehow': 'irgendwie',
  'sometimes': 'manchmal',
  'somewhat': 'etwas',
  'sort of': 'irgendwie',
  'seldom': 'selten',
  'such': 'solch',
  'then': 'dann',
  'thus': 'somit',
  'too': 'auch',
  'totally': 'total',
  'twice': 'zweimal',
  'up to': 'bis zu',
  'upwards of': 'über',
  'tiny bit': 'ein bisschen',
  'very': 'sehr',
  'well': 'gut',
  'backward': 'rückwärts',
  'hella': 'voll',
  'by no means': 'keineswegs',
  'altogether': 'insgesamt',
  'outright': 'völlig',
  'ultimately': 'letztendlich',
}
