export default {
  'a': 'ein',
  'an': 'ein',
  'another': 'andere',
  'any': 'irgendein',
  'both': 'beide',
  'each': 'jeder',
  'else': 'sonst',
  'every': 'jeder',
  'few': 'wenige',
  'least': 'am wenigsten',
  'much': 'viel',
  'neither': 'weder',
  'own': 'eigen',
  'plenty': 'reichlich',
  'some': 'einige',
  'several': 'mehrere',
  'that': 'das',
  'the': 'der',
  'these': 'diese',
  'this': 'dies',
  'those': 'jene',
  'various': 'verschiedene',
  'whatever': 'was auch immer',
  'whichever': 'welcher auch immer',
  'it': 'es',
  'they': 'sie',
  'i': 'ich',
  'them': 'sie',
  'you': 'du',
  'she': 'sie',
  'me': 'mich',
  'he': 'er',
  'him': 'ihn',
  'us': 'uns',
  'we': 'wir',
  'her': 'ihr',
  'hers': 'ihrer',
  'his': 'sein',
  'its': 'sein',
  'mine': 'meiner',
  'my': 'mein',
  'none': 'keiner',
  'our': 'unser',
  'ours': 'unserer',
  'thy': 'dein',
  'their': 'ihr',
  'theirs': 'ihrer',
  'your': 'dein',
  'yours': 'deiner',
  'whatsoever': '',
  'whichsoever': '',
  'whoever': 'wer auch immer',
  'whom': 'wen',
  'whomever': 'wen auch immer',
  'whomsoever': 'wen auch immer',
  'whose': 'wessen',
  'whosesoever': '',
  'whosoever': 'wer auch immer',
  'whenever': 'wann immer',
  'although': 'obwohl',
  'and': 'und',
  'because': 'weil',
  'before': 'bevor',
  'but': 'aber',
  'if': 'wenn',
  'how': 'wie',
  'nor': 'noch',
  'now': 'jetzt',
  'or': 'oder',
  'since': 'seit',
  'though': 'obwohl',
  'while': 'während',
  'yet': 'noch',
  'amen': 'amen',
  'argh': 'argh',
  'boo': 'buh',
  'brr': 'brr',
  'bye': 'tschüss',
  'congratulations': 'Glückwunsch',
  'dammit': 'verdammt',
  'damn': 'verdammt',
  'damnit': 'verdammt',
  'dang': 'verflixt',
  'drat': 'verflixt',
  'duh': '',
  'eww': 'igitt',
  'fuck': 'Scheiße',
  'goodbye': 'auf Wiedersehen',
  'gosh': 'meine Güte',
  'haha': 'haha',
  'hello': 'hallo',
  'hey': 'hey',
  'hi': 'hi',
  'holy': 'heilig',
  'hooray': 'hurra',
  'huh': 'hä',
  'lol': 'lol',
  'meh': 'na ja',
  'mmm': 'mmm',
  'nah': 'nö',
  'nope': 'nee',
  'oh': 'oh',
  'oops': 'hoppla',
  'ouch': 'aua',
  'ow': 'au',
  'phew': 'puh',
  'phooey': 'pfui',
  'please': 'bitte',
  'shit': 'Scheiße',
  'tsk': 'ts',
  'ugh': 'bäh',
  'uh huh': 'mhm',
  'uh oh': 'oje',
  'whew': 'puh',
  'whoa': 'wow',
  'wtf': '',
  'ya': 'ja',
  'yay': 'juhu',
  'yeah': 'ja',
  'yep': 'jep',
  'yes': 'ja',
  'yikes': 'huch',
  'yipee': 'juhu',
  'heck': 'verflixt',
  'yippee': 'juhu',
  'yuck': 'igitt',
  'yup': 'jo',
  'about': 'über',
  'across': 'über',
  'after': 'nach',
  'along': 'entlang',
  'amid': 'inmitten',
  'amidst': 'inmitten',
  'among': 'unter',
  'amongst': 'unter',
  'apropos': 'apropos',
  'around': 'um',
  'as': 'als',
  'at': 'bei',
  'atop': 'oben auf',
  'barring': 'außer',
  'besides': 'neben',
  'between': 'zwischen',
  'bout': 'über',
  'by': 'von',
  'despite': 'trotz',
  'down': 'hinunter',
  'during': 'während',
  'except': 'außer',
  'for': 'für',
  'from': 'von',
  'in': 'in',
  'into': 'in',
  'notwithstanding': 'ungeachtet',
  'of': 'von',
  'off': 'ab',
  'on': 'auf',
  'onto': 'auf',
  'out': 'hinaus',
  'than': 'als',
  'thereby': 'dadurch',
  'through': 'durch',
  'throughout': 'überall',
  'thru': 'durch',
  'till': 'bis',
  'towards': 'zu',
  'unlike': 'anders als',
  'until': 'bis',
  'up': 'hoch',
  'upon': 'auf',
  'versus': 'gegen',
  'via': 'via',
  'whereas': 'wohingegen',
  'with': 'mit',
  'within': 'innerhalb',
  'without': 'ohne',
}
