export default {
  'a lot': 'beaucoup',
  'abroad': '',
  'ad nauseam': 'ad nauseam',
  'again': 'encore',
  'all but': 'presque',
  'all that': '',
  'almost': 'presque',
  'already': 'déjà',
  'also': 'aussi',
  'always': 'toujours',
  'anymore': 'plus',
  'anyway': '',
  'alongside': '',
  'apart': 'séparément',
  'aside': '',
  'as soon': '',
  'at best': '',
  'at large': '',
  'at least': '',
  'at most': '',
  'at worst': '',
  'away': 'loin',
  'by far': '',
  'by now': '',
  'de jure': 'de jure',
  'de trop': 'de trop',
  'definitely': 'certainement',
  'directly': 'directement',
  'en masse': 'en masse',
  'enough': 'assez',
  'for example': '',
  'for good': 'définitivement',
  'for sure': 'assurément',
  'forever': 'éternellement',
  'fully': 'pleinement',
  'further': 'davantage',
  'furthermore': '',
  'hence': 'donc',
  'indeed': 'effectivement',
  'instead': 'plutôt',
  'just about': 'quasiment',
  'just': 'juste',
  'likewise': 'pareillement',
  'kinda': 'plutôt',
  'maybe': 'peut-être',
  'meanwhile': 'entre-temps',
  'awhile': '',
  'more': 'plus',
  'moreover': '',
  'newly': 'nouvellement',
  'no longer': 'plus',
  'not only': '',
  'not withstanding': 'néanmoins',
  'of course': 'évidemment',
  'often': 'souvent',
  'once again': '',
  'once more': '',
  'once': '',
  'only': 'seulement',
  'par excellence': 'par excellence',
  'per se': 'per se',
  'perhaps': 'peut-être',
  'point blank': '',
  'quite': 'assez',
  'randomly': 'aléatoirement',
  'rather': 'plutôt',
  'really': 'vraiment',
  'so': 'tellement',
  'somehow': '',
  'sometimes': 'parfois',
  'somewhat': '',
  'sort of': '',
  'seldom': 'rarement',
  'such': 'tel',
  'then': 'alors',
  'thus': 'ainsi',
  'too': 'aussi',
  'totally': 'totalement',
  'twice': '',
  'up to': 'jusqu\'à',
  'upwards of': '',
  'tiny bit': '',
  'very': 'très',
  'well': 'bien',
  'backward': '',
  'hella': 'vachement',
  'by no means': 'aucunement',
  'altogether': 'complètement',
  'outright': 'carrément',
  'ultimately': 'finalement',
}
