export default {
  'a lot': 'たくさん',
  'abroad': '海外',
  'ad nauseam': 'うんざりするほど',
  'again': 'また',
  'all but': 'ほとんど',
  'all that': 'それほど',
  'almost': 'ほとんど',
  'already': 'もう',
  'also': 'また',
  'always': 'いつも',
  'anymore': 'もう',
  'anyway': 'とにかく',
  'alongside': '並んで',
  'apart': '離れて',
  'aside': '脇に',
  'as soon': 'すぐ',
  'at best': 'せいぜい',
  'at large': '全体として',
  'at least': '少なくとも',
  'at most': '多くても',
  'at worst': '最悪の場合',
  'away': '離れて',
  'by far': '断然',
  'by now': '今頃',
  'de jure': '法律上',
  'de trop': '余計',
  'definitely': '間違いなく',
  'directly': '直接',
  'en masse': '一斉に',
  'enough': '十分',
  'for example': '例えば',
  'for good': '永久に',
  'for sure': '確かに',
  'forever': '永遠に',
  'fully': '完全に',
  'further': 'さらに',
  'furthermore': 'さらに',
  'hence': 'それゆえ',
  'indeed': '確かに',
  'instead': '代わりに',
  'just about': 'ほぼ',
  'just': 'ちょうど',
  'likewise': '同様に',
  'kinda': 'ちょっと',
  'maybe': 'たぶん',
  'meanwhile': 'その間',
  'awhile': 'しばらく',
  'more': 'もっと',
  'moreover': 'その上',
  'newly': '新たに',
  'no longer': 'もはや',
  'not only': 'だけでなく',
  'not withstanding': 'にもかかわらず',
  'of course': 'もちろん',
  'often': 'よく',
  'once again': 'もう一度',
  'once more': 'もう一度',
  'once': '一度',
  'only': 'だけ',
  'par excellence': '随一',
  'per se': 'それ自体',
  'perhaps': 'おそらく',
  'point blank': '単刀直入に',
  'quite': 'かなり',
  'randomly': '無作為に',
  'rather': 'むしろ',
  'really': '本当に',
  'so': 'とても',
  'somehow': '何とか',
  'sometimes': '時々',
  'somewhat': 'やや',
  'sort of': 'なんとなく',
  'seldom': 'めったに',
  'such': 'それほど',
  'then': 'それから',
  'thus': 'このように',
  'too': 'も',
  'totally': '全く',
  'twice': '二回',
  'up to': 'まで',
  'upwards of': '以上',
  'tiny bit': '少しだけ',
  'very': 'とても',
  'well': '上手に',
  'backward': '後ろへ',
  'hella': 'めっちゃ',
  'by no means': '決して',
  'altogether': '全部で',
  'outright': '完全に',
  'ultimately': '最終的に',
}
