export default {
  'a lot': 'mycket',
  'abroad': 'utomlands',
  'ad nauseam': 'i det oändliga',
  'again': 'igen',
  'all but': 'nästan',
  'all that': 'så värst',
  'almost': 'nästan',
  'already': 'redan',
  'also': 'också',
  'always': 'alltid',
  'anymore': 'längre',
  'anyway': 'i alla fall',
  'alongside': 'bredvid',
  'apart': 'isär',
  'aside': 'åt sidan',
  'as soon': 'så snart',
  'at best': 'i bästa fall',
  'at large': 'på fri fot',
  'at least': 'åtminstone',
  'at most': 'högst',
  'at worst': 'i värsta fall',
  'away': 'bort',
  'by far': 'överlägset',
  'by now': 'vid det här laget',
  'de jure': 'de jure',
  'de trop': 'överflödig',
  'definitely': 'definitivt',
  'directly': 'direkt',
  'en masse': 'i massor',
  'enough': 'nog',
  'for example': 'till exempel',
  'for good': 'för gott',
  'for sure': 'helt säkert',
  'forever': 'för alltid',
  'fully': 'helt',
  'further': 'vidare',
  'furthermore': 'dessutom',
  'hence': 'därför',
  'indeed': 'verkligen',
  'instead': 'istället',
  'just about': 'nästan',
  'just': 'bara',
  'likewise': 'likaså',
  'kinda': 'typ',
  'maybe': 'kanske',
  'meanwhile': 'under tiden',
  'awhile': 'en stund',
  'more': 'mer',
  'moreover': 'dessutom',
  'newly': 'nyligen',
  'no longer': 'inte längre',
  'not only': 'inte bara',
  'not withstanding': 'oaktat',
  'of course': 'naturligtvis',
  'often': 'ofta',
  'once again': 'återigen',
  'once more': 'en gång till',
  'once': 'en gång',
  'only': 'endast',
  'par excellence': 'par excellence',
  'per se': 'i sig',
  'perhaps': 'kanske',
  'point blank': 'rakt ut',
  'quite': 'ganska',
  'randomly': 'slumpmässigt',
  'rather': 'snarare',
  'really': 'verkligen',
  'so': 'så',
  'somehow': 'på något sätt',
  'sometimes': 'ibland',
  'somewhat': 'något',
  'sort of': 'typ',
  'seldom': 'sällan',
  'such': 'sådan',
  'then': 'då',
  'thus': 'således',
  'too': 'också',
  'totally': 'totalt',
  'twice': 'två gånger',
  'up to': 'upp till',
  'upwards of': 'uppemot',
  'tiny bit': 'lite grann',
  'very': 'väldigt',
  'well': 'bra',
  'backward': 'bakåt',
  'hella': 'sjukt',
  'by no means': 'ingalunda',
  'altogether': 'helt och hållet',
  'outright': 'rentav',
  'ultimately': 'i slutändan',
}
