export default {
  'a': 'en',
  'an': 'en',
  'another': 'en annan',
  'any': 'någon',
  'both': 'båda',
  'each': 'varje',
  'else': 'annars',
  'every': 'varje',
  'few': 'få',
  'least': 'minst',
  'much': 'mycket',
  'neither': 'ingendera',
  'own': 'egen',
  'plenty': 'gott om',
  'some': 'några',
  'several': 'flera',
  'that': 'det',
  'the': 'den',
  'these': 'dessa',
  'this': 'detta',
  'those': 'de där',
  'various': 'olika',
  'whatever': 'vad som helst',
  'whichever': 'vilken som helst',
  'it': 'det',
  'they': 'de',
  'i': 'jag',
  'them': 'dem',
  'you': 'du',
  'she': 'hon',
  'me': 'mig',
  'he': 'han',
  'him': 'honom',
  'us': 'oss',
  'we': 'vi',
  'her': 'hennes',
  'hers': 'hennes',
  'his': 'hans',
  'its': 'dess',
  'mine': 'min',
  'my': 'min',
  'none': 'ingen',
  'our': 'vår',
  'ours': 'vår',
  'thy': 'din',
  'their': 'deras',
  'theirs': 'deras',
  'your': 'din',
  'yours': 'din',
  'whatsoever': '',
  'whichsoever': '',
  'whoever': 'vem som helst',
  'whom': 'vem',
  'whomever': 'vem som helst',
  'whomsoever': 'vem som helst',
  'whose': 'vars',
  'whosesoever': '',
  'whosoever': 'vem som helst',
  'whenever': 'närhelst',
  'although': 'fastän',
  'and': 'och',
  'because': 'eftersom',
  'before': 'innan',
  'but': 'men',
  'if': 'om',
  'how': 'hur',
  'nor': 'inte heller',
  'now': 'nu',
  'or': 'eller',
  'since': 'sedan',
  'though': 'fast',
  'while': 'medan',
  'yet': 'ändå',
  'amen': 'amen',
  'argh': 'argh',
  'boo': 'bu',
  'brr': 'brr',
  'bye': 'hej då',
  'congratulations': 'grattis',
  'dammit': 'fan',
  'damn': 'fan',
  'damnit': 'fan',
  'dang': 'sjutton',
  'drat': 'attans',
  'duh': '',
  'eww': 'usch',
  'fuck': 'fan',
  'goodbye': 'adjö',
  'gosh': 'jösses',
  'haha': 'haha',
  'hello': 'hej',
  'hey': 'hallå',
  'hi': 'hej',
  'holy': 'heliga',
  'hooray': 'hurra',
  'huh': 'va',
  'lol': 'asg',
  'meh': 'äh',
  'mmm': 'mmm',
  'nah': 'nä',
  'nope': 'nix',
  'oh': 'åh',
  'oops': 'hoppsan',
  'ouch': 'aj',
  'ow': 'aj',
  'phew': 'puh',
  'phooey': 'äsch',
  'please': 'snälla',
  'shit': 'skit',
  'tsk': 'tss',
  'ugh': 'usch',
  'uh huh': 'mm',
  'uh oh': 'oj då',
  'whew': 'puh',
  'whoa': 'oj',
  'wtf': '',
  'ya': 'ja',
  'yay': 'jippi',
  'yeah': 'ja',
  'yep': 'japp',
  'yes': 'ja',
  'yikes': 'hu',
  'yipee': 'jippi',
  'heck': 'sjutton',
  'yippee': 'jippi',
  'yuck': 'blä',
  'yup': 'japp',
  'about': 'om',
  'across': 'över',
  'after': 'efter',
  'along': 'längs',
  'amid': 'mitt i',
  'amidst': 'mitt i',
  'among': 'bland',
  'amongst': 'bland',
  'apropos': 'apropå',
  'around': 'runt',
  'as': 'som',
  'at': 'på',
  'atop': 'ovanpå',
  'barring': 'utom',
  'besides': 'förutom',
  'between': 'mellan',
  'bout': 'om',
  'by': 'av',
  'despite': 'trots',
  'down': 'ner',
  'during': 'under',
  'except': 'utom',
  'for': 'för',
  'from': 'från',
  'in': 'i',
  'into': 'in i',
  'notwithstanding': 'oaktat',
  'of': 'av',
  'off': 'av',
  'on': 'på',
  'onto': 'upp på',
  'out': 'ut',
  'than': 'än',
  'thereby': 'därigenom',
  'through': 'genom',
  'throughout': 'genom hela',
  'thru': 'genom',
  'till': 'tills',
  'towards': 'mot',
  'unlike': 'till skillnad från',
  'until': 'tills',
  'up': 'upp',
  'upon': 'på',
  'versus': 'mot',
  'via': 'via',
  'whereas': 'medan',
  'with': 'med',
  'within': 'inom',
  'without': 'utan',
}
