export default {
  'abandon': 'överge',
  'abduct': 'bortföra',
  'abet': 'bistå',
  'abide': 'tåla',
  'abolish': 'avskaffa',
  'abort': 'avbryta',
  'abound': 'överflöda',
  'abscond': 'avvika',
  'absolve': 'frikänna',
  'abuse': 'missbruka',
  'accent': 'betona',
  'accept': 'acceptera',
  'access': 'komma åt',
  'acclimate': 'acklimatisera',
  'accommodate': 'tillgodose',
  'accompany': 'ledsaga',
  'accomplish': 'åstadkomma',
  'accord': 'bevilja',
  'accost': 'antasta',
  'account': 'redogöra',
  'accrue': 'ackumuleras',
  'accuse': 'anklaga',
  'accustom': 'vänja',
  'ace': 'spika',
  'ache': 'värka',
  'achieve': 'uppnå',
  'acknowledge': 'erkänna',
  'acquiesce': 'foga sig',
  'acquire': 'förvärva',
  'act': 'agera',
  'activate': 'aktivera',
  'adapt': 'anpassa',
  'address': 'adressera',
  'adjourn': 'ajournera',
  'adjust': 'justera',
  'administer': 'administrera',
  'admit': 'medge',
  'adopt': 'adoptera',
  'adorn': 'pryda',
  'adsorb': 'adsorbera',
  'advance': 'avancera',
  'advocate': 'förespråka',
  'affix': 'fästa',
  'afford': 'ha råd med',
  'age': 'åldras',
  'agree': 'hålla med',
  'aid': 'hjälpa',
  'aim': 'sikta',
  'air': 'vädra',
  'alarm': 'oroa',
  'align': 'rikta in',
  'allege': 'påstå',
  'allot': 'tilldela',
  'allow': 'tillåta',
  'allude': 'anspela',
  'alter': 'ändra',
  'amalgamate': 'slå samman',
  'amaze': 'förbluffa',
  'amuse': 'roa',
  'analyse': 'analysera',
  'anchor': 'förankra',
  'anger': 'förarga',
  'animate': 'animera',
  'anneal': 'glödga',
  'announce': 'tillkännage',
  'annoy': 'irritera',
  'annul': 'annullera',
  'answer': 'svara',
  'anticipate': 'förutse',
  'appeal': 'vädja',
  'appear': 'dyka upp',
  'appease': 'blidka',
  'apply': 'ansöka',
  'appoint': 'utnämna',
  'appraise': 'värdera',
  'approach': 'närma sig',
  'approve': 'godkänna',
  'arch': 'välva',
  'archive': 'arkivera',
  'argue': 'argumentera',
  'arise': 'uppstå',
  'arm': 'beväpna',
  'armour': 'bepansra',
  'arouse': 'väcka',
  'arrange': 'ordna',
  'arrive': 'anlända',
  'ask': 'fråga',
  'aspire': 'sträva',
  'assail': 'angripa',
  'assemble': 'montera',
  'assert': 'hävda',
  'assess': 'bedöma',
  'assign': 'tilldela',
  'assist': 'assistera',
  'associate': 'associera',
  'assure': 'försäkra',
  'astonish': 'förvåna',
  'attach': 'fästa',
  'attack': 'attackera',
  'attain': 'uppnå',
  'attempt': 'försöka',
  'attest': 'intyga',
  'attract': 'attrahera',
  'auction': 'auktionera',
  'augment': 'utöka',
  'automate': 'automatisera',
  'avert': 'avvärja',
  'avoid': 'undvika',
  'await': 'invänta',
  'awaken': 'väcka',
  'award': 'belöna',
  'babysit': 'sitta barnvakt',
  'back': 'backa',
  'backfire': 'slå tillbaka',
  'baffle': 'förbrylla',
  'bail': 'betala borgen',
  'balance': 'balansera',
  'ban': 'förbjuda',
  'band': 'gå samman',
  'bang': 'smälla',
  'bank': 'sätta in',
  'bar': 'spärra',
  'bargain': 'pruta',
  'barge': 'klampa in',
  'bark': 'skälla',
  'base': 'basera',
  'bash': 'banka',
  'bathe': 'bada',
  'battle': 'strida',
  'be': 'vara',
  'bear': 'bära',
  'beat': 'slå',
  'become': 'bli',
  'beef': 'förstärka',
  'befriend': 'bli vän med',
  'beg': 'tigga',
  'begin': 'börja',
  'beguile': 'förtrolla',
  'behave': 'uppföra sig',
  'behead': 'halshugga',
  'behold': 'skåda',
  'believe': 'tro',
  'belittle': 'förringa',
  'belt': 'smälla till',
  'bend': 'böja',
  'benefit': 'gynna',
  'bequeath': 'testamentera',
  'bestow': 'skänka',
  'bet': 'slå vad',
  'betray': 'förråda',
  'bewilder': 'förvirra',
  'bias': 'snedvrida',
  'bid': 'bjuda',
  'bide': 'bida',
  'bike': 'cykla',
  'bill': 'fakturera',
  'bind': 'binda',
  'biopsy': 'ta biopsi',
  'bit': '',
  'bitch': 'gnälla',
  'bite': 'bita',
  'blame': 'skylla',
  'bleed': 'blöda',
  'blend': 'blanda',
  'blink': 'blinka',
  'blitz': 'storma',
  'block': 'blockera',
  'blow': 'blåsa',
  'blur': 'sudda',
  'board': 'gå ombord',
  'boast': 'skryta',
  'bog': 'köra fast',
  'boil': 'koka',
  'bolster': 'stärka',
  'bomb': 'bomba',
  'bombard': 'bombardera',
  'bond': 'knyta an',
  'bone': 'urbena',
  'book': 'boka',
  'boost': 'öka',
  'boot': 'sparka ut',
  'border': 'gränsa',
  'borrow': 'låna',
  'bother': 'besvära',
  'bottle': 'buteljera',
  'box': 'boxas',
  'boycott': 'bojkotta',
  'brake': 'bromsa',
  'branch': 'förgrena',
  'brand': 'brännmärka',
  'breach': 'bryta mot',
  'break': 'bryta',
  'breastfeed': 'amma',
  'breathe': 'andas',
  'breed': 'avla',
  'bribe': 'muta',
  'bridge': 'överbrygga',
  'bring': 'ta med',
  'broadcast': 'sända',
  'broaden': 'bredda',
  'bruise': 'ge blåmärken',
  'brush': 'borsta',
  'bubble': 'bubbla',
  'buckle': 'spänna fast',
  'budget': 'budgetera',
  'buffer': 'buffra',
  'build': 'bygga',
  'bump': 'stöta',
  'burden': 'belasta',
  'burn': 'bränna',
  'burst': 'brista',
  'bury': 'begrava',
  'bust': 'knäcka',
  'buy': 'köpa',
  'buzz': 'surra',
  'bypass': 'kringgå',
  'cake': 'klumpa sig',
  'call': 'ringa',
  'camp': 'campa',
  'cancel': 'ställa in',
  'canoe': 'paddla kanot',
  'cap': 'begränsa',
  'capture': 'fånga',
  'card': 'kolla leg',
  'care': 'bry sig',
  'careen': 'kränga',
  'cash': 'lösa in',
  'cast': 'kasta',
  'catalog': 'katalogisera',
  'catch': 'fånga',
  'cater': 'catera',
  'caulk': 'täta',
  'cause': 'orsaka',
  'caution': 'varna',
  'cave': 'ge vika',
  'cease': 'upphöra',
  'center': 'centrera',
  'centre': 'centrera',
  'chain': 'kedja fast',
  'chair': 'leda',
  'challenge': 'utmana',
  'change': 'ändra',
  'channel': 'kanalisera',
  'charge': 'debitera',
  'charm': 'charma',
  'chart': 'kartlägga',
  'chase': 'jaga',
  'cheat': 'fuska',
  'check': 'kolla',
  'cheer': 'heja',
  'cherish': 'hålla kär',
  'chew': 'tugga',
  'chip': 'kantstöta',
  'chirp': 'kvittra',
  'choose': 'välja',
  'chop': 'hacka',
  'circle': 'cirkla',
  'circumvent': 'kringgå',
  'cite': 'citera',
  'claim': 'hävda',
  'claw': 'klösa',
  'cleanse': 'rena',
  'click': 'klicka',
  'cling': 'klänga',
  'clip': 'klippa',
  'cloud': 'fördunkla',
  'club': 'klubba',
  'coalesce': 'smälta samman',
  'coat': 'belägga',
  'code': 'koda',
  'coerce': 'tvinga',
  'coexist': 'samexistera',
  'cohabit': 'sammanbo',
  'coin': 'mynta',
  'coincide': 'sammanfalla',
  'collapse': 'kollapsa',
  'collect': 'samla',
  'collide': 'kollidera',
  'collude': 'vara i maskopi',
  'color': 'färga',
  'colour': 'färga',
  'combat': 'bekämpa',
  'combine': 'kombinera',
  'combust': 'fatta eld',
  'come': 'komma',
  'comfort': 'trösta',
  'command': 'befalla',
  'commence': 'påbörja',
  'comment': 'kommentera',
  'commit': 'begå',
  'commute': 'pendla',
  'compel': 'tvinga',
  'compete': 'tävla',
  'compile': 'sammanställa',
  'complement': 'komplettera',
  'comply': 'efterleva',
  'compound': 'förvärra',
  'compromise': 'kompromissa',
  'conceal': 'dölja',
  'conceive': 'föreställa sig',
  'concentrate': 'koncentrera',
  'concern': 'angå',
  'conclude': 'dra slutsatsen',
  'concur': 'instämma',
  'condemn': 'fördöma',
  'condense': 'kondensera',
  'condone': 'överse med',
  'conduct': 'genomföra',
  'confess': 'bekänna',
  'confide': 'anförtro',
  'configure': 'konfigurera',
  'confirm': 'bekräfta',
  'conflict': 'stå i konflikt',
  'conform': 'anpassa sig',
  'confront': 'konfrontera',
  'confuse': 'förvirra',
  'conglomerate': 'klumpa ihop',
  'conjure': 'frammana',
  'connote': 'konnotera',
  'conquer': 'erövra',
  'consent': 'samtycka',
  'conserve': 'bevara',
  'consider': 'överväga',
  'consist': 'bestå',
  'consolidate': 'konsolidera',
  'conspire': 'konspirera',
  'constitute': 'utgöra',
  'constrain': 'begränsa',
  'construct': 'konstruera',
  'consult': 'konsultera',
  'consume': 'konsumera',
  'contact': 'kontakta',
  'contain': 'innehålla',
  'continue': 'fortsätta',
  'contrast': 'kontrastera',
  'contribute': 'bidra',
  'control': 'kontrollera',
  'convene': 'sammankalla',
  'converge': 'konvergera',
  'convert': 'konvertera',
  'convey': 'förmedla',
  'convince': 'övertyga',
  'coordinate': 'samordna',
  'copy': 'kopiera',
  'core': 'kärna ur',
  'corrode': 'korrodera',
  'cost': 'kosta',
  'cough': 'hosta',
  'counsel': 'ge råd',
  'count': 'räkna',
  'couple': 'koppla ihop',
  'court': 'uppvakta',
  'cover': 'täcka',
  'crack': 'knäcka',
  'craft': 'tillverka',
  'crash': 'krascha',
  'crave': 'längta efter',
  'create': 'skapa',
  'credit': 'kreditera',
  'creep': 'krypa',
  'cripple': 'förlama',
  'crop': 'beskära',
  'cross': 'korsa',
  'crowd': 'trängas',
  'crumble': 'smulas',
  'crush': 'krossa',
  'cry': 'gråta',
  'cube': 'tärna',
  'cue': 'ge signal',
  'curb': 'tygla',
  'cure': 'bota',
  'curl': 'rulla ihop',
  'curtail': 'inskränka',
  'curve': 'kröka',
  'cut': 'skära',
  'dab': 'badda',
  'damage': 'skada',
  'dampen': 'dämpa',
  'dance': 'dansa',
  'dare': 'våga',
  'darken': 'mörkna',
  'dart': 'pila',
  'date': 'dejta',
  'daunt': 'avskräcka',
  'deafen': 'göra döv',
  'deal': 'hantera',
  'debark': 'gå i land',
  'debate': 'debattera',
  'debrief': 'debriefa',
  'debug': 'felsöka',
  'debunk': 'vederlägga',
  'debut': 'debutera',
  'deceive': 'bedra',
  'decide': 'besluta',
  'decimate': 'decimera',
  'decipher': 'tyda',
  'declare': 'förklara',
  'decline': 'avböja',
  'decode': 'avkoda',
  'decommission': 'avveckla',
  'decompose': 'förmultna',
  'decouple': 'frikoppla',
  'decrease': 'minska',
  'decree': 'påbjuda',
  'decry': 'fördöma',
  'decrypt': 'dekryptera',
  'deduct': 'dra av',
  'deepen': 'fördjupa',
  'deface': 'vandalisera',
  'defeat': 'besegra',
  'defect': 'hoppa av',
  'define': 'definiera',
  'deform': 'deformera',
  'defraud': 'svindla',
  'defy': 'trotsa',
  'delay': 'försena',
  'delegate': 'delegera',
  'delight': 'glädja',
  'delimit': 'avgränsa',
  'deliver': 'leverera',
  'demand': 'kräva',
  'demean': 'förnedra',
  'demolish': 'riva',
  'denote': 'beteckna',
  'denounce': 'ange',
  'deny': 'förneka',
  'depart': 'avresa',
  'depict': 'avbilda',
  'deplore': 'beklaga',
  'deploy': 'utplacera',
  'deport': 'utvisa',
  'deposit': 'deponera',
  'derail': 'spåra ur',
  'derive': 'härleda',
  'desert': 'överge',
  'design': 'designa',
  'desire': 'åtrå',
  'desist': 'avstå',
  'detach': 'lossa',
  'detail': 'specificera',
  'develop': 'utveckla',
  'devolve': 'urarta',
  'diagnose': 'diagnostisera',
  'die': 'dö',
  'differ': 'skilja sig',
  'dig': 'gräva',
  'digest': 'smälta',
  'diminish': 'förminska',
  'dine': 'äta middag',
  'dip': 'doppa',
  'disable': 'inaktivera',
  'disarm': 'avväpna',
  'disband': 'upplösa',
  'disburse': 'utbetala',
  'discard': 'kassera',
  'discern': 'urskilja',
  'discharge': 'skriva ut',
  'disclaim': 'frånsäga sig',
  'disclose': 'avslöja',
  'discourage': 'avskräcka',
  'discover': 'upptäcka',
  'discuss': 'diskutera',
  'disguise': 'förklä',
  'dish': 'servera',
  'dislike': 'ogilla',
  'dislodge': 'rubba',
  'dismantle': 'nedmontera',
  'dispatch': 'avsända',
  'dispense': 'dela ut',
  'disperse': 'skingra',
  'displace': 'tränga undan',
  'display': 'visa',
  'displease': 'misshaga',
  'dispose': 'göra sig av med',
  'disprove': 'motbevisa',
  'dispute': 'bestrida',
  'disrupt': 'störa',
  'dissolve': 'upplösa',
  'dissuade': 'avråda',
  'distil': 'destillera',
  'distill': 'destillera',
  'distinguish': 'särskilja',
  'distort': 'förvränga',
  'disturb': 'störa',
  'ditch': 'dumpa',
  'dive': 'dyka',
  'diverge': 'gå isär',
  'divert': 'avleda',
  'divest': 'avyttra',
  'divide': 'dela',
  'divorce': 'skiljas',
  'divulge': 'yppa',
  'do': 'göra',
  'dock': 'docka',
  'document': 'dokumentera',
  'dodge': 'väja',
  'doubt': 'tvivla',
  'download': 'ladda ner',
  'draft': 'utarbeta',
  'drag': 'släpa',
  'drain': 'dränera',
  'draw': 'rita',
  'dream': 'drömma',
  'dredge': 'muddra',
  'dress': 'klä',
  'drift': 'driva',
  'drill': 'borra',
  'drink': 'dricka',
  'drip': 'droppa',
  'drive': 'köra',
  'drone': 'mässa',
  'drop': 'tappa',
  'drown': 'drunkna',
  'dub': 'dubba',
  'duel': 'duellera',
  'dump': 'dumpa',
  'duplicate': 'duplicera',
  'dwindle': 'sina',
  'dye': 'färga',
  'earmark': 'öronmärka',
  'earn': 'tjäna',
  'eat': 'äta',
  'echo': 'eka',
  'edge': 'kanta',
  'edit': 'redigera',
  'effect': 'åstadkomma',
  'elapse': 'förflyta',
  'elect': 'välja',
  'elucidate': 'klargöra',
  'elude': 'undgå',
  'embalm': 'balsamera',
  'embark': 'gå ombord',
  'embody': 'förkroppsliga',
  'embrace': 'omfamna',
  'embroider': 'brodera',
  'embroil': 'dra in i',
  'emerge': 'framträda',
  'emphasize': 'betona',
  'empower': 'bemyndiga',
  'enable': 'möjliggöra',
  'enact': 'stifta',
  'encircle': 'omringa',
  'enclose': 'bifoga',
  'encounter': 'möta',
  'encourage': 'uppmuntra',
  'encroach': 'inkräkta',
  'encrypt': 'kryptera',
  'encumber': 'belasta',
  'end': 'sluta',
  'endanger': 'äventyra',
  'endorse': 'stödja',
  'endow': 'förläna',
  'endure': 'uthärda',
  'enforce': 'upprätthålla',
  'engage': 'engagera',
  'engender': 'alstra',
  'engrave': 'gravera',
  'engulf': 'uppsluka',
  'enhance': 'förbättra',
  'enjoy': 'njuta av',
  'enlarge': 'förstora',
  'enlist': 'värva',
  'enquire': 'förhöra sig',
  'enrich': 'berika',
  'enrol': 'skriva in',
  'enroll': 'skriva in',
  'ensue': 'följa',
  'ensure': 'säkerställa',
  'enter': 'gå in',
  'entice': 'locka',
  'entrain': 'rycka med',
  'entrench': 'förskansa',
  'entrust': 'anförtro',
  'envelop': 'omsluta',
  'envisage': 'föreställa sig',
  'envision': 'föreställa sig',
  'envy': 'avundas',
  'equip': 'utrusta',
  'erase': 'radera',
  'erupt': 'få utbrott',
  'escape': 'rymma',
  'eschew': 'undvika',
  'espouse': 'förespråka',
  'establish': 'etablera',
  'estimate': 'uppskatta',
  'etch': 'etsa',
  'evaluate': 'utvärdera',
  'evoke': 'framkalla',
  'evolve': 'utvecklas',
  'exalt': 'upphöja',
  'examine': 'undersöka',
  'exceed': 'överskrida',
  'excel': 'utmärka sig',
  'exchange': 'utbyta',
  'exclaim': 'utropa',
  'exclude': 'utesluta',
  'excuse': 'ursäkta',
  'exercise': 'träna',
  'exert': 'utöva',
  'exhale': 'andas ut',
  'exhaust': 'uttömma',
  'exhibit': 'ställa ut',
  'exhort': 'mana',
  'exhume': 'gräva upp',
  'exist': 'existera',
  'exit': 'gå ut',
  'expect': 'förvänta',
  'expedite': 'påskynda',
  'expel': 'utvisa',
  'experience': 'uppleva',
  'experiment': 'experimentera',
  'expire': 'löpa ut',
  'explain': 'förklara',
  'exploit': 'utnyttja',
  'explore': 'utforska',
  'export': 'exportera',
  'expose': 'blotta',
  'expunge': 'utplåna',
  'extinguish': 'släcka',
  'extol': 'lovprisa',
  'extract': 'utvinna',
  'exude': 'utstråla',
  'eye': 'syna',
  'eyeball': 'ögna',
  'face': 'möta',
  'fail': 'misslyckas',
  'fall': 'falla',
  'falter': 'vackla',
  'farm': 'odla',
  'fasten': 'fästa',
  'favour': 'gynna',
  'fear': 'frukta',
  'feature': 'presentera',
  'feed': 'mata',
  'feel': 'känna',
  'fence': 'fäktas',
  'ferment': 'jäsa',
  'field': 'ta emot',
  'fight': 'slåss',
  'figure': 'lista ut',
  'file': 'arkivera',
  'film': 'filma',
  'filter': 'filtrera',
  'finance': 'finansiera',
  'find': 'hitta',
  'finish': 'avsluta',
  'fire': 'avskeda',
  'fish': 'fiska',
  'fit': 'passa',
  'fix': 'fixa',
  'flag': 'flagga',
  'flake': 'flagna',
  'flame': 'flamma',
  'flare': 'blossa',
  'flash': 'blixtra',
  'flatter': 'smickra',
  'flavor': 'smaksätta',
  'flavour': 'smaksätta',
  'flee': 'fly',
  'flesh': 'konkretisera',
  'fling': 'slänga',
  'flip': 'vända',
  'float': 'flyta',
  'flock': 'flockas',
  'flood': 'översvämma',
  'flow': 'flöda',
  'flower': 'blomma',
  'fly': 'flyga',
  'focus': 'fokusera',
  'fog': 'imma igen',
  'foil': 'omintetgöra',
  'fold': 'vika',
  'foot': 'stå för',
  'forbid': 'förbjuda',
  'force': 'tvinga',
  'forecast': 'prognostisera',
  'foreclose': 'utmäta',
  'forego': 'avstå från',
  'foreshadow': 'förebåda',
  'forewarn': 'förvarna',
  'forfeit': 'förverka',
  'forge': 'smida',
  'forget': 'glömma',
  'forgive': 'förlåta',
  'form': 'forma',
  'format': 'formatera',
  'forsake': 'överge',
  'forsee': 'förutse',
  'forward': 'vidarebefordra',
  'fracture': 'bryta',
  'fragment': 'fragmentera',
  'frame': 'rama in',
  'franchise': '',
  'freeze': 'frysa',
  'freshen': 'fräscha upp',
  'frighten': 'skrämma',
  'frolic': 'skutta',
  'frost': 'glasera',
  'frown': 'rynka pannan',
  'fry': 'steka',
  'fuck': 'knulla',
  'fuel': 'tanka',
  'fulfil': 'uppfylla',
  'function': 'fungera',
  'fund': 'finansiera',
  'fundraise': 'samla in pengar',
  'furnish': 'möblera',
  'fuss': 'tjafsa',
  'fuzz': 'ludda',
  'gag': 'sätta munkavle på',
  'gain': 'vinna',
  'game': 'spela',
  'gang': 'gadda ihop sig',
  'gas': 'gasa',
  'gate': '',
  'gather': 'samla',
  'gaze': 'blicka',
  'gear': 'växla',
  'get': 'få',
  'gift': 'skänka',
  'giggle': 'fnittra',
  'give': 'ge',
  'glare': 'blänga',
  'glean': 'snappa upp',
  'gloss': 'släta över',
  'glow': 'glöda',
  'glue': 'limma',
  'go': 'gå',
  'gossip': 'skvallra',
  'govern': 'styra',
  'grab': 'greppa',
  'grade': 'betygsätta',
  'grapple': 'brottas',
  'grasp': 'fatta',
  'graze': 'beta',
  'greet': 'hälsa',
  'grill': 'grilla',
  'grind': 'mala',
  'grip': 'greppa',
  'ground': 'jorda',
  'grow': 'växa',
  'growth': '',
  'grumble': 'knorra',
  'guarantee': 'garantera',
  'guard': 'vakta',
  'guess': 'gissa',
  'gulp': 'klunka',
  'gun': 'gasa',
  'hack': 'hacka',
  'ham': 'spela över',
  'hammer': 'hamra',
  'hamper': 'hämma',
  'hand': 'räcka',
  'handle': 'hantera',
  'hang': 'hänga',
  'happen': 'hända',
  'harangue': 'läxa upp',
  'harass': 'trakassera',
  'harbour': 'hysa',
  'harm': 'skada',
  'harness': 'ta tillvara',
  'harvest': 'skörda',
  'hash': 'stöta och blöta',
  'hasten': 'påskynda',
  'hatch': 'kläcka',
  'hate': 'hata',
  'haunt': 'hemsöka',
  'have': 'ha',
  'head': 'leda',
  'hear': 'höra',
  'heat': 'värma',
  'hedge': 'gardera',
  'heighten': 'förhöja',
  'help': 'hjälpa',
  'hide': 'gömma',
  'highlight': 'framhäva',
  'hijack': 'kapa',
  'hike': 'vandra',
  'hinder': 'hindra',
  'hint': 'antyda',
  'hire': 'anställa',
  'hit': 'slå',
  'hoist': 'hissa',
  'hold': 'hålla',
  'hole': 'sänka',
  'honor': 'hedra',
  'honour': 'hedra',
  'hook': 'haka fast',
  'hop': 'skutta',
  'hope': 'hoppas',
  'horse': 'busa',
  'house': 'hysa',
  'hug': 'krama',
  'hunt': 'jaga',
  'hurt': 'skada',
  'ignore': 'ignorera',
  'imbue': 'genomsyra',
  'immerse': 'sänka ner',
  'impact': 'påverka',
  'impale': 'spetsa',
  'impart': 'förmedla',
  'imperil': 'äventyra',
  'impinge': 'inkräkta',
  'implement': 'implementera',
  'imply': 'implicera',
  'import': 'importera',
  'impose': 'påtvinga',
  'impoverish': 'utarma',
  'impress': 'imponera',
  'imprison': 'fängsla',
  'improve': 'förbättra',
  'incite': 'uppvigla',
  'incline': 'luta',
  'include': 'inkludera',
  'increase': 'öka',
  'index': 'indexera',
  'indicate': 'indikera',
  'indulge': 'hänge sig',
  'infest': 'angripa',
  'influence': 'påverka',
  'inform': 'informera',
  'infuse': 'ingjuta',
  'ingest': 'inta',
  'inhabit': 'bebo',
  'inhale': 'andas in',
  'inhibit': 'hämma',
  'initiate': 'inleda',
  'injure': 'skada',
  'ink': 'skriva på',
  'inquire': 'förhöra sig',
  'insert': 'infoga',
  'insist': 'insistera',
  'inspire': 'inspirera',
  'install': 'installera',
  'instil': 'ingjuta',
  'instruct': 'instruera',
  'insure': 'försäkra',
  'intent': '',
  'interact': 'interagera',
  'interest': 'intressera',
  'interface': 'samverka',
  'intern': 'praktisera',
  'interpret': 'tolka',
  'interrupt': 'avbryta',
  'interview': 'intervjua',
  'intimidate': 'skrämma',
  'intoxicate': 'berusa',
  'introduce': 'introducera',
  'intrude': 'inkräkta',
  'inundate': 'översvämma',
  'invade': 'invadera',
  'invent': 'uppfinna',
  'invert': 'invertera',
  'invest': 'investera',
  'invoice': 'fakturera',
  'invoke': 'åberopa',
  'involve': 'involvera',
  'irk': 'reta',
  'iron': 'stryka',
  'issue': 'utfärda',
  'jam': 'klämma',
  'jazz': 'piffa upp',
  'join': 'gå med',
  'joke': 'skämta',
  'juggle': 'jonglera',
  'juice': 'pressa',
  'jump': 'hoppa',
  'juxtapose': 'ställa mot varandra',
  'keel': 'kantra',
  'keep': 'behålla',
  'key': 'knappa in',
  'kick': 'sparka',
  'kid': 'skoja',
  'kidnap': 'kidnappa',
  'kill': 'döda',
  'kiss': 'kyssa',
  'kneel': 'knäböja',
  'knock': 'knacka',
  'know': 'veta',
  'label': 'märka',
  'labor': 'slita',
  'labour': 'slita',
  'lace': 'snöra',
  'lack': 'sakna',
  'land': 'landa',
  'languish': 'tyna bort',
  'lap': 'lapa',
  'latch': 'haka fast',
  'laugh': 'skratta',
  'launch': 'lansera',
  'launder': 'tvätta',
  'leach': 'laka ur',
  'lead': 'leda',
  'leak': 'läcka',
  'leap': 'hoppa',
  'learn': 'lära sig',
  'lease': 'leasa',
  'leave': 'lämna',
  'lecture': 'föreläsa',
  'leech': 'snylta',
  'lend': 'låna ut',
  'lengthen': 'förlänga',
  'lessen': 'minska',
  'level': 'jämna',
  'levy': 'uttaxera',
  'license': 'licensiera',
  'lick': 'slicka',
  'lie': 'ljuga',
  'lift': 'lyfta',
  'like': 'gilla',
  'limit': 'begränsa',
  'line': 'kanta',
  'linger': 'dröja',
  'link': 'länka',
  'liquefy': 'göra flytande',
  'liquidate': 'likvidera',
  'list': 'lista',
  'liven': 'liva upp',
  'load': 'lasta',
  'loan': 'låna ut',
  'lobby': 'lobba',
  'lock': 'låsa',
  'log': 'logga',
  'look': 'titta',
  'loot': 'plundra',
  'lose': 'förlora',
  'love': 'älska',
  'lump': 'klumpa ihop',
  'lurk': 'lurpassa',
  'lust': 'åtrå',
  'mail': 'posta',
  'maim': 'lemlästa',
  'maintain': 'underhålla',
  'make': 'göra',
  'manage': 'sköta',
  'mandate': 'påbjuda',
  'manner': '',
  'manoeuvre': 'manövrera',
  'map': 'kartlägga',
  'market': 'marknadsföra',
  'mash': 'mosa',
  'mask': 'maskera',
  'master': 'bemästra',
  'match': 'matcha',
  'matter': 'spela roll',
  'measure': 'mäta',
  'meet': 'träffa',
  'mention': 'nämna',
  'merge': 'slå ihop',
  'merit': 'förtjäna',
  'mess': 'stöka till',
  'milk': 'mjölka',
  'mimic': 'härma',
  'mimick': 'härma',
  'mince': 'finhacka',
  'mind': 'bry sig om',
  'mine': 'bryta',
  'mingle': 'mingla',
  'minus': '',
  'mirror': 'spegla',
  'misplace': 'förlägga',
  'miss': 'missa',
  'mistake': 'förväxla',
  'mix': 'blanda',
  'mock': 'håna',
  'model': 'modellera',
  'mold': 'gjuta',
  'molest': 'antasta',
  'monitor': 'övervaka',
  'monkey': 'apa sig',
  'mop': 'moppa',
  'mount': 'bestiga',
  'mourn': 'sörja',
  'mouth': 'mima',
  'move': 'flytta',
  'mow': 'klippa',
  'multiply': 'multiplicera',
  'murder': 'mörda',
  'name': 'namnge',
  'need': 'behöva',
  'neglect': 'försumma',
  'net': 'håva in',
  'network': 'nätverka',
  'nod': 'nicka',
  'note': 'notera',
  'notice': 'lägga märke till',
  'nourish': 'nära',
  'nurse': 'vårda',
  'obey': 'lyda',
  'object': 'invända',
  'observe': 'observera',
  'obsess': 'älta',
  'obtain': 'erhålla',
  'occupy': 'ockupera',
  'occur': 'inträffa',
  'offer': 'erbjuda',
  'oil': 'olja',
  'omit': 'utelämna',
  'ooze': 'sippra',
  'operate': 'operera',
  'opine': 'tycka',
  'oppose': 'motsätta sig',
  'orbit': 'kretsa',
  'order': 'beställa',
  'orient': 'orientera',
  'outgrow': 'växa ur',
  'outline': 'skissera',
  'outnumber': 'vara fler än',
  'outpace': 'distansera',
  'overlap': 'överlappa',
  'overpass': 'förbigå',
  'oversee': 'övervaka',
  'overshadow': 'överskugga',
  'overturn': 'välta',
  'overuse': 'överanvända',
  'overwhelm': 'överväldiga',
  'owe': 'vara skyldig',
  'pack': 'packa',
  'package': 'paketera',
  'paint': 'måla',
  'pair': 'para ihop',
  'paise': '',
  'pamper': 'skämma bort',
  'pan': 'såga',
  'panic': 'få panik',
  'paralyse': 'paralysera',
  'park': 'parkera',
  'part': 'skiljas',
  'participate': 'delta',
  'party': 'festa',
  'pass': 'passera',
  'paste': 'klistra',
  'patch': 'lappa',
  'patent': 'patentera',
  'patrol': 'patrullera',
  'pause': 'pausa',
  'pave': 'stenlägga',
  'pay': 'betala',
  'peak': 'kulminera',
  'pee': 'kissa',
  'peel': 'skala',
  'peer': 'kika',
  'pen': 'författa',
  'pencil': 'skissa',
  'perceive': 'uppfatta',
  'perform': 'utföra',
  'perfume': 'parfymera',
  'perish': 'förgås',
  'permeate': 'genomtränga',
  'permit': 'tillåta',
  'perplex': 'förbrylla',
  'persevere': 'framhärda',
  'persist': 'kvarstå',
  'persuade': 'övertala',
  'pervade': 'genomsyra',
  'pet': 'klappa',
  'phase': 'fasa ut',
  'phone': 'ringa',
  'photograph': 'fotografera',
  'pick': 'plocka',
  'pile': 'stapla',
  'pin': 'nåla fast',
  'pine': 'tråna',
  'pinpoint': 'precisera',
  'pipe': 'leda i rör',
  'pit': 'ställa mot',
  'pity': 'tycka synd om',
  'pivot': 'svänga',
  'place': 'placera',
  'plan': 'planera',
  'plant': 'plantera',
  'play': 'leka',
  'plce': '',
  'plead': 'vädja',
  'plug': 'täppa till',
  'plummet': 'rasa',
  'plump': 'fluffa',
  'plunge': 'störta',
  'poach': 'tjuvjaga',
  'point': 'peka',
  'poison': 'förgifta',
  'police': 'övervaka',
  'polish': 'polera',
  'poll': 'tillfråga',
  'pollute': 'förorena',
  'pool': 'slå ihop',
  'poop': 'bajsa',
  'pop': 'poppa',
  'pore': 'granska',
  'portray': 'skildra',
  'pose': 'posera',
  'position': 'positionera',
  'possess': 'besitta',
  'post': 'posta',
  'pound': 'bulta',
  'power': 'driva',
  'practice': 'öva',
  'praise': 'berömma',
  'preach': 'predika',
  'preclude': 'utesluta',
  'predetermine': 'förutbestämma',
  'predict': 'förutspå',
  'prefer': 'föredra',
  'preoccupy': 'uppta',
  'preserve': 'bevara',
  'press': 'trycka',
  'presuppose': 'förutsätta',
  'prevail': 'segra',
  'prevent': 'förhindra',
  'prey': 'jaga',
  'price': 'prissätta',
  'pride': 'stoltsera',
  'print': 'skriva ut',
  'probe': 'sondera',
  'proceed': 'fortsätta',
  'process': 'bearbeta',
  'proclaim': 'proklamera',
  'procure': 'anskaffa',
  'prod': 'peta på',
  'produce': 'producera',
  'profess': 'bekänna',
  'profile': 'profilera',
  'program': 'programmera',
  'programme': 'programmera',
  'progress': 'framskrida',
  'prohibit': 'förbjuda',
  'project': 'projicera',
  'promise': 'lova',
  'promote': 'främja',
  'pronounce': 'uttala',
  'prop': 'stötta',
  'propose': 'föreslå',
  'prosper': 'blomstra',
  'protest': 'protestera',
  'protrude': 'sticka ut',
  'prove': 'bevisa',
  'provide': 'tillhandahålla',
  'provoke': 'provocera',
  'prune': 'beskära',
  'psych': 'psyka',
  'publish': 'publicera',
  'puke': 'spy',
  'pump': 'pumpa',
  'punch': 'slå till',
  'punish': 'straffa',
  'purchase': 'köpa',
  'purport': 'utge sig',
  'pursuant': '',
  'pursue': 'eftersträva',
  'push': 'knuffa',
  'put': 'sätta',
  'quash': 'kväsa',
  'quench': 'släcka',
  'question': 'ifrågasätta',
  'quit': 'sluta',
  'quiver': 'darra',
  'quote': 'citera',
  'race': 'tävla',
  'rack': 'plåga',
  'rage': 'rasa',
  'rain': 'regna',
  'raise': 'höja',
  'rake': 'kratta',
  'rally': 'mobilisera',
  'range': 'sträcka sig',
  'rank': 'rangordna',
  'rant': 'orera',
  'rap': 'rappa',
  'rape': 'våldta',
  'rat': 'tjalla',
  'rate': 'betygsätta',
  'rattle': 'skramla',
  'ravish': 'hänföra',
  'reach': 'nå',
  'react': 'reagera',
  'read': 'läsa',
  'realise': 'inse',
  'realize': 'inse',
  'reap': 'skörda',
  'reason': 'resonera',
  'reboot': 'starta om',
  'rebuff': 'avvisa',
  'recall': 'återkalla',
  'receive': 'ta emot',
  'reckon': 'räkna med',
  'reclaim': 'återta',
  'recognize': 'känna igen',
  'reconcile': 'försona',
  'record': 'spela in',
  'recoup': 'ta igen',
  'recover': 'återhämta sig',
  'recycle': 'återvinna',
  'redact': 'maskera',
  'redo': 'göra om',
  'reduce': 'reducera',
  'reel': 'ragla',
  'refactor': 'refaktorera',
  'reference': 'referera',
  'refinance': 'refinansiera',
  'refine': 'förfina',
  'reflect': 'reflektera',
  'refocus': 'omfokusera',
  'reform': 'reformera',
  'refract': 'bryta',
  'refresh': 'friska upp',
  'refuel': 'tanka',
  'refund': 'återbetala',
  'refurbish': 'renovera',
  'refuse': 'vägra',
  'regard': 'betrakta',
  'register': 'registrera',
  'regret': 'ångra',
  'regroup': 'omgruppera',
  'rehearse': 'repetera',
  'reheat': 'värma upp',
  'reimburse': 'ersätta',
  'reinforce': 'förstärka',
  'reject': 'avvisa',
  'rejoice': 'jubla',
  'relate': 'relatera',
  'release': 'släppa',
  'relent': 'ge med sig',
  'relieve': 'lindra',
  'relinquish': 'avstå från',
  'relish': 'njuta av',
  'relive': 'återuppleva',
  'reload': 'ladda om',
  'rely': 'förlita sig',
  'remain': 'förbli',
  'remake': 'göra om',
  'remark': 'anmärka',
  'remedy': 'avhjälpa',
  'remember': 'minnas',
  'remove': 'ta bort',
  'render': 'återge',
  'rendezvous': 'mötas',
  'renew': 'förnya',
  'renounce': 'avsäga sig',
  'rent': 'hyra',
  'reorder': 'beställa om',
  'repair': 'reparera',
  'repeal': 'upphäva',
  'repeat': 'upprepa',
  'repel': 'stöta bort',
  'rephrase': 'omformulera',
  'replace': 'byta ut',
  'replenish': 'fylla på',
  'replicate': 'replikera',
  'reply': 'svara',
  'report': 'rapportera',
  'represent': 'representera',
  'request': 'begära',
  'require': 'kräva',
  'resemble': 'likna',
  'resent': 'känna agg',
  'reserve': 'reservera',
  'reside': 'bo',
  'resign': 'avgå',
  'resist': 'motstå',
  'resolve': 'lösa',
  'resort': 'tillgripa',
  'respect': 'respektera',
  'respond': 'svara',
  'rest': 'vila',
  'restart': 'starta om',
  'restock': 'fylla på',
  'restrain': 'hålla tillbaka',
  'restrict': 'inskränka',
  'restructure': 'omstrukturera',
  'result': 'resultera',
  'resume': 'återuppta',
  'resurface': 'dyka upp igen',
  'retire': 'gå i pension',
  'retrieve': 'hämta',
  'retrofit': 'eftermontera',
  'return': 'återvända',
  'reup': 'förlänga',
  'revamp': 'rusta upp',
  'reveal': 'avslöja',
  'revel': 'frossa',
  'revere': 'vörda',
  'reverse': 'backa',
  'revert': 'återgå',
  'review': 'granska',
  'revisit': 'återbesöka',
  'revive': 'återuppliva',
  'revoke': 'återkalla',
  'revolve': 'rotera',
  'reward': 'belöna',
  'rhyme': 'rimma',
  'rid': 'befria',
  'ride': 'rida',
  'ring': 'ringa',
  'riot': 'göra upplopp',
  'rip': 'riva sönder',
  'ripen': 'mogna',
  'rise': 'stiga',
  'risk': 'riskera',
  'roam': 'ströva',
  'roast': 'rosta',
  'rock': 'gunga',
  'roll': 'rulla',
  'roof': 'lägga tak',
  'root': 'rota',
  'rope': 'binda fast',
  'rot': 'ruttna',
  'rout': 'krossa',
  'route': 'dirigera',
  'rub': 'gnugga',
  'ruin': 'förstöra',
  'rule': 'härska',
  'run': 'springa',
  'rush': 'rusa',
  'rust': 'rosta',
  'sack': 'sparka',
  'sacrifice': 'offra',
  'sadden': 'bedröva',
  'safeguard': 'värna',
  'sail': 'segla',
  'sample': 'prova',
  'satisfy': 'tillfredsställa',
  'say': 'säga',
  'scale': 'skala',
  'scan': 'skanna',
  'scar': 'ärra',
  'scare': 'skrämma',
  'scavenge': 'rota',
  'schedule': 'schemalägga',
  'score': 'göra mål',
  'scrape': 'skrapa',
  'scratch': 'klia',
  'screen': 'sålla',
  'screw': 'skruva',
  'scribble': 'klottra',
  'scroll': 'skrolla',
  'sculpt': 'skulptera',
  'seal': 'försegla',
  'search': 'söka',
  'seat': 'placera',
  'see': 'se',
  'seed': 'så',
  'seek': 'söka',
  'seem': 'verka',
  'sell': 'sälja',
  'send': 'skicka',
  'sense': 'ana',
  'sentence': 'döma',
  'sequester': 'avskilja',
  'serve': 'servera',
  'service': 'serva',
  'set': 'ställa',
  'sever': 'kapa',
  'sew': 'sy',
  'shack': 'flytta ihop',
  'shade': 'skugga',
  'shake': 'skaka',
  'shape': 'forma',
  'share': 'dela',
  'sharpen': 'vässa',
  'shatter': 'splittra',
  'shave': 'raka',
  'shed': 'fälla',
  'sheild': 'skydda',
  'shelter': 'skydda',
  'shift': 'skifta',
  'shine': 'skina',
  'ship': 'skeppa',
  'shiver': 'huttra',
  'shock': 'chocka',
  'shoot': 'skjuta',
  'shop': 'handla',
  'shore': 'stötta upp',
  'shorten': 'förkorta',
  'show': 'visa',
  'shrink': 'krympa',
  'shrivel': 'skrumpna',
  'shuffle': 'blanda',
  'shun': 'sky',
  'side': 'ta parti',
  'sift': 'sikta',
  'sign': 'underteckna',
  'signal': 'signalera',
  'silence': 'tysta',
  'sing': 'sjunga',
  'sink': 'sjunka',
  'sip': 'smutta',
  'sit': 'sitta',
  'size': 'bedöma',
  'skateboard': 'åka skateboard',
  'ski': 'åka skidor',
  'skip': 'hoppa över',
  'slam': 'smälla igen',
  'slay': 'dräpa',
  'sleep': 'sova',
  'slice': 'skiva',
  'slide': 'glida',
  'slip': 'halka',
  'slit': 'skära upp',
  'slouch': 'sjunka ihop',
  'smash': 'krossa',
  'smell': 'lukta',
  'smile': 'le',
  'smirk': 'flina',
  'smoke': 'röka',
  'smuggle': 'smuggla',
  'snake': 'slingra',
  'snap': 'knäppa',
  'snatch': 'rycka',
  'sneak': 'smyga',
  'sneeze': 'nysa',
  'sniff': 'nosa',
  'snow': 'snöa',
  'sob': 'snyfta',
  'solicit': 'be om',
  'solve': 'lösa',
  'soothe': 'lugna',
  'sound': 'låta',
  'sow': 'så',
  'spam': 'spamma',
  'span': 'spänna över',
  'spark': 'tända',
  'spawn': 'ge upphov till',
  'speak': 'tala',
  'speed': 'rusa',
  'spell': 'stava',
  'spend': 'spendera',
  'spill': 'spilla',
  'spin': 'snurra',
  'spiral': 'skena',
  'spit': 'spotta',
  'spite': 'förtreta',
  'splash': 'plaska',
  'splay': 'spreta',
  'split': 'klyva',
  'spoil': 'skämma bort',
  'sponsor': 'sponsra',
  'spoof': 'parodiera',
  'spot': 'få syn på',
  'spray': 'spreja',
  'spread': 'sprida',
  'spring': 'hoppa',
  'sprinkle': 'strö',
  'spruce': 'snygga till',
  'spur': 'sporra',
  'spy': 'spionera',
  'squander': 'slösa bort',
  'square': 'kvadrera',
  'squish': 'mosa',
  'stab': 'knivhugga',
  'stack': 'stapla',
  'staff': 'bemanna',
  'stage': 'iscensätta',
  'stagger': 'stappla',
  'stain': 'fläcka',
  'stake': 'satsa',
  'stalk': 'förfölja',
  'stall': 'förhala',
  'stamp': 'stämpla',
  'stand': 'stå',
  'staple': 'häfta',
  'star': 'spela huvudrollen',
  'stare': 'stirra',
  'start': 'starta',
  'startle': 'skrämma',
  'starve': 'svälta',
  'state': 'uppge',
  'stay': 'stanna',
  'steal': 'stjäla',
  'steer': 'styra',
  'stem': 'hejda',
  'step': 'kliva',
  'stick': 'fastna',
  'stiffen': 'stelna',
  'stifle': 'kväva',
  'sting': 'sticka',
  'stink': 'stinka',
  'stitch': 'sy',
  'stocking': '',
  'stockpile': 'bunkra',
  'stoop': 'böja sig',
  'stop': 'stoppa',
  'store': 'lagra',
  'storm': 'storma',
  'strain': 'anstränga',
  'strangle': 'strypa',
  'stream': 'strömma',
  'strengthen': 'stärka',
  'stress': 'betona',
  'stretch': 'sträcka',
  'strew': 'strö',
  'strike': 'strejka',
  'string': 'trä',
  'strive': 'sträva',
  'stroke': 'smeka',
  'struggle': 'kämpa',
  'study': 'studera',
  'stuff': 'proppa',
  'stumble': 'snubbla',
  'style': 'styla',
  'sub': 'vikariera',
  'subject': 'utsätta',
  'sublimate': 'sublimera',
  'submerge': 'sänka ner',
  'submit': 'lämna in',
  'subside': 'avta',
  'subsist': 'livnära sig',
  'subvert': 'undergräva',
  'succeed': 'lyckas',
  'succumb': 'duka under',
  'suffer': 'lida',
  'suffice': 'räcka',
  'suggest': 'föreslå',
  'suit': 'passa',
  'sum': 'summera',
  'summarise': 'sammanfatta',
  'summon': 'tillkalla',
  'supplement': 'komplettera',
  'supply': 'förse',
  'support': 'stötta',
  'suppose': 'anta',
  'suppress': 'undertrycka',
  'surface': 'dyka upp',
  'surge': 'svalla',
  'surmount': 'övervinna',
  'surpass': 'överträffa',
  'surprise': 'överraska',
  'survey': 'kartlägga',
  'survive': 'överleva',
  'swallow': 'svälja',
  'sway': 'svaja',
  'swear': 'svära',
  'sweat': 'svettas',
  'sweep': 'sopa',
  'sweeten': 'söta',
  'swim': 'simma',
  'swing': 'svinga',
  'swipe': 'svepa',
  'switch': 'byta',
  'tackle': 'tackla',
  'tag': 'tagga',
  'tailor': 'skräddarsy',
  'take part': 'delta',
  'take': 'ta',
  'talk': 'prata',
  'tally': 'räkna samman',
  'tamper': 'mixtra',
  'tangle': 'trassla',
  'target': 'rikta in sig på',
  'tarnish': 'fläcka',
  'taste': 'smaka',
  'tax': 'beskatta',
  'teach': 'lära ut',
  'tear': 'riva sönder',
  'tease': 'retas',
  'tee': '',
  'tell': 'berätta',
  'temper': 'härda',
  'tempt': 'fresta',
  'test': 'testa',
  'text': 'sms:a',
  'thank': 'tacka',
  'think': 'tänka',
  'thread': 'trä',
  'threaten': 'hota',
  'thrive': 'frodas',
  'throw': 'kasta',
  'thrust': 'stöta',
  'thwart': 'omintetgöra',
  'tick': 'ticka',
  'tide': '',
  'tie': 'knyta',
  'tile': 'kakla',
  'time': 'tajma',
  'tip': 'tippa',
  'tire': 'trötta ut',
  'toll': 'klämta',
  'tone': 'tona',
  'top': 'toppa',
  'topple': 'störta',
  'torture': 'tortera',
  'toss': 'slänga',
  'total': 'summera',
  'touch': 'röra',
  'toughen': 'härda',
  'tour': 'turnera',
  'track': 'spåra',
  'trade': 'handla',
  'traffick': 'langa',
  'train': 'träna',
  'trample': 'trampa ner',
  'transact': 'göra affärer',
  'transfer': 'överföra',
  'transform': 'förvandla',
  'transition': 'övergå',
  'transpire': 'framgå',
  'transport': 'transportera',
  'trap': 'snärja',
  'travel': 'resa',
  'treat': 'behandla',
  'trek': 'vandra',
  'tremble': 'darra',
  'trend': 'trenda',
  'tribute': '',
  'trick': 'lura',
  'trickle': 'sippra',
  'trigger': 'utlösa',
  'trim': 'trimma',
  'trip': 'snubbla',
  'trot': 'trava',
  'trouble': 'bekymra',
  'trust': 'lita på',
  'tumble': 'tumla',
  'tune': 'stämma',
  'tunnel': 'gräva tunnel',
  'turn': 'vända',
  'twin': 'para ihop',
  'twist': 'vrida',
  'type': 'skriva',
  'uncover': 'avtäcka',
  'undercut': 'underskrida',
  'undergo': 'genomgå',
  'understand': 'förstå',
  'undervalue': 'undervärdera',
  'underwhelm': 'göra besviken',
  'undo': 'ångra',
  'unearth': 'gräva fram',
  'unfounded': '',
  'unleash': 'släppa lös',
  'unlock': 'låsa upp',
  'unplug': 'koppla ur',
  'unravel': 'nysta upp',
  'untie': 'knyta upp',
  'unveil': 'avtäcka',
  'update': 'uppdatera',
  'upgrade': 'uppgradera',
  'uphold': 'upprätthålla',
  'uplift': 'lyfta',
  'upload': 'ladda upp',
  'urge': 'uppmana',
  'vacuum': 'dammsuga',
  'validate': 'validera',
  'value': 'värdesätta',
  'vanish': 'försvinna',
  'vary': 'variera',
  'venture': 'våga sig',
  'vibe': '',
  'vie': 'tävla',
  'view': 'betrakta',
  'visit': 'besöka',
  'voice': 'uttrycka',
  'void': 'ogiltigförklara',
  'vomit': 'kräkas',
  'vote': 'rösta',
  'vow': 'lova',
  'wait': 'vänta',
  'waive': 'avstå från',
  'wake': 'vakna',
  'walk': 'promenera',
  'wander': 'irra',
  'want': 'vilja',
  'war': 'kriga',
  'warehouse': 'magasinera',
  'warn': 'varna',
  'warrant': 'berättiga',
  'wash': 'tvätta',
  'waste': 'slösa',
  'watch': 'titta på',
  'wave': 'vinka',
  'wax': 'vaxa',
  'wear': 'ha på sig',
  'weather': 'rida ut',
  'weave': 'väva',
  'wed': 'viga',
  'weed': 'rensa',
  'weep': 'gråta',
  'welcome': 'välkomna',
  'wheel': 'rulla',
  'whip': 'piska',
  'whisk': 'vispa',
  'whisper': 'viska',
  'whistle': 'vissla',
  'wick': '',
  'widen': 'vidga',
  'wield': 'svinga',
  'win': 'vinna',
  'wind': 'slingra',
  'wing': 'improvisera',
  'wipe': 'torka',
  'wire': 'koppla',
  'wish': 'önska',
  'withdraw': 'dra tillbaka',
  'wither': 'vissna',
  'wonder': 'undra',
  'work': 'arbeta',
  'workshop': 'workshoppa',
  'worry': 'oroa sig',
  'worsen': 'förvärra',
  'worship': 'dyrka',
  'worth': '',
  'wound': 'såra',
  'wrap': 'slå in',
  'wreak': 'ställa till med',
  'wreck': 'förstöra',
  'wrestle': 'brottas',
  'wring': 'vrida ur',
  'wrinkle': 'skrynkla',
  'write': 'skriva',
  'yawn': 'gäspa',
  'yell': 'skrika',
  'yield': 'avkasta',
  'zip': 'zippa',
  'zone': '',
  'zoom': 'zooma',
}
