export default {
  'a priori': '',
  'aberrant': 'potofu',
  'abject': 'duni',
  'ablaze': 'ya kuwaka',
  'able': 'mwenye uwezo',
  'aboard': 'ndani',
  'above': 'ya juu',
  'abreast': 'sambamba',
  'abrupt': 'ya ghafla',
  'absent': 'asiyekuwepo',
  'absolute': 'kamili',
  'abstract': 'dhahania',
  'abstruse': 'gumu kueleweka',
  'absurd': 'ya kipuuzi',
  'abundant': 'tele',
  'accurate': 'sahihi',
  'acquiescent': 'nyenyekevu',
  'actual': 'halisi',
  'acute': 'kali',
  'ad hoc': 'ya dharura',
  'ad infinitum': 'bila mwisho',
  'adamant': 'shupavu',
  'adept': 'stadi',
  'adequate': 'ya kutosha',
  'adverse': 'hasi',
  'affectionate': 'mwenye upendo',
  'affluent': 'tajiri',
  'afraid': 'mwenye hofu',
  'against': 'dhidi ya',
  'aggressive': 'kali',
  'agile': 'epesi',
  'agreeable': 'ya kupendeza',
  'ahead': 'mbele',
  'alcoholic': 'ya kileo',
  'alight': 'ya kuwaka',
  'alike': 'ya kufanana',
  'alive': 'hai',
  'alkaline': 'ya alkali',
  'all': 'yote',
  'alone': 'peke yake',
  'aloof': 'ya kujitenga',
  'alright': 'sawa',
  'alternate': 'mbadala',
  'ample': 'tele',
  'angry': 'mwenye hasira',
  'antiquated': 'ya kizamani',
  'antique': 'ya kale',
  'antsy': 'asiyetulia',
  'appalled': 'aliyeshtuka',
  'appalling': 'ya kutisha',
  'apparent': 'dhahiri',
  'appetizing': 'ya kuamsha hamu',
  'appropriate': 'ya kufaa',
  'approximate': 'ya kukadiria',
  'apt': 'mwafaka',
  'arbitrary': 'holela',
  'archival': 'ya kumbukumbu',
  'arrogant': 'mwenye kiburi',
  'articulate': 'fasaha',
  'artificial': 'bandia',
  'artsy': 'ya kisanaa',
  'ashen': 'kijivu',
  'asleep': 'aliyelala',
  'astute': 'erevu',
  'attractive': 'ya kuvutia',
  'auditory': 'ya kusikia',
  'austere': 'ya kujinyima',
  'authentic': 'halisi',
  'autoimmune': '',
  'avant garde': 'ya kimapinduzi',
  'average': 'wastani',
  'awake': 'macho',
  'aware': 'mwenye ufahamu',
  'awesome': 'ya ajabu',
  'awkward': 'ya aibu',
  'backwards': 'ya kinyume',
  'bad': 'baya',
  'bald': 'mwenye upara',
  'bankrupt': 'muflisi',
  'bare': 'tupu',
  'barren': 'tasa',
  'bawdy': 'chafu',
  'beautiful': 'rembo',
  'behind': 'nyuma',
  'belated': 'ya kuchelewa',
  'beloved': 'pendwa',
  'below': 'chini',
  'beneath': 'chini ya',
  'beneficial': 'ya manufaa',
  'benign': 'pole',
  'bent': 'iliyopinda',
  'beside': 'kando ya',
  'bestselling': 'inayouzika zaidi',
  'beyond': 'zaidi ya',
  'big': 'kubwa',
  'bigtime': 'kubwa',
  'bipartisan': 'ya vyama viwili',
  'bitter': 'chungu',
  'bizarre': 'ya kushangaza',
  'black': 'eusi',
  'bland': 'chapwa',
  'blind': 'kipofu',
  'blithe': 'changamfu',
  'blond': '',
  'bloody': 'ya damu',
  'blue': 'buluu',
  'blunt': 'butu',
  'bogus': 'bandia',
  'bold': 'jasiri',
  'boldface': 'ya herufi nzito',
  'bona fide': 'halisi',
  'bonafide': 'halisi',
  'bouncy': 'ya kudunda',
  'brand new': 'mpya kabisa',
  'brash': 'mwenye kiburi',
  'brave': 'jasiri',
  'breathtaking': 'ya kustaajabisha',
  'bright': 'angavu',
  'brilliant': 'mahiri',
  'brisk': 'ya haraka',
  'broad': 'pana',
  'bronze': 'ya shaba',
  'brown': 'kahawia',
  'buck naked': 'uchi wa mnyama',
  'buff': 'mwenye misuli',
  'burly': 'kakamavu',
  'busy': 'mwenye shughuli',
  'cagey': 'erevu',
  'calm': 'tulivu',
  'cardiac': 'ya moyo',
  'careful': 'makini',
  'celebate': 'ya useja',
  'certain': 'ya hakika',
  'cheap': 'rahisi',
  'cheery': 'changamfu',
  'cheesy': 'ya kishamba',
  'chewy': 'ya kutafuna',
  'chilly': 'ya baridi',
  'chintzy': 'duni',
  'circumspect': 'angalifu',
  'civil': 'ya kiraia',
  'clean': 'safi',
  'clear': 'wazi',
  'clever': 'janja',
  'clockwise': 'mwendo wa saa',
  'close': 'karibu',
  'cloudy': 'ya mawingu',
  'coarse': 'ya kuparuza',
  'coercive': 'ya kulazimisha',
  'cogent': 'ya kushawishi',
  'cognizant': 'mwenye ufahamu',
  'cold': 'baridi',
  'colonial': 'ya kikoloni',
  'colossal': 'kubwa mno',
  'comatose': 'aliyepoteza fahamu',
  'commensurate': 'linganifu',
  'common': 'ya kawaida',
  'compassionate': 'mwenye huruma',
  'complete': 'kamili',
  'compulsory': 'ya lazima',
  'concave': 'bonyeo',
  'conceited': 'mwenye majivuno',
  'concise': 'fupi',
  'condescending': 'ya kudharau',
  'conducive': 'wezeshi',
  'congruent': 'linganifu',
  'conjoint': 'ya pamoja',
  'conjugal': 'ya ndoa',
  'conjugate': 'ya kuunganishwa',
  'consequent': 'ya kufuatia',
  'constant': 'ya kudumu',
  'consummate': 'kamili',
  'contradictory': 'ya kupingana',
  'contrary': 'kinyume',
  'contrite': 'mwenye majuto',
  'cool': 'poa',
  'corporate': 'ya kampuni',
  'correct': 'sahihi',
  'corrupt': 'fisadi',
  'costly': 'ghali',
  'counterclockwise': 'kinyume cha saa',
  'counterfeit': 'bandia',
  'covert': 'ya siri',
  'cowardly': 'mwoga',
  'coy': 'mwenye haya',
  'cozy': 'ya starehe',
  'crafty': 'janja',
  'craven': 'mwoga',
  'crazed': 'mwenye wazimu',
  'creepy': 'ya kutisha',
  'crisp': 'kavu',
  'crucial': 'muhimu sana',
  'cruel': 'katili',
  'crystal clear': 'wazi kabisa',
  'crystalline': 'ya fuwele',
  'cuddly': 'ya kukumbatika',
  'curly': 'ya kujikunja',
  'curmudgeonly': 'korofi',
  'customary': 'ya kimila',
  'cute': 'ya kupendeza',
  'cutesy': 'ya kujidai',
  'daily': 'ya kila siku',
  'damp': 'chepechepe',
  'dangerous': 'hatari',
  'dapper': 'nadhifu',
  'dark': 'ya giza',
  'de facto': 'halisi',
  'dead': 'mfu',
  'deadly': 'ya kuua',
  'deadpan': 'bila hisia',
  'deaf': 'kiziwi',
  'dear': 'pendwa',
  'deceased': 'marehemu',
  'deep': 'ya kina',
  'defiant': 'kaidi',
  'definite': 'ya uhakika',
  'defuse': 'ya kutawanyika',
  'degenerate': 'potofu',
  'deliberate': 'ya makusudi',
  'delicate': 'ororo',
  'delightful': 'ya kufurahisha',
  'demure': 'mwenye haya',
  'dense': 'zito',
  'dependent': 'tegemezi',
  'derelict': 'iliyotelekezwa',
  'desperate': 'ya kukata tamaa',
  'despondent': 'aliyekata tamaa',
  'destitute': 'fukara',
  'desultory': 'holela',
  'devoid': 'tupu',
  'devout': 'mcha Mungu',
  'didactic': 'ya kufundisha',
  'difficult': 'gumu',
  'diffuse': 'ya kutawanyika',
  'dim': 'hafifu',
  'dire': 'baya sana',
  'direct': 'ya moja kwa moja',
  'dirty': 'chafu',
  'discreet': 'angalifu',
  'discrete': 'ya kutengana',
  'diseased': 'yenye ugonjwa',
  'disjoint': 'ya kutengana',
  'disparate': 'tofauti kabisa',
  'distant': 'ya mbali',
  'distinct': 'bainifu',
  'divergent': 'ya kutofautiana',
  'diverse': 'anuwai',
  'divine': 'ya kimungu',
  'dizzy': 'mwenye kizunguzungu',
  'docile': 'tiifu',
  'dominant': 'tawala',
  'done': 'iliyokwisha',
  'dormant': 'iliyolala',
  'doting': 'ya kudekeza',
  'double': 'maradufu',
  'doubtful': 'ya shaka',
  'dreary': 'ya kuchosha',
  'drowsy': 'ya kusinzia',
  'drunk': 'mlevi',
  'dry': 'kavu',
  'due': 'inayodaiwa',
  'dull': 'ya kuchosha',
  'dumb': 'jinga',
  'eager': 'mwenye hamu',
  'early': 'mapema',
  'earthly': 'ya kidunia',
  'east': 'mashariki',
  'eastern': 'ya mashariki',
  'easy': 'rahisi',
  'easygoing': 'tulivu',
  'eerie': 'ya kutisha',
  'efficient': 'ya ufanisi',
  'elaborate': 'ya kina',
  'elderly': 'mzee',
  'elegant': 'maridadi',
  'elicit': 'haramu',
  'eloquent': 'fasaha',
  'emergent': 'chipukizi',
  'eminent': 'mashuhuri',
  'empty': 'tupu',
  'en route': 'njiani',
  'en suite': 'ya ndani',
  'enamored': 'aliyevutiwa',
  'enough': 'ya kutosha',
  'entire': 'zima',
  'equal': 'sawa',
  'erect': 'wima',
  'erstwhile': 'ya zamani',
  'essential': 'muhimu',
  'ethereal': 'ya kiroho',
  'everyday': 'ya kila siku',
  'evil': 'ovu',
  'exact': 'kamili',
  'exempt': 'ya msamaha',
  'expedient': 'ya kufaa',
  'explicit': 'wazi',
  'express': 'ya haraka',
  'exquisite': 'zuri kabisa',
  'extra': 'ya ziada',
  'extravagant': 'ya anasa',
  'extreme': 'ya kupindukia',
  'exuberant': 'changamfu',
  'exultant': 'mwenye shangwe',
  'fabled': 'ya hadithi',
  'faint': 'hafifu',
  'fake': 'bandia',
  'false': 'ya uongo',
  'famed': 'maarufu',
  'familiar': 'ya kuzoeleka',
  'fancy': 'maridadi',
  'far off': 'mbali sana',
  'far reaching': 'pana',
  'far': 'mbali',
  'fast paced': 'ya kasi',
  'fast': 'ya haraka',
  'faulty': 'bovu',
  'faux': 'bandia',
  'fed up': 'aliyechoshwa',
  'feeble': 'dhaifu',
  'feminine': 'ya kike',
  'fertile': 'yenye rutuba',
  'fervent': 'ya shauku',
  'fierce': 'kali',
  'fiery': 'ya moto',
  'final': 'ya mwisho',
  'financial': 'ya kifedha',
  'finite': 'yenye kikomo',
  'firm': 'imara',
  'flagrant': 'ya waziwazi',
  'flat': 'tambarare',
  'flirty': 'ya kutongoza',
  'flowery': 'ya maua',
  'fluent': 'fasaha',
  'fluorescent': 'ya kung\'aa',
  'foamy': 'ya povu',
  'folksy': 'ya kienyeji',
  'fond': 'mwenye kupenda',
  'foolish': 'pumbavu',
  'for keeps': 'ya kudumu',
  'foregoing': 'iliyotangulia',
  'foreign': 'ya kigeni',
  'foreseeable': 'inayotabirika',
  'forgetful': 'sahaulifu',
  'formal': 'rasmi',
  'former': 'ya zamani',
  'fortunate': 'mwenye bahati',
  'forward': 'ya mbele',
  'foul': 'chafu',
  'fragile': 'dhaifu',
  'fragrant': 'yenye harufu nzuri',
  'frail': 'dhaifu',
  'frantic': 'ya kuhangaika',
  'free': 'huru',
  'frequent': 'ya mara kwa mara',
  'fresh': 'bichi',
  'fretful': 'mwenye wasiwasi',
  'friendly': 'ya kirafiki',
  'frilly': 'ya mapambo',
  'fringe': 'ya pembezoni',
  'frozen': 'iliyoganda',
  'frugal': 'ya kubana matumizi',
  'full': 'iliyojaa',
  'fun': 'ya kufurahisha',
  'funny': 'ya kuchekesha',
  'furry': 'yenye manyoya',
  'gainful': 'yenye kipato',
  'gauche': 'ya kishamba',
  'gaudy': 'ya kishaufu',
  'gay': 'ya jinsia moja',
  'generic': 'ya jumla',
  'gentle': 'pole',
  'genuine': 'halisi',
  'ghastly': 'ya kutisha',
  'ghostly': 'ya mizimu',
  'giant': 'kubwa mno',
  'giddy': 'mwenye kizunguzungu',
  'gigantic': 'kubwa mno',
  'glad': 'mwenye furaha',
  'glib': 'mwepesi wa kuongea',
  'global': 'ya dunia nzima',
  'gloomy': 'ya huzuni',
  'golden': 'ya dhahabu',
  'good': 'zuri',
  'goofy': 'ya kuchekesha',
  'graceful': 'mwenye madaha',
  'grand': 'kuu',
  'grateful': 'mwenye shukrani',
  'gratis': 'bure',
  'gray': 'kijivu',
  'greasy': 'ya mafuta',
  'great': 'kuu',
  'greedy': 'lafi',
  'green': 'kijani',
  'grey': 'kijivu',
  'grim': 'ya huzuni',
  'grisly': 'ya kutisha',
  'grizzled': 'mwenye mvi',
  'groovy': 'poa',
  'gross': 'ya kuchukiza',
  'gruesome': 'ya kutisha',
  'guilty': 'mwenye hatia',
  'gung ho': 'mwenye ari',
  'hairy': 'mwenye nywele nyingi',
  'hallowed': 'takatifu',
  'handsome': 'tanashati',
  'handsy': 'ya kupapasa',
  'handy': 'ya kufaa',
  'happy': 'mwenye furaha',
  'hard up': 'mwenye shida',
  'hard': 'gumu',
  'hardcore': 'ya kupindukia',
  'hardworking': 'mwenye bidii',
  'hardy': 'stahimilivu',
  'harsh': 'kali',
  'hateful': 'ya chuki',
  'heady': 'ya kulevya',
  'hearty': 'kunjufu',
  'heavenly': 'ya mbinguni',
  'heavy': 'zito',
  'hefty': 'zito',
  'hellish': 'ya jehanamu',
  'helpful': 'ya msaada',
  'hesitant': 'ya kusita',
  'high': 'ya juu',
  'highfalutin': 'ya majivuno',
  'hilly': 'ya vilima',
  'hispanic': 'ya kihispania',
  'hoary': 'ya mvi',
  'hollow': 'yenye mvungu',
  'home made': 'ya nyumbani',
  'homely': 'ya kawaida',
  'homesick': 'mwenye hamu ya nyumbani',
  'honest': 'aminifu',
  'honorary': 'ya heshima',
  'horrific': 'ya kutisha',
  'hostile': 'ya uadui',
  'hot': 'ya moto',
  'hourly': 'ya kila saa',
  'huge': 'kubwa sana',
  'humane': 'ya kibinadamu',
  'humble': 'nyenyekevu',
  'humid': 'ya unyevunyevu',
  'hungry': 'mwenye njaa',
  'ice cold': 'baridi kali',
  'icy': 'ya barafu',
  'idle': 'goigoi',
  'ignorant': 'jinga',
  'ill': 'mgonjwa',
  'illegal': 'haramu',
  'illegitimate': 'haramu',
  'illicit': 'haramu',
  'illiterate': 'asiyejua kusoma',
  'immature': 'changa',
  'immediate': 'ya papo hapo',
  'immense': 'kubwa mno',
  'imminent': 'inayokaribia',
  'impartial': 'bila upendeleo',
  'impending': 'inayokaribia',
  'imperfect': 'pungufu',
  'implicit': 'isiyotamkwa',
  'impolite': 'asiye na adabu',
  'important': 'muhimu',
  'improper': 'isiyofaa',
  'in front': 'mbele',
  'in situ': 'mahali pake',
  'in vitro': 'ya maabara',
  'inaccurate': 'isiyo sahihi',
  'inadequate': 'isiyotosha',
  'inane': 'ya kipuuzi',
  'inappropriate': 'isiyofaa',
  'incomplete': 'isiyokamilika',
  'inconsiderate': 'asiyejali',
  'incorrect': 'isiyo sahihi',
  'indefinite': 'isiyo na kikomo',
  'independent': 'huru',
  'indeterminate': 'isiyobainika',
  'indie': 'huru',
  'indirect': 'isiyo ya moja kwa moja',
  'indoor': 'ya ndani',
  'indulgent': 'ya kudekeza',
  'inept': 'asiye na ujuzi',
  'inert': 'ajizi',
  'inferior': 'duni',
  'infinite': 'isiyo na mwisho',
  'influential': 'yenye ushawishi',
  'infrared': 'ya infraredi',
  'infrequent': 'ya mara chache',
  'ingrown': 'iliyokua ndani',
  'inhibitory': 'ya kuzuia',
  'initial': 'ya awali',
  'innate': 'ya asili',
  'inner': 'ya ndani',
  'inordinate': 'ya kupita kiasi',
  'insane': 'mwenye wazimu',
  'insecure': 'asiyejiamini',
  'inside': 'ya ndani',
  'insignificant': 'isiyo na umuhimu',
  'insoluble': 'isiyoyeyuka',
  'insolvent': 'muflisi',
  'insubordinate': 'asiyetii',
  'intact': 'zima',
  'intellegent': 'mwenye akili',
  'intense': 'kali',
  'interdependent': 'ya kutegemeana',
  'intermediate': 'ya kati',
  'intimate': 'ya karibu',
  'invaluable': 'ya thamani kubwa',
  'ipso facto': '',
  'irate': 'mwenye hasira kali',
  'irrelevant': 'isiyohusika',
  'jaded': 'aliyechoshwa',
  'jittery': 'mwenye wasiwasi',
  'jolly': 'changamfu',
  'juicy': 'yenye maji mengi',
  'junior': 'mdogo',
  'kaput': 'bovu',
  'keen': 'mwenye hamu',
  'kind': 'karimu',
  'kindly': 'karimu',
  'knowing': 'ya kujua',
  'lame': 'kiwete',
  'languid': 'legevu',
  'lapsed': 'iliyoisha muda',
  'large': 'kubwa',
  'last': 'ya mwisho',
  'late': 'ya kuchelewa',
  'lately': 'hivi karibuni',
  'lay': 'mlei',
  'lean': 'embamba',
  'leery': 'mwenye shaka',
  'left wing': 'ya mrengo wa kushoto',
  'legal': 'halali',
  'legendary': 'ya hadithi',
  'legitimate': 'halali',
  'lesser': 'dogo zaidi',
  'lethal': 'ya kuua',
  'lewd': 'chafu',
  'lighthearted': 'kunjufu',
  'lightweight': 'epesi',
  'likely': 'yamkini',
  'lil': 'dogo',
  'limp': 'legevu',
  'literal': 'halisi',
  'literary': 'ya kifasihi',
  'literate': 'anayejua kusoma',
  'little': 'dogo',
  'live': 'hai',
  'lively': 'changamfu',
  'lofty': 'tukufu',
  'lonely': 'mpweke',
  'long': 'refu',
  'longstanding': 'ya muda mrefu',
  'longterm': 'ya muda mrefu',
  'longtime': 'ya muda mrefu',
  'loose': 'legevu',
  'loud': 'ya sauti kubwa',
  'lousy': 'duni',
  'loutish': 'ya kijeuri',
  'lovely': 'ya kupendeza',
  'low': 'ya chini',
  'lower': 'ya chini zaidi',
  'lowly': 'nyonge',
  'loyal': 'aminifu',
  'lucky': 'mwenye bahati',
  'lumbering': 'ya mwendo mzito',
  'macabre': 'ya kutisha',
  'macho': 'ya kiume',
  'mad': 'mwenye hasira',
  'magenta': '',
  'main': 'kuu',
  'mainstream': 'ya kawaida',
  'major': 'kuu',
  'makeshift': 'ya muda',
  'mammalian': 'ya mamalia',
  'mammoth': 'kubwa mno',
  'mandatory': 'ya lazima',
  'many': 'nyingi',
  'maritime': 'ya baharini',
  'masculine': 'ya kiume',
  'mature': 'komavu',
  'maverick': 'ya kujitegemea',
  'meager': 'haba',
  'mean': 'katili',
  'measly': 'haba',
  'meaty': 'ya nyama',
  'mediocre': 'ya wastani',
  'meek': 'pole',
  'mega': 'kubwa sana',
  'mellow': 'tulivu',
  'menacing': 'ya vitisho',
  'mere': 'tupu',
  'merry': 'changamfu',
  'metropolitan': 'ya jiji',
  'middle aged': 'ya makamo',
  'mild': 'pole',
  'mindblowing': 'ya kustaajabisha',
  'mini': 'dogo',
  'minor': 'dogo',
  'moderate': 'ya wastani',
  'modern': 'ya kisasa',
  'modest': 'mwenye kiasi',
  'moist': 'ya unyevu',
  'moldy': 'ya ukungu',
  'monochrome': 'ya rangi moja',
  'monthly': 'ya kila mwezi',
  'moody': 'korofi',
  'moot': 'ya mjadala',
  'morbid': 'ya kifo',
  'most': 'nyingi zaidi',
  'muddy': 'ya matope',
  'multifaceted': 'ya pande nyingi',
  'multiple': 'nyingi',
  'mundane': 'ya kawaida',
  'mute': 'bubu',
  'naive': 'zuzu',
  'naked': 'uchi',
  'narrow': 'embamba',
  'nausiating': 'ya kichefuchefu',
  'naval': 'ya wanamaji',
  'near': 'karibu',
  'nearby': 'ya karibu',
  'neat': 'nadhifu',
  'necessary': 'ya lazima',
  'neighborly': 'ya kijirani',
  'nerdy': 'ya kisomi',
  'new': 'mpya',
  'newlywed': 'maharusi',
  'next': 'ijayo',
  'nibbly': 'ya kutafuna',
  'nice': 'zuri',
  'nightly': 'ya kila usiku',
  'nimble': 'epesi',
  'no more': 'hakuna tena',
  'noble': 'tukufu',
  'noisy': 'ya kelele',
  'nonchalant': 'ya kutojali',
  'nondescript': 'ya kawaida',
  'nonprofit': 'isiyo ya faida',
  'nonstop': 'bila kusimama',
  'normal': 'ya kawaida',
  'north': 'kaskazini',
  'northeast': 'kaskazini mashariki',
  'northern': 'ya kaskazini',
  'northwest': 'kaskazini magharibi',
  'nosy': 'ya udaku',
  'notable': 'mashuhuri',
  'nuanced': 'ya kina',
  'nude': 'uchi',
  'numb': 'ya ganzi',
  'obediant': 'tiifu',
  'obedient': 'tiifu',
  'obese': 'nene kupita kiasi',
  'obligated': 'mwenye wajibu',
  'obscene': 'ya matusi',
  'obscure': 'isiyojulikana',
  'observant': 'makini',
  'obsolete': 'iliyopitwa na wakati',
  'odd': 'ya ajabu',
  'off guard': 'bila tahadhari',
  'offbeat': 'isiyo ya kawaida',
  'offhand': 'bila maandalizi',
  'offline': 'nje ya mtandao',
  'oily': 'ya mafuta',
  'ok': 'sawa',
  'okay': 'sawa',
  'old fashioned': 'ya kizamani',
  'old school': 'ya kizamani',
  'old': 'ya zamani',
  'on board': 'ndani',
  'onboard': 'ndani',
  'one on one': 'ana kwa ana',
  'ongoing': 'inayoendelea',
  'online': 'mtandaoni',
  'open': 'wazi',
  'orange': 'ya machungwa',
  'orderly': 'ya mpangilio',
  'organic': 'hai',
  'orotund': 'ya majivuno',
  'other': 'nyingine',
  'outdoor': 'ya nje',
  'outer': 'ya nje',
  'outside': 'ya nje',
  'over': 'iliyokwisha',
  'overall': 'ya jumla',
  'overboard': 'nje ya chombo',
  'overdue': 'iliyochelewa',
  'overhand': 'ya kutoka juu',
  'overhead': 'ya juu',
  'overnight': 'ya usiku mmoja',
  'overseas': 'ya ng\'ambo',
  'overt': 'ya waziwazi',
  'overweight': 'nene',
  'overwrought': 'mwenye msongo',
  'own': 'mwenyewe',
  'painful': 'ya maumivu',
  'pale': 'ya kupauka',
  'paranoid': 'mwenye wasiwasi',
  'part time': 'ya muda',
  'partial': 'ya sehemu',
  'partisan': 'ya kichama',
  'passionate': 'ya shauku',
  'peaceful': 'ya amani',
  'pent up': 'iliyozuiliwa',
  'perfect': 'kamilifu',
  'permanent': 'ya kudumu',
  'pert': 'changamfu',
  'pertinent': 'husika',
  'perverse': 'potofu',
  'petite': 'dogo',
  'phony': 'bandia',
  'picayune': 'duni',
  'pink': 'ya waridi',
  'placid': 'tulivu',
  'plaid': 'ya miraba',
  'plain': 'ya kawaida',
  'pleasant': 'ya kupendeza',
  'pointy': 'iliyochongoka',
  'polite': 'mwenye adabu',
  'poor': 'maskini',
  'populist': 'ya umma',
  'precise': 'sahihi',
  'preexisting': 'iliyokuwepo kabla',
  'pregnant': 'mjamzito',
  'premature': 'ya kabla ya wakati',
  'prepaid': 'ya kulipwa kabla',
  'present': 'iliyopo',
  'pricey': 'ghali',
  'prickly': 'ya miiba',
  'prima': 'ya kwanza',
  'primary': 'ya msingi',
  'prime': 'bora',
  'prior': 'ya awali',
  'pristine': 'safi kabisa',
  'private': 'ya binafsi',
  'probable': 'yamkini',
  'profane': 'ya kufuru',
  'profound': 'ya kina',
  'profuse': 'tele',
  'prominent': 'mashuhuri',
  'prompt': 'ya haraka',
  'proper': 'stahiki',
  'proportionate': 'linganifu',
  'proud': 'mwenye fahari',
  'proven': 'iliyothibitishwa',
  'proximate': 'ya karibu',
  'public': 'ya umma',
  'punjabi': 'ya kipunjabi',
  'puny': 'nyonge',
  'pure': 'safi',
  'purple': 'zambarau',
  'puzzled': 'aliyechanganyikiwa',
  'quack': 'bandia',
  'quaint': 'ya kizamani',
  'quarterly': 'ya kila robo mwaka',
  'quick': 'ya haraka',
  'quiet': 'kimya',
  'rabid': 'ya kichaa',
  'racial': 'ya rangi',
  'ragged': 'kuukuu',
  'rainy': 'ya mvua',
  'rampant': 'iliyokithiri',
  'random': 'holela',
  'rapid': 'ya kasi',
  'rare': 'adimu',
  'raw': 'bichi',
  'ready': 'tayari',
  'real': 'halisi',
  'recalcitrant': 'kaidi',
  'recent': 'ya hivi karibuni',
  'recondite': 'gumu kueleweka',
  'red': 'ekundu',
  'redundant': 'isiyohitajika',
  'relevant': 'husika',
  'reluctant': 'ya kusita',
  'remote': 'ya mbali',
  'renowned': 'maarufu',
  'replicate': 'ya nakala',
  'reprobate': 'potofu',
  'resistant': 'sugu',
  'resolute': 'shupavu',
  'resonant': 'ya mwangwi',
  'retarded': 'taahira',
  'rheumatoid': 'ya baridi yabisi',
  'rich': 'tajiri',
  'right wing': 'ya mrengo wa kulia',
  'right': 'sahihi',
  'rightful': 'halali',
  'ripe': 'bivu',
  'ritzy': 'ya kifahari',
  'rival': 'pinzani',
  'robust': 'imara',
  'romantic': 'ya kimapenzi',
  'roomy': 'yenye nafasi',
  'rosy': 'ya waridi',
  'rotten': 'bovu',
  'rough': 'ya kuparuza',
  'round': 'ya mviringo',
  'royal': 'ya kifalme',
  'rude': 'fidhuli',
  'sacred': 'takatifu',
  'sad': 'mwenye huzuni',
  'safe': 'salama',
  'saintly': 'takatifu',
  'salty': 'ya chumvi',
  'same': 'ile ile',
  'satisfactory': 'ya kuridhisha',
  'savvy': 'erevu',
  'scanty': 'haba',
  'scarce': 'adimu',
  'scarlet': 'ekundu',
  'scary': 'ya kutisha',
  'scathing': 'kali',
  'scholarly': 'ya kisomi',
  'scientific': 'ya kisayansi',
  'secondary': 'ya sekondari',
  'secure': 'salama',
  'sedate': 'tulivu',
  'seemly': 'ya adabu',
  'select': 'teule',
  'self sufficient': 'ya kujitosheleza',
  'selfish': 'choyo',
  'sensory': 'ya hisia',
  'separate': 'tofauti',
  'serene': 'tulivu',
  'severe': 'kali',
  'sexy': 'ya kuvutia',
  'shady': 'ya kutia shaka',
  'shallow': 'ya kina kifupi',
  'shameful': 'ya aibu',
  'sharp': 'kali',
  'sheer': 'tupu',
  'shiny': 'ya kung\'aa',
  'short': 'fupi',
  'shrill': 'ya sauti kali',
  'shy': 'mwenye haya',
  'sick': 'mgonjwa',
  'sickly': 'dhaifu',
  'significant': 'muhimu',
  'silly': 'ya kijinga',
  'simple': 'rahisi',
  'sincere': 'ya dhati',
  'single': 'moja',
  'sinister': 'ovu',
  'skilled': 'stadi',
  'skin deep': 'ya juu juu',
  'skinny': 'embamba',
  'sleek': 'laini',
  'sleepy': 'mwenye usingizi',
  'slender': 'embamba',
  'slick': 'laini',
  'slight': 'dogo',
  'slim': 'embamba',
  'slimy': 'ya ute',
  'slippery': 'ya kuteleza',
  'slipshod': 'zembe',
  'slow': 'ya polepole',
  'sly': 'janja',
  'small': 'dogo',
  'smart': 'mwenye akili',
  'smelly': 'ya kunuka',
  'smooth': 'laini',
  'smug': 'mwenye majivuno',
  'snobbish': 'mwenye dharau',
  'so called': 'inayoitwa',
  'social': 'ya kijamii',
  'soft': 'laini',
  'sold out': 'iliyoisha',
  'solemn': 'ya kicho',
  'solid': 'imara',
  'soluble': 'ya kuyeyuka',
  'somber': 'ya huzuni',
  'soon': 'hivi karibuni',
  'sophisticated': 'ya hali ya juu',
  'sordid': 'chafu',
  'sore': 'ya maumivu',
  'sorry': 'mwenye majuto',
  'soundproof': 'isiyopitisha sauti',
  'sour': 'chachu',
  'south': 'kusini',
  'southeast': 'kusini mashariki',
  'southern': 'ya kusini',
  'southwest': 'kusini magharibi',
  'soviet': 'ya kisovieti',
  'spare': 'ya akiba',
  'sparkly': 'ya kumetameta',
  'sparse': 'haba',
  'special': 'maalumu',
  'specific': 'mahususi',
  'speedy': 'ya kasi',
  'spicy': 'ya viungo',
  'spirited': 'mwenye ari',
  'splendid': 'zuri kabisa',
  'spot on': 'sahihi kabisa',
  'sprightly': 'changamfu',
  'spry': 'epesi',
  'squeamish': 'mwenye kinyaa',
  'stale': 'iliyochacha',
  'stalwart': 'shupavu',
  'stark': 'tupu',
  'stately': 'ya kifahari',
  'statutory': 'ya kisheria',
  'steadfast': 'thabiti',
  'steady': 'thabiti',
  'steep': 'ya mwinuko mkali',
  'sterile': 'tasa',
  'stern': 'kali',
  'stiff': 'gumu',
  'still': 'tulivu',
  'stout': 'nene',
  'straight forward': 'ya moja kwa moja',
  'straight': 'nyoofu',
  'straightforward': 'ya moja kwa moja',
  'strange': 'geni',
  'stray': 'aliyepotea',
  'strict': 'kali',
  'stringent': 'kali',
  'strong': 'yenye nguvu',
  'strung out': 'mwenye msongo',
  'stubborn': 'kaidi',
  'stupid': 'jinga',
  'sturdy': 'imara',
  'stylish': 'maridadi',
  'subdued': 'tulivu',
  'sublime': 'tukufu',
  'subpar': 'duni',
  'subsequent': 'inayofuata',
  'substandard': 'duni',
  'substantial': 'kubwa',
  'subtle': 'isiyo dhahiri',
  'suburban': 'ya viungani',
  'succinct': 'fupi',
  'sudden': 'ya ghafla',
  'sui generis': 'ya kipekee',
  'super duper': 'bora kabisa',
  'super': 'bora sana',
  'superb': 'bora kabisa',
  'superficial': 'ya juu juu',
  'supervisory': 'ya usimamizi',
  'supreme': 'kuu kabisa',
  'sure': 'ya hakika',
  'surly': 'korofi',
  'surreal': 'ya ndoto',
  'suspect': 'ya kutia shaka',
  'sweet': 'tamu',
  'swift': 'ya kasi',
  'symbolic': 'ya ishara',
  'talented': 'mwenye kipaji',
  'tall': 'refu',
  'tame': 'ya kufugwa',
  'tart': 'chachu',
  'tasteful': 'ya kupendeza',
  'tawdry': 'duni',
  'teenage': 'ya balehe',
  'temperate': 'ya wastani',
  'temporary': 'ya muda',
  'tender': 'ororo',
  'tense': 'ya wasiwasi',
  'terrific': 'bora sana',
  'tertiary': 'ya tatu',
  'testy': 'korofi',
  'thick': 'nene',
  'thin': 'embamba',
  'thirsty': 'mwenye kiu',
  'thorny': 'ya miiba',
  'thoughtful': 'mwenye kujali',
  'tidy': 'nadhifu',
  'tight': 'ya kubana',
  'timely': 'ya wakati mwafaka',
  'tiny': 'dogo sana',
  'tip top': 'bora kabisa',
  'tired': 'aliyechoka',
  'together': 'pamoja',
  'tolerant': 'vumilivu',
  'top notch': 'bora kabisa',
  'top': 'ya juu kabisa',
  'torpid': 'legevu',
  'total': 'kamili',
  'tough': 'gumu',
  'tranquil': 'tulivu',
  'transparent': 'angavu',
  'trenchant': 'kali',
  'trendy': 'ya mtindo',
  'trite': 'chapwa',
  'true': 'ya kweli',
  'ugly': 'baya',
  'ultimate': 'ya mwisho',
  'ultra': 'ya kupindukia',
  'unabated': 'bila kupungua',
  'unappealing': 'isiyovutia',
  'unassuming': 'nyenyekevu',
  'unattended': 'bila uangalizi',
  'unauthorized': 'bila idhini',
  'unbecoming': 'isiyofaa',
  'unchallenged': 'bila kupingwa',
  'uncharted': 'isiyogunduliwa',
  'unchecked': 'bila kudhibitiwa',
  'uncircumcised': 'asiyetahiriwa',
  'unconvincing': 'isiyoshawishi',
  'undecided': 'asiyeamua',
  'under': 'chini ya',
  'underage': 'chini ya umri',
  'undercover': 'ya siri',
  'underhand': 'ya hila',
  'underlying': 'ya msingi',
  'underneath': 'chini ya',
  'underprivileged': 'asiyejiweza',
  'undersized': 'dogo kuliko kawaida',
  'underwater': 'chini ya maji',
  'underway': 'inayoendelea',
  'underweight': 'ya uzito pungufu',
  'undisclosed': 'isiyotajwa',
  'undisputed': 'isiyopingika',
  'undocumented': 'bila nyaraka',
  'undue': 'isiyostahili',
  'unemployed': 'asiye na ajira',
  'unending': 'isiyo na mwisho',
  'uneven': 'isiyo sawa',
  'unexpected': 'isiyotarajiwa',
  'unexplained': 'isiyoelezwa',
  'unfair': 'isiyo ya haki',
  'unfinished': 'isiyokamilika',
  'unforeseen': 'isiyotarajiwa',
  'unguarded': 'bila ulinzi',
  'unheard': 'isiyosikika',
  'uninsured': 'bila bima',
  'uninterested': 'asiye na hamu',
  'uninterrupted': 'bila kukatizwa',
  'uninvited': 'bila mwaliko',
  'unique': 'ya kipekee',
  'universal': 'ya ulimwengu wote',
  'unknown': 'isiyojulikana',
  'unmarried': 'mseja',
  'unmatched': 'isiyo na kifani',
  'unmet': 'isiyotimizwa',
  'unnamed': 'isiyotajwa jina',
  'unnoticed': 'bila kuonekana',
  'unopposed': 'bila kupingwa',
  'unpaid': 'isiyolipwa',
  'unparalleled': 'isiyo na kifani',
  'unprecedented': 'isiyowahi kutokea',
  'unrecognized': 'isiyotambuliwa',
  'unregulated': 'bila udhibiti',
  'unrelated': 'isiyohusiana',
  'unrelenting': 'isiyokoma',
  'unrequited': 'isiyorudishwa',
  'unreserved': 'bila kificho',
  'unresolved': 'isiyotatuliwa',
  'unruly': 'ya fujo',
  'unseen': 'isiyoonekana',
  'unsettled': 'isiyotulia',
  'unsightly': 'ya kuchukiza',
  'unsold': 'isiyouzwa',
  'unspent': 'isiyotumika',
  'unspoken': 'isiyotamkwa',
  'unsupervised': 'bila usimamizi',
  'unsuspecting': 'asiyeshuku',
  'untapped': 'isiyotumiwa',
  'untested': 'isiyojaribiwa',
  'untold': 'isiyohesabika',
  'untouched': 'isiyoguswa',
  'unused': 'isiyotumika',
  'unwanted': 'isiyotakiwa',
  'unwarranted': 'isiyo na sababu',
  'unwieldy': 'gumu kutumia',
  'up front': 'ya awali',
  'up to date': 'ya sasa',
  'upbeat': 'changamfu',
  'upper': 'ya juu',
  'uppity': 'mwenye kiburi',
  'upscale': 'ya kifahari',
  'upset': 'aliyeudhika',
  'upside down': 'juu chini',
  'uptight': 'mwenye wasiwasi',
  'urban': 'ya mjini',
  'urgent': 'ya dharura',
  'useful': 'ya manufaa',
  'usual': 'ya kawaida',
  'utter': 'tupu',
  'uttermost': 'ya mwisho kabisa',
  'vacant': 'wazi',
  'vagrant': 'ya kuzurura',
  'vague': 'isiyo wazi',
  'vain': 'ya majivuno',
  'valuable': 'ya thamani',
  'vast': 'kubwa sana',
  'vengeful': 'ya kisasi',
  'verdant': 'ya kijani',
  'versatile': 'ya matumizi mengi',
  'vibrant': 'changamfu',
  'vice versa': 'kinyume chake',
  'vigilant': 'macho',
  'vile': 'ovu',
  'volatile': 'tete',
  'vulgar': 'ya matusi',
  'wanton': 'holela',
  'warm': 'vuguvugu',
  'wary': 'angalifu',
  'wasteful': 'ya ubadhirifu',
  'watery': 'ya majimaji',
  'weak': 'dhaifu',
  'weary': 'aliyechoka',
  'weatherproof': 'ya kustahimili hali ya hewa',
  'wee': 'dogo sana',
  'weekly': 'ya kila wiki',
  'weird': 'ya ajabu',
  'well off': 'tajiri',
  'western': 'ya magharibi',
  'wet': 'iliyolowa',
  'whacked out': 'mwenye wazimu',
  'whiny': 'ya kunung\'unika',
  'white': 'eupe',
  'whole': 'zima',
  'wholesale': 'ya jumla',
  'wicked': 'ovu',
  'wide': 'pana',
  'widespread': 'iliyoenea',
  'wild': 'ya porini',
  'wily': 'janja',
  'win win': 'ya kunufaisha wote',
  'windy': 'yenye upepo',
  'wiry': 'embamba na imara',
  'wise': 'mwenye busara',
  'wistful': 'ya kutamani',
  'womanly': 'ya kike',
  'wooden': 'ya mbao',
  'woozy': 'mwenye kizunguzungu',
  'worthwhile': 'yenye faida',
  'wound': 'iliyosokotwa',
  'wounded': 'aliyejeruhiwa',
  'wrong': 'isiyo sahihi',
  'wrought': 'ya kufuliwa',
  'wry': 'ya kejeli',
  'yearly': 'ya kila mwaka',
  'yellow': 'njano',
  'young': 'changa',
  'zany': 'ya kuchekesha',
}
