export default {
  'a lot': 'sana',
  'abroad': 'ng\'ambo',
  'ad nauseam': 'kupita kiasi',
  'again': 'tena',
  'all but': 'karibu',
  'all that': 'kiasi hicho',
  'almost': 'karibu',
  'already': 'tayari',
  'also': 'pia',
  'always': 'daima',
  'anymore': 'tena',
  'anyway': 'hata hivyo',
  'alongside': 'sambamba na',
  'apart': 'mbali',
  'aside': 'kando',
  'as soon': 'mara tu',
  'at best': 'kwa uzuri zaidi',
  'at large': 'kwa ujumla',
  'at least': 'angalau',
  'at most': 'si zaidi ya',
  'at worst': 'kwa ubaya zaidi',
  'away': 'mbali',
  'by far': 'kwa mbali',
  'by now': 'kufikia sasa',
  'de jure': 'kisheria',
  'de trop': 'kupita kiasi',
  'definitely': 'kwa hakika',
  'directly': 'moja kwa moja',
  'en masse': 'kwa wingi',
  'enough': 'vya kutosha',
  'for example': 'kwa mfano',
  'for good': 'kabisa',
  'for sure': 'bila shaka',
  'forever': 'milele',
  'fully': 'kikamilifu',
  'further': 'zaidi',
  'furthermore': 'zaidi ya hayo',
  'hence': 'kwa hiyo',
  'indeed': 'kweli',
  'instead': 'badala yake',
  'just about': 'karibu',
  'just': 'tu',
  'likewise': 'vivyo hivyo',
  'kinda': 'kiasi',
  'maybe': 'labda',
  'meanwhile': 'wakati huo huo',
  'awhile': 'kwa muda',
  'more': 'zaidi',
  'moreover': 'isitoshe',
  'newly': 'hivi karibuni',
  'no longer': 'si tena',
  'not only': 'si tu',
  'not withstanding': 'licha ya hayo',
  'of course': 'bila shaka',
  'often': 'mara nyingi',
  'once again': 'kwa mara nyingine',
  'once more': 'kwa mara nyingine',
  'once': 'mara moja',
  'only': 'tu',
  'par excellence': 'bora kabisa',
  'per se': 'hasa',
  'perhaps': 'huenda',
  'point blank': 'moja kwa moja',
  'quite': 'kabisa',
  'randomly': 'kiholela',
  'rather': 'afadhali',
  'really': 'kweli',
  'so': 'hivyo',
  'somehow': 'kwa namna fulani',
  'sometimes': 'wakati mwingine',
  'somewhat': 'kiasi',
  'sort of': 'kiasi',
  'seldom': 'mara chache',
  'such': 'namna hiyo',
  'then': 'kisha',
  'thus': 'hivyo',
  'too': 'pia',
  'totally': 'kabisa',
  'twice': 'mara mbili',
  'up to': 'hadi',
  'upwards of': 'zaidi ya',
  'tiny bit': 'kidogo sana',
  'very': 'sana',
  'well': 'vizuri',
  'backward': 'nyuma',
  'hella': 'sana',
  'by no means': 'kamwe',
  'altogether': 'kwa jumla',
  'outright': 'kabisa',
  'ultimately': 'hatimaye',
}
