export default {
  'a': '',
  'an': '',
  'another': 'nyingine',
  'any': 'yoyote',
  'both': 'wote wawili',
  'each': 'kila',
  'else': 'kingine',
  'every': 'kila',
  'few': 'chache',
  'least': 'kidogo kabisa',
  'much': 'nyingi',
  'neither': 'wala',
  'own': 'mwenyewe',
  'plenty': 'tele',
  'some': 'baadhi',
  'several': 'kadhaa',
  'that': 'hiyo',
  'the': '',
  'these': 'hizi',
  'this': 'hii',
  'those': 'zile',
  'various': 'mbalimbali',
  'whatever': 'chochote',
  'whichever': 'yoyote',
  'it': 'hiyo',
  'they': 'wao',
  'i': 'mimi',
  'them': 'wao',
  'you': 'wewe',
  'she': 'yeye',
  'me': 'mimi',
  'he': 'yeye',
  'him': 'yeye',
  'us': 'sisi',
  'we': 'sisi',
  'her': 'yake',
  'hers': 'yake',
  'his': 'yake',
  'its': 'yake',
  'mine': 'yangu',
  'my': 'yangu',
  'none': 'hakuna',
  'our': 'yetu',
  'ours': 'yetu',
  'thy': 'yako',
  'their': 'yao',
  'theirs': 'yao',
  'your': 'yako',
  'yours': 'yako',
  'whatsoever': 'chochote',
  'whichsoever': 'yoyote',
  'whoever': 'yeyote',
  'whom': 'nani',
  'whomever': 'yeyote',
  'whomsoever': 'yeyote',
  'whose': 'ya nani',
  'whosesoever': 'ya yeyote',
  'whosoever': 'yeyote',
  'whenever': 'wakati wowote',
  'although': 'ingawa',
  'and': 'na',
  'because': 'kwa sababu',
  'before': 'kabla',
  'but': 'lakini',
  'if': 'kama',
  'how': 'jinsi',
  'nor': 'wala',
  'now': 'sasa',
  'or': 'au',
  'since': 'tangu',
  'though': 'ingawa',
  'while': 'wakati',
  'yet': 'bado',
  'amen': 'amina',
  'argh': 'aah',
  'boo': '',
  'brr': '',
  'bye': 'kwaheri',
  'congratulations': 'hongera',
  'dammit': 'ala',
  'damn': 'ala',
  'damnit': 'ala',
  'dang': 'ala',
  'drat': 'ala',
  'duh': '',
  'eww': 'aka',
  'fuck': '',
  'goodbye': 'kwaheri',
  'gosh': 'lo',
  'haha': 'haha',
  'hello': 'habari',
  'hey': 'hei',
  'hi': 'mambo',
  'holy': 'takatifu',
  'hooray': 'hoyee',
  'huh': 'eh',
  'lol': '',
  'meh': '',
  'mmm': 'mmm',
  'nah': 'hapana',
  'nope': 'hapana',
  'oh': 'oo',
  'oops': '',
  'ouch': 'aii',
  'ow': 'aii',
  'phew': '',
  'phooey': '',
  'please': 'tafadhali',
  'shit': '',
  'tsk': '',
  'ugh': 'aka',
  'uh huh': 'ehe',
  'uh oh': '',
  'whew': '',
  'whoa': 'lo',
  'wtf': '',
  'ya': 'eeh',
  'yay': 'hoyee',
  'yeah': 'eeh',
  'yep': 'ndiyo',
  'yes': 'ndiyo',
  'yikes': 'aisee',
  'yipee': 'hoyee',
  'heck': 'ala',
  'yippee': 'hoyee',
  'yuck': 'aka',
  'yup': 'ndiyo',
  'about': 'kuhusu',
  'across': 'ng\'ambo ya',
  'after': 'baada ya',
  'along': 'kando ya',
  'amid': 'katikati ya',
  'amidst': 'katikati ya',
  'among': 'miongoni mwa',
  'amongst': 'miongoni mwa',
  'apropos': 'kuhusu',
  'around': 'kuzunguka',
  'as': 'kama',
  'at': 'kwenye',
  'atop': 'juu ya',
  'barring': 'isipokuwa',
  'besides': 'mbali na',
  'between': 'kati ya',
  'bout': 'kuhusu',
  'by': 'na',
  'despite': 'licha ya',
  'down': 'chini',
  'during': 'wakati wa',
  'except': 'isipokuwa',
  'for': 'kwa',
  'from': 'kutoka',
  'in': 'katika',
  'into': 'ndani ya',
  'notwithstanding': 'licha ya',
  'of': 'ya',
  'off': '',
  'on': 'juu ya',
  'onto': 'juu ya',
  'out': 'nje',
  'than': 'kuliko',
  'thereby': 'kwa hivyo',
  'through': 'kupitia',
  'throughout': 'kote',
  'thru': 'kupitia',
  'till': 'hadi',
  'towards': 'kuelekea',
  'unlike': 'tofauti na',
  'until': 'hadi',
  'up': 'juu',
  'upon': 'juu ya',
  'versus': 'dhidi ya',
  'via': 'kupitia',
  'whereas': 'ilhali',
  'with': 'na',
  'within': 'ndani ya',
  'without': 'bila',
}
