export default {
  'abandon': 'kutelekeza',
  'abduct': 'kuteka nyara',
  'abet': 'kusaidia',
  'abide': 'kuzingatia',
  'abolish': 'kufuta',
  'abort': 'kutoa mimba',
  'abound': 'kujaa tele',
  'abscond': 'kutoroka',
  'absolve': 'kusamehe',
  'abuse': 'kudhulumu',
  'accent': 'kutilia mkazo',
  'accept': 'kukubali',
  'access': 'kufikia',
  'acclimate': 'kuzoea',
  'accommodate': 'kupokea',
  'accompany': 'kusindikiza',
  'accomplish': 'kutimiza',
  'accord': 'kukubaliana',
  'accost': 'kukabili',
  'account': 'kuhesabu',
  'accrue': 'kuongezeka',
  'accuse': 'kutuhumu',
  'accustom': 'kuzoeza',
  'ace': 'kufaulu kabisa',
  'ache': 'kuuma',
  'achieve': 'kufanikisha',
  'acknowledge': 'kukiri',
  'acquiesce': 'kuridhia',
  'acquire': 'kupata',
  'act': 'kutenda',
  'activate': 'kuwasha',
  'adapt': 'kujirekebisha',
  'address': 'kushughulikia',
  'adjourn': 'kuahirisha',
  'adjust': 'kurekebisha',
  'administer': 'kusimamia',
  'admit': 'kukiri',
  'adopt': 'kuasili',
  'adorn': 'kupamba',
  'adsorb': 'kufyonza',
  'advance': 'kusonga mbele',
  'advocate': 'kutetea',
  'affix': 'kubandika',
  'afford': 'kumudu',
  'age': 'kuzeeka',
  'agree': 'kukubaliana',
  'aid': 'kusaidia',
  'aim': 'kulenga',
  'air': 'kurusha hewani',
  'alarm': 'kutia hofu',
  'align': 'kuoanisha',
  'allege': 'kudai',
  'allot': 'kugawia',
  'allow': 'kuruhusu',
  'allude': 'kudokeza',
  'alter': 'kubadilisha',
  'amalgamate': 'kuunganisha',
  'amaze': 'kushangaza',
  'amuse': 'kufurahisha',
  'analyse': 'kuchambua',
  'anchor': 'kutia nanga',
  'anger': 'kukasirisha',
  'animate': 'kuhuisha',
  'anneal': '',
  'announce': 'kutangaza',
  'annoy': 'kuudhi',
  'annul': 'kubatilisha',
  'answer': 'kujibu',
  'anticipate': 'kutarajia',
  'appeal': 'kukata rufaa',
  'appear': 'kuonekana',
  'appease': 'kutuliza',
  'apply': 'kuomba',
  'appoint': 'kuteua',
  'appraise': 'kuthamini',
  'approach': 'kukaribia',
  'approve': 'kuidhinisha',
  'arch': 'kupinda',
  'archive': 'kuhifadhi',
  'argue': 'kubishana',
  'arise': 'kujitokeza',
  'arm': 'kupa silaha',
  'armour': 'kukinga',
  'arouse': 'kuamsha',
  'arrange': 'kupanga',
  'arrive': 'kufika',
  'ask': 'kuuliza',
  'aspire': 'kutamani',
  'assail': 'kushambulia',
  'assemble': 'kukusanya',
  'assert': 'kusisitiza',
  'assess': 'kutathmini',
  'assign': 'kukabidhi',
  'assist': 'kusaidia',
  'associate': 'kuhusisha',
  'assure': 'kuhakikishia',
  'astonish': 'kushangaza',
  'attach': 'kuambatanisha',
  'attack': 'kushambulia',
  'attain': 'kufikia',
  'attempt': 'kujaribu',
  'attest': 'kushuhudia',
  'attract': 'kuvutia',
  'auction': 'kunadi',
  'augment': 'kuongeza',
  'automate': 'kufanya kiotomatiki',
  'avert': 'kuepusha',
  'avoid': 'kuepuka',
  'await': 'kusubiri',
  'awaken': 'kuamsha',
  'award': 'kutunuku',
  'babysit': 'kuangalia watoto',
  'back': 'kuunga mkono',
  'backfire': 'kugeuka kinyume',
  'baffle': 'kutatanisha',
  'bail': 'kudhamini',
  'balance': 'kusawazisha',
  'ban': 'kupiga marufuku',
  'band': 'kuungana',
  'bang': 'kugonga',
  'bank': 'kuweka benki',
  'bar': 'kuzuia',
  'bargain': 'kupatana',
  'barge': 'kuingia kwa nguvu',
  'bark': 'kubweka',
  'base': 'kuegemeza',
  'bash': 'kupiga',
  'bathe': 'kuoga',
  'battle': 'kupigana',
  'be': 'kuwa',
  'bear': 'kubeba',
  'beat': 'kupiga',
  'become': 'kuwa',
  'beef': 'kuimarisha',
  'befriend': 'kufanya urafiki',
  'beg': 'kuomba',
  'begin': 'kuanza',
  'beguile': 'kurubuni',
  'behave': 'kuwa na adabu',
  'behead': 'kukata kichwa',
  'behold': 'kutazama',
  'believe': 'kuamini',
  'belittle': 'kudharau',
  'belt': 'kupiga',
  'bend': 'kupinda',
  'benefit': 'kunufaika',
  'bequeath': 'kurithisha',
  'bestow': 'kutunuku',
  'bet': 'kuweka dau',
  'betray': 'kusaliti',
  'bewilder': 'kuchanganya',
  'bias': 'kupendelea',
  'bid': 'kuweka zabuni',
  'bide': 'kungoja',
  'bike': 'kuendesha baiskeli',
  'bill': 'kutoza',
  'bind': 'kufunga',
  'biopsy': 'kuchukua sampuli',
  'bit': '',
  'bitch': 'kulalamika',
  'bite': 'kuuma',
  'blame': 'kulaumu',
  'bleed': 'kutoka damu',
  'blend': 'kuchanganya',
  'blink': 'kupepesa macho',
  'blitz': 'kuvamia',
  'block': 'kuzuia',
  'blow': 'kupuliza',
  'blur': 'kufifisha',
  'board': 'kupanda',
  'boast': 'kujivuna',
  'bog': 'kukwama',
  'boil': 'kuchemsha',
  'bolster': 'kuimarisha',
  'bomb': 'kulipua',
  'bombard': 'kushambulia',
  'bond': 'kushikamana',
  'bone': 'kutoa mifupa',
  'book': 'kuweka nafasi',
  'boost': 'kuongeza nguvu',
  'boot': 'kufukuza',
  'border': 'kupakana',
  'borrow': 'kukopa',
  'bother': 'kusumbua',
  'bottle': 'kuweka chupani',
  'box': 'kupiga ngumi',
  'boycott': 'kususia',
  'brake': 'kupiga breki',
  'branch': 'kutoa matawi',
  'brand': 'kuweka chapa',
  'breach': 'kukiuka',
  'break': 'kuvunja',
  'breastfeed': 'kunyonyesha',
  'breathe': 'kupumua',
  'breed': 'kuzalisha',
  'bribe': 'kuhonga',
  'bridge': 'kuziba pengo',
  'bring': 'kuleta',
  'broadcast': 'kutangaza',
  'broaden': 'kupanua',
  'bruise': 'kuchubua',
  'brush': 'kupiga mswaki',
  'bubble': 'kutoa mapovu',
  'buckle': 'kufunga',
  'budget': 'kupanga bajeti',
  'buffer': 'kukinga',
  'build': 'kujenga',
  'bump': 'kugonga',
  'burden': 'kulemea',
  'burn': 'kuchoma',
  'burst': 'kupasuka',
  'bury': 'kuzika',
  'bust': 'kuvunja',
  'buy': 'kununua',
  'buzz': 'kuvuma',
  'bypass': 'kukwepa',
  'cake': 'kuganda',
  'call': 'kuita',
  'camp': 'kupiga kambi',
  'cancel': 'kufuta',
  'canoe': 'kuendesha mtumbwi',
  'cap': 'kuwekea kikomo',
  'capture': 'kukamata',
  'card': 'kukagua kitambulisho',
  'care': 'kujali',
  'careen': 'kuyumba',
  'cash': 'kubadilisha kuwa fedha',
  'cast': 'kutupa',
  'catalog': 'kuorodhesha',
  'catch': 'kukamata',
  'cater': 'kuandaa chakula',
  'caulk': 'kuziba',
  'cause': 'kusababisha',
  'caution': 'kuonya',
  'cave': 'kuporomoka',
  'cease': 'kukoma',
  'center': 'kuweka katikati',
  'centre': 'kuweka katikati',
  'chain': 'kufunga minyororo',
  'chair': 'kuongoza kikao',
  'challenge': 'kupa changamoto',
  'change': 'kubadilisha',
  'channel': 'kuelekeza',
  'charge': 'kutoza',
  'charm': 'kuvutia',
  'chart': 'kuchora ramani',
  'chase': 'kukimbiza',
  'cheat': 'kudanganya',
  'check': 'kukagua',
  'cheer': 'kushangilia',
  'cherish': 'kuthamini',
  'chew': 'kutafuna',
  'chip': 'kumega',
  'chirp': 'kulia',
  'choose': 'kuchagua',
  'chop': 'kukatakata',
  'circle': 'kuzunguka',
  'circumvent': 'kukwepa',
  'cite': 'kunukuu',
  'claim': 'kudai',
  'claw': 'kukwaruza',
  'cleanse': 'kutakasa',
  'click': 'kubofya',
  'cling': 'kung\'ang\'ania',
  'clip': 'kukata',
  'cloud': 'kutia giza',
  'club': 'kupiga rungu',
  'coalesce': 'kuungana',
  'coat': 'kupaka',
  'code': 'kuandika programu',
  'coerce': 'kulazimisha',
  'coexist': 'kuishi pamoja',
  'cohabit': 'kuishi kinyumba',
  'coin': 'kubuni',
  'coincide': 'kwenda sanjari',
  'collapse': 'kuporomoka',
  'collect': 'kukusanya',
  'collide': 'kugongana',
  'collude': 'kula njama',
  'color': 'kupaka rangi',
  'colour': 'kupaka rangi',
  'combat': 'kupambana',
  'combine': 'kuunganisha',
  'combust': 'kuwaka',
  'come': 'kuja',
  'comfort': 'kufariji',
  'command': 'kuamuru',
  'commence': 'kuanza',
  'comment': 'kutoa maoni',
  'commit': 'kujitoa',
  'commute': 'kusafiri kila siku',
  'compel': 'kulazimisha',
  'compete': 'kushindana',
  'compile': 'kukusanya',
  'complement': 'kukamilisha',
  'comply': 'kutii',
  'compound': 'kuzidisha',
  'compromise': 'kufikia mwafaka',
  'conceal': 'kuficha',
  'conceive': 'kutunga mimba',
  'concentrate': 'kukaza fikira',
  'concern': 'kuhusu',
  'conclude': 'kuhitimisha',
  'concur': 'kukubaliana',
  'condemn': 'kulaani',
  'condense': 'kufupisha',
  'condone': 'kuvumilia',
  'conduct': 'kuendesha',
  'confess': 'kukiri',
  'confide': 'kueleza siri',
  'configure': 'kusanidi',
  'confirm': 'kuthibitisha',
  'conflict': 'kukinzana',
  'conform': 'kuendana',
  'confront': 'kukabili',
  'confuse': 'kuchanganya',
  'conglomerate': 'kuungana',
  'conjure': 'kuibua',
  'connote': 'kudokeza',
  'conquer': 'kushinda',
  'consent': 'kuridhia',
  'conserve': 'kuhifadhi',
  'consider': 'kuzingatia',
  'consist': 'kuundwa na',
  'consolidate': 'kuimarisha',
  'conspire': 'kula njama',
  'constitute': 'kuunda',
  'constrain': 'kubana',
  'construct': 'kujenga',
  'consult': 'kushauriana',
  'consume': 'kutumia',
  'contact': 'kuwasiliana',
  'contain': 'kuwa na',
  'continue': 'kuendelea',
  'contrast': 'kulinganua',
  'contribute': 'kuchangia',
  'control': 'kudhibiti',
  'convene': 'kuitisha',
  'converge': 'kukutana',
  'convert': 'kubadilisha',
  'convey': 'kufikisha',
  'convince': 'kushawishi',
  'coordinate': 'kuratibu',
  'copy': 'kunakili',
  'core': 'kutoa kiini',
  'corrode': 'kuliwa na kutu',
  'cost': 'kugharimu',
  'cough': 'kukohoa',
  'counsel': 'kushauri',
  'count': 'kuhesabu',
  'couple': 'kuunganisha',
  'court': 'kuchumbia',
  'cover': 'kufunika',
  'crack': 'kupasua',
  'craft': 'kutengeneza',
  'crash': 'kuanguka',
  'crave': 'kutamani sana',
  'create': 'kuumba',
  'credit': 'kuweka salio',
  'creep': 'kutambaa',
  'cripple': 'kulemaza',
  'crop': 'kukata',
  'cross': 'kuvuka',
  'crowd': 'kusongamana',
  'crumble': 'kubomoka',
  'crush': 'kuponda',
  'cry': 'kulia',
  'cube': 'kukata mchemraba',
  'cue': 'kuashiria',
  'curb': 'kudhibiti',
  'cure': 'kuponya',
  'curl': 'kukunja',
  'curtail': 'kupunguza',
  'curve': 'kupinda',
  'cut': 'kukata',
  'dab': 'kugusa kidogo',
  'damage': 'kuharibu',
  'dampen': 'kutia unyevu',
  'dance': 'kucheza ngoma',
  'dare': 'kuthubutu',
  'darken': 'kutia giza',
  'dart': 'kuchomoka',
  'date': 'kuchumbiana',
  'daunt': 'kutia hofu',
  'deafen': 'kufanya kiziwi',
  'deal': 'kushughulika',
  'debark': 'kushuka',
  'debate': 'kujadili',
  'debrief': 'kuhoji',
  'debug': 'kuondoa hitilafu',
  'debunk': 'kufichua uongo',
  'debut': 'kuanza rasmi',
  'deceive': 'kudanganya',
  'decide': 'kuamua',
  'decimate': 'kuangamiza',
  'decipher': 'kufumbua',
  'declare': 'kutangaza',
  'decline': 'kukataa',
  'decode': 'kufumbua',
  'decommission': 'kusitisha matumizi',
  'decompose': 'kuoza',
  'decouple': 'kutenganisha',
  'decrease': 'kupungua',
  'decree': 'kuamuru',
  'decry': 'kulaani',
  'decrypt': 'kufungua msimbo',
  'deduct': 'kukata',
  'deepen': 'kuongeza kina',
  'deface': 'kuchafua',
  'defeat': 'kushinda',
  'defect': 'kuasi',
  'define': 'kufafanua',
  'deform': 'kuharibu umbo',
  'defraud': 'kulaghai',
  'defy': 'kukaidi',
  'delay': 'kuchelewesha',
  'delegate': 'kukasimu',
  'delight': 'kufurahisha',
  'delimit': 'kuweka mipaka',
  'deliver': 'kufikisha',
  'demand': 'kudai',
  'demean': 'kudhalilisha',
  'demolish': 'kubomoa',
  'denote': 'kumaanisha',
  'denounce': 'kushutumu',
  'deny': 'kukana',
  'depart': 'kuondoka',
  'depict': 'kuonyesha',
  'deplore': 'kusikitikia',
  'deploy': 'kupeleka',
  'deport': 'kufukuza nchini',
  'deposit': 'kuweka amana',
  'derail': 'kuvuruga',
  'derive': 'kutokana',
  'desert': 'kutelekeza',
  'design': 'kubuni',
  'desire': 'kutamani',
  'desist': 'kuacha',
  'detach': 'kutenganisha',
  'detail': 'kueleza kwa kina',
  'develop': 'kuendeleza',
  'devolve': 'kugatua',
  'diagnose': 'kutambua ugonjwa',
  'die': 'kufa',
  'differ': 'kutofautiana',
  'dig': 'kuchimba',
  'digest': 'kumeng\'enya',
  'diminish': 'kupungua',
  'dine': 'kula chakula',
  'dip': 'kuchovya',
  'disable': 'kulemaza',
  'disarm': 'kupokonya silaha',
  'disband': 'kuvunja',
  'disburse': 'kutoa fedha',
  'discard': 'kutupa',
  'discern': 'kutambua',
  'discharge': 'kuachilia',
  'disclaim': 'kukana',
  'disclose': 'kufichua',
  'discourage': 'kukatisha tamaa',
  'discover': 'kugundua',
  'discuss': 'kujadili',
  'disguise': 'kubadilisha sura',
  'dish': 'kupakua',
  'dislike': 'kutopenda',
  'dislodge': 'kung\'oa',
  'dismantle': 'kubomoa',
  'dispatch': 'kutuma',
  'dispense': 'kugawa',
  'disperse': 'kutawanya',
  'displace': 'kuhamisha',
  'display': 'kuonyesha',
  'displease': 'kuchukiza',
  'dispose': 'kutupa',
  'disprove': 'kukanusha',
  'dispute': 'kupinga',
  'disrupt': 'kuvuruga',
  'dissolve': 'kuyeyusha',
  'dissuade': 'kushawishi kuacha',
  'distil': 'kuchuja',
  'distill': 'kuchuja',
  'distinguish': 'kutofautisha',
  'distort': 'kupotosha',
  'disturb': 'kusumbua',
  'ditch': 'kutelekeza',
  'dive': 'kupiga mbizi',
  'diverge': 'kuachana',
  'divert': 'kuchepusha',
  'divest': 'kujiondoa',
  'divide': 'kugawanya',
  'divorce': 'kutaliki',
  'divulge': 'kufichua',
  'do': 'kufanya',
  'dock': 'kutia nanga',
  'document': 'kuweka kumbukumbu',
  'dodge': 'kukwepa',
  'doubt': 'kushuku',
  'download': 'kupakua',
  'draft': 'kuandaa rasimu',
  'drag': 'kukokota',
  'drain': 'kuondoa maji',
  'draw': 'kuchora',
  'dream': 'kuota',
  'dredge': 'kuchimbua',
  'dress': 'kuvaa',
  'drift': 'kuelea',
  'drill': 'kutoboa',
  'drink': 'kunywa',
  'drip': 'kudondoka',
  'drive': 'kuendesha',
  'drone': 'kuvuma',
  'drop': 'kuangusha',
  'drown': 'kuzama',
  'dub': 'kupachika jina',
  'duel': 'kupigana',
  'dump': 'kutupa',
  'duplicate': 'kunakili',
  'dwindle': 'kupungua',
  'dye': 'kupaka rangi',
  'earmark': 'kutenga',
  'earn': 'kuchuma',
  'eat': 'kula',
  'echo': 'kurudia',
  'edge': 'kusogea',
  'edit': 'kuhariri',
  'effect': 'kuleta',
  'elapse': 'kupita',
  'elect': 'kuchagua',
  'elucidate': 'kufafanua',
  'elude': 'kukwepa',
  'embalm': 'kuhifadhi maiti',
  'embark': 'kuanza safari',
  'embody': 'kuwakilisha',
  'embrace': 'kukumbatia',
  'embroider': 'kutarizi',
  'embroil': 'kuingiza mgogoroni',
  'emerge': 'kujitokeza',
  'emphasize': 'kusisitiza',
  'empower': 'kuwezesha',
  'enable': 'kuwezesha',
  'enact': 'kutunga sheria',
  'encircle': 'kuzingira',
  'enclose': 'kuambatanisha',
  'encounter': 'kukutana',
  'encourage': 'kutia moyo',
  'encroach': 'kuvamia',
  'encrypt': 'kusimba',
  'encumber': 'kulemea',
  'end': 'kumaliza',
  'endanger': 'kuhatarisha',
  'endorse': 'kuidhinisha',
  'endow': 'kujalia',
  'endure': 'kuvumilia',
  'enforce': 'kutekeleza',
  'engage': 'kushirikisha',
  'engender': 'kuzaa',
  'engrave': 'kuchonga',
  'engulf': 'kumeza',
  'enhance': 'kuboresha',
  'enjoy': 'kufurahia',
  'enlarge': 'kukuza',
  'enlist': 'kujiunga',
  'enquire': 'kuuliza',
  'enrich': 'kutajirisha',
  'enrol': 'kujiandikisha',
  'enroll': 'kujiandikisha',
  'ensue': 'kufuatia',
  'ensure': 'kuhakikisha',
  'enter': 'kuingia',
  'entice': 'kurubuni',
  'entrain': 'kupanda treni',
  'entrench': 'kujikita',
  'entrust': 'kukabidhi',
  'envelop': 'kufunika',
  'envisage': 'kutazamia',
  'envision': 'kutazamia',
  'envy': 'kuonea wivu',
  'equip': 'kupatia vifaa',
  'erase': 'kufuta',
  'erupt': 'kulipuka',
  'escape': 'kutoroka',
  'eschew': 'kuepuka',
  'espouse': 'kuunga mkono',
  'establish': 'kuanzisha',
  'estimate': 'kukadiria',
  'etch': 'kuchonga',
  'evaluate': 'kutathmini',
  'evoke': 'kuibua',
  'evolve': 'kubadilika',
  'exalt': 'kutukuza',
  'examine': 'kuchunguza',
  'exceed': 'kuzidi',
  'excel': 'kubobea',
  'exchange': 'kubadilishana',
  'exclaim': 'kupaza sauti',
  'exclude': 'kutenga',
  'excuse': 'kusamehe',
  'exercise': 'kufanya mazoezi',
  'exert': 'kutumia nguvu',
  'exhale': 'kutoa pumzi',
  'exhaust': 'kuchosha',
  'exhibit': 'kuonyesha',
  'exhort': 'kuhimiza',
  'exhume': 'kufukua',
  'exist': 'kuwepo',
  'exit': 'kutoka',
  'expect': 'kutarajia',
  'expedite': 'kuharakisha',
  'expel': 'kufukuza',
  'experience': 'kupitia',
  'experiment': 'kufanya majaribio',
  'expire': 'kuisha muda',
  'explain': 'kueleza',
  'exploit': 'kunyonya',
  'explore': 'kuchunguza',
  'export': 'kusafirisha nje',
  'expose': 'kufichua',
  'expunge': 'kufuta kabisa',
  'extinguish': 'kuzima',
  'extol': 'kusifu',
  'extract': 'kuchomoa',
  'exude': 'kutokwa',
  'eye': 'kukodolea macho',
  'eyeball': 'kukadiria kwa macho',
  'face': 'kukabili',
  'fail': 'kushindwa',
  'fall': 'kuanguka',
  'falter': 'kuyumba',
  'farm': 'kulima',
  'fasten': 'kufunga',
  'favour': 'kupendelea',
  'fear': 'kuogopa',
  'feature': 'kuangazia',
  'feed': 'kulisha',
  'feel': 'kuhisi',
  'fence': 'kuzungushia uzio',
  'ferment': 'kuchachusha',
  'field': 'kujibu maswali',
  'fight': 'kupigana',
  'figure': 'kubaini',
  'file': 'kuwasilisha',
  'film': 'kurekodi video',
  'filter': 'kuchuja',
  'finance': 'kugharamia',
  'find': 'kukuta',
  'finish': 'kumaliza',
  'fire': 'kufukuza kazi',
  'fish': 'kuvua samaki',
  'fit': 'kutosha',
  'fix': 'kurekebisha',
  'flag': 'kuweka alama',
  'flake': 'kubambuka',
  'flame': 'kuwaka moto',
  'flare': 'kuwaka ghafla',
  'flash': 'kumulika',
  'flatter': 'kusifu mno',
  'flavor': 'kuongeza ladha',
  'flavour': 'kuongeza ladha',
  'flee': 'kukimbia',
  'flesh': 'kukamilisha',
  'fling': 'kuvurumisha',
  'flip': 'kupindua',
  'float': 'kuelea',
  'flock': 'kumiminika',
  'flood': 'kufurika',
  'flow': 'kutiririka',
  'flower': 'kutoa maua',
  'fly': 'kuruka',
  'focus': 'kulenga',
  'fog': 'kutia ukungu',
  'foil': 'kuzima',
  'fold': 'kukunja',
  'foot': 'kulipa gharama',
  'forbid': 'kukataza',
  'force': 'kulazimisha',
  'forecast': 'kutabiri',
  'foreclose': 'kunyang\'anya',
  'forego': 'kuacha',
  'foreshadow': 'kuashiria',
  'forewarn': 'kuonya mapema',
  'forfeit': 'kupoteza',
  'forge': 'kughushi',
  'forget': 'kusahau',
  'forgive': 'kusamehe',
  'form': 'kuunda',
  'format': 'kupangilia',
  'forsake': 'kutelekeza',
  'forsee': 'kuona mbele',
  'forward': 'kupeleka mbele',
  'fracture': 'kuvunjika',
  'fragment': 'kusambaratika',
  'frame': 'kusingizia',
  'franchise': 'kutoa leseni',
  'freeze': 'kuganda',
  'freshen': 'kuburudisha',
  'frighten': 'kutisha',
  'frolic': 'kurukaruka',
  'frost': 'kufunika kwa barafu',
  'frown': 'kukunja uso',
  'fry': 'kukaanga',
  'fuck': 'kutomba',
  'fuel': 'kuchochea',
  'fulfil': 'kutimiza',
  'function': 'kufanya kazi',
  'fund': 'kufadhili',
  'fundraise': 'kuchangisha',
  'furnish': 'kuweka samani',
  'fuss': 'kuhangaika',
  'fuzz': 'kufifisha',
  'gag': 'kuziba mdomo',
  'gain': 'kupata faida',
  'game': 'kucheza kamari',
  'gang': 'kuungana',
  'gas': 'kujaza mafuta',
  'gate': 'kufunga lango',
  'gather': 'kukusanya',
  'gaze': 'kukazia macho',
  'gear': 'kujiandaa',
  'get': 'kupata',
  'gift': 'kuzawadia',
  'giggle': 'kuchekacheka',
  'give': 'kutoa',
  'glare': 'kukodolea macho',
  'glean': 'kuokota',
  'gloss': 'kung\'arisha',
  'glow': 'kung\'aa',
  'glue': 'kubandika',
  'go': 'kwenda',
  'gossip': 'kusengenya',
  'govern': 'kutawala',
  'grab': 'kunyakua',
  'grade': 'kupanga madaraja',
  'grapple': 'kupambana',
  'grasp': 'kushika',
  'graze': 'kula majani',
  'greet': 'kusalimia',
  'grill': 'kuchoma',
  'grind': 'kusaga',
  'grip': 'kushika kwa nguvu',
  'ground': 'kusimamisha',
  'grow': 'kukua',
  'growth': 'kukua',
  'grumble': 'kunung\'unika',
  'guarantee': 'kudhamini',
  'guard': 'kulinda',
  'guess': 'kubahatisha',
  'gulp': 'kumeza kwa haraka',
  'gun': 'kupiga risasi',
  'hack': 'kudukua',
  'ham': 'kuigiza kupita kiasi',
  'hammer': 'kupiga nyundo',
  'hamper': 'kukwamisha',
  'hand': 'kukabidhi',
  'handle': 'kushughulikia',
  'hang': 'kutundika',
  'happen': 'kutokea',
  'harangue': 'kukemea',
  'harass': 'kunyanyasa',
  'harbour': 'kuficha',
  'harm': 'kudhuru',
  'harness': 'kutumia',
  'harvest': 'kuvuna',
  'hash': 'kujadili',
  'hasten': 'kuharakisha',
  'hatch': 'kuangua',
  'hate': 'kuchukia',
  'haunt': 'kuandama',
  'have': 'kuwa na',
  'head': 'kuongoza',
  'hear': 'kusikia',
  'heat': 'kupasha moto',
  'hedge': 'kujikinga',
  'heighten': 'kuongeza',
  'help': 'kusaidia',
  'hide': 'kuficha',
  'highlight': 'kuangazia',
  'hijack': 'kuteka',
  'hike': 'kupanda milima',
  'hinder': 'kukwamisha',
  'hint': 'kudokeza',
  'hire': 'kuajiri',
  'hit': 'kupiga',
  'hoist': 'kupandisha',
  'hold': 'kushika',
  'hole': 'kutoboa',
  'honor': 'kuheshimu',
  'honour': 'kuheshimu',
  'hook': 'kunasa',
  'hop': 'kurukaruka',
  'hope': 'kutumaini',
  'horse': 'kuchezacheza',
  'house': 'kupa makazi',
  'hug': 'kukumbatia',
  'hunt': 'kuwinda',
  'hurt': 'kuumiza',
  'ignore': 'kupuuza',
  'imbue': 'kujaza',
  'immerse': 'kuzamisha',
  'impact': 'kuathiri',
  'impale': 'kuchoma',
  'impart': 'kutoa maarifa',
  'imperil': 'kuhatarisha',
  'impinge': 'kuingilia',
  'implement': 'kutekeleza',
  'imply': 'kudokeza',
  'import': 'kuagiza kutoka nje',
  'impose': 'kulazimisha',
  'impoverish': 'kufukarisha',
  'impress': 'kuvutia',
  'imprison': 'kufunga gerezani',
  'improve': 'kuboresha',
  'incite': 'kuchochea',
  'incline': 'kuelekea',
  'include': 'kujumuisha',
  'increase': 'kuongeza',
  'index': 'kuorodhesha',
  'indicate': 'kuonyesha',
  'indulge': 'kujifurahisha',
  'infest': 'kuvamia',
  'influence': 'kushawishi',
  'inform': 'kufahamisha',
  'infuse': 'kuingiza',
  'ingest': 'kumeza',
  'inhabit': 'kukaa',
  'inhale': 'kuvuta pumzi',
  'inhibit': 'kuzuia',
  'initiate': 'kuanzisha',
  'injure': 'kujeruhi',
  'ink': 'kusaini',
  'inquire': 'kuuliza',
  'insert': 'kuingiza',
  'insist': 'kusisitiza',
  'inspire': 'kuhamasisha',
  'install': 'kusakinisha',
  'instil': 'kupandikiza',
  'instruct': 'kuelekeza',
  'insure': 'kukata bima',
  'intent': 'kukusudia',
  'interact': 'kuingiliana',
  'interest': 'kuvutia',
  'interface': 'kuwasiliana',
  'intern': 'kufanya mafunzo',
  'interpret': 'kutafsiri',
  'interrupt': 'kukatiza',
  'interview': 'kuhoji',
  'intimidate': 'kutisha',
  'intoxicate': 'kulevya',
  'introduce': 'kutambulisha',
  'intrude': 'kuingilia',
  'inundate': 'kufurika',
  'invade': 'kuvamia',
  'invent': 'kubuni',
  'invert': 'kupindua',
  'invest': 'kuwekeza',
  'invoice': 'kutuma ankara',
  'invoke': 'kutaja',
  'involve': 'kushirikisha',
  'irk': 'kuudhi',
  'iron': 'kupiga pasi',
  'issue': 'kutoa',
  'jam': 'kukwama',
  'jazz': 'kupamba',
  'join': 'kujiunga',
  'joke': 'kutania',
  'juggle': 'kurusha mipira',
  'juice': 'kukamua',
  'jump': 'kuruka',
  'juxtapose': 'kuweka sambamba',
  'keel': 'kupinduka',
  'keep': 'kutunza',
  'key': 'kuingiza',
  'kick': 'kupiga teke',
  'kid': 'kutania',
  'kidnap': 'kuteka nyara',
  'kill': 'kuua',
  'kiss': 'kubusu',
  'kneel': 'kupiga magoti',
  'knock': 'kugonga',
  'know': 'kujua',
  'label': 'kuweka lebo',
  'labor': 'kutaabika',
  'labour': 'kutaabika',
  'lace': 'kufunga kamba',
  'lack': 'kukosa',
  'land': 'kutua',
  'languish': 'kudhoofika',
  'lap': 'kulamba',
  'latch': 'kufunga komeo',
  'laugh': 'kucheka',
  'launch': 'kuzindua',
  'launder': 'kufua',
  'leach': 'kuvuja',
  'lead': 'kuongoza',
  'leak': 'kuvuja',
  'leap': 'kuruka',
  'learn': 'kujifunza',
  'lease': 'kukodisha',
  'leave': 'kuondoka',
  'lecture': 'kutoa mhadhara',
  'leech': 'kunyonya',
  'lend': 'kukopesha',
  'lengthen': 'kurefusha',
  'lessen': 'kupunguza',
  'level': 'kusawazisha',
  'levy': 'kutoza',
  'license': 'kutoa leseni',
  'lick': 'kulamba',
  'lie': 'kusema uongo',
  'lift': 'kuinua',
  'like': 'kupenda',
  'limit': 'kuweka kikomo',
  'line': 'kupanga mstari',
  'linger': 'kukawia',
  'link': 'kuunganisha',
  'liquefy': 'kuyeyusha',
  'liquidate': 'kufilisi',
  'list': 'kuorodhesha',
  'liven': 'kuchangamsha',
  'load': 'kupakia',
  'loan': 'kukopesha',
  'lobby': 'kushawishi',
  'lock': 'kufunga kufuli',
  'log': 'kurekodi',
  'look': 'kuangalia',
  'loot': 'kupora',
  'lose': 'kupoteza',
  'love': 'kupenda',
  'lump': 'kuweka pamoja',
  'lurk': 'kuvizia',
  'lust': 'kutamani kimwili',
  'mail': 'kutuma barua',
  'maim': 'kulemaza',
  'maintain': 'kudumisha',
  'make': 'kutengeneza',
  'manage': 'kusimamia',
  'mandate': 'kuagiza',
  'manner': '',
  'manoeuvre': 'kufanya mbinu',
  'map': 'kuchora ramani',
  'market': 'kutafuta soko',
  'mash': 'kuponda',
  'mask': 'kuficha',
  'master': 'kumudu',
  'match': 'kulingana',
  'matter': 'kujalisha',
  'measure': 'kupima',
  'meet': 'kukutana',
  'mention': 'kutaja',
  'merge': 'kuunganisha',
  'merit': 'kustahili',
  'mess': 'kuvuruga',
  'milk': 'kukamua',
  'mimic': 'kuiga',
  'mimick': 'kuiga',
  'mince': 'kusaga',
  'mind': 'kujali',
  'mine': 'kuchimba madini',
  'mingle': 'kuchangamana',
  'minus': 'kutoa',
  'mirror': 'kuakisi',
  'misplace': 'kupoteza',
  'miss': 'kukosa',
  'mistake': 'kukosea',
  'mix': 'kuchanganya',
  'mock': 'kudhihaki',
  'model': 'kuwa mfano',
  'mold': 'kufinyanga',
  'molest': 'kunyanyasa kingono',
  'monitor': 'kufuatilia',
  'monkey': 'kuchezacheza',
  'mop': 'kupiga deki',
  'mount': 'kupanda',
  'mourn': 'kuomboleza',
  'mouth': 'kutamka',
  'move': 'kusonga',
  'mow': 'kukata nyasi',
  'multiply': 'kuzidisha',
  'murder': 'kuua kimakusudi',
  'name': 'kutaja',
  'need': 'kuhitaji',
  'neglect': 'kupuuza',
  'net': 'kunasa',
  'network': 'kujenga mtandao',
  'nod': 'kuitikia kwa kichwa',
  'note': 'kuzingatia',
  'notice': 'kutambua',
  'nourish': 'kulisha',
  'nurse': 'kuuguza',
  'obey': 'kutii',
  'object': 'kupinga',
  'observe': 'kuchunguza',
  'obsess': 'kuhangaikia',
  'obtain': 'kupata',
  'occupy': 'kukalia',
  'occur': 'kutokea',
  'offer': 'kutoa',
  'oil': 'kupaka mafuta',
  'omit': 'kuacha',
  'ooze': 'kuvuja',
  'operate': 'kuendesha',
  'opine': 'kutoa maoni',
  'oppose': 'kupinga',
  'orbit': 'kuzunguka',
  'order': 'kuagiza',
  'orient': 'kuelekeza',
  'outgrow': 'kuzidi',
  'outline': 'kutoa muhtasari',
  'outnumber': 'kuzidi kwa idadi',
  'outpace': 'kuzidi kwa kasi',
  'overlap': 'kuingiliana',
  'overpass': 'kupita juu',
  'oversee': 'kusimamia',
  'overshadow': 'kufunika',
  'overturn': 'kupindua',
  'overuse': 'kutumia kupita kiasi',
  'overwhelm': 'kulemea',
  'owe': 'kudaiwa',
  'pack': 'kufunga mizigo',
  'package': 'kufungasha',
  'paint': 'kupaka rangi',
  'pair': 'kuoanisha',
  'paise': 'kusifu',
  'pamper': 'kudekeza',
  'pan': 'kukosoa',
  'panic': 'kuingiwa na hofu',
  'paralyse': 'kupooza',
  'park': 'kuegesha',
  'part': 'kutengana',
  'participate': 'kushiriki',
  'party': 'kusherehekea',
  'pass': 'kupita',
  'paste': 'kubandika',
  'patch': 'kuziba',
  'patent': 'kusajili hataza',
  'patrol': 'kufanya doria',
  'pause': 'kutua',
  'pave': 'kuweka lami',
  'pay': 'kulipa',
  'peak': 'kufikia kilele',
  'pee': 'kukojoa',
  'peel': 'kumenya',
  'peer': 'kuchungulia',
  'pen': 'kuandika',
  'pencil': 'kuandika kwa penseli',
  'perceive': 'kutambua',
  'perform': 'kutumbuiza',
  'perfume': 'kutia manukato',
  'perish': 'kuangamia',
  'permeate': 'kupenya',
  'permit': 'kuruhusu',
  'perplex': 'kutatanisha',
  'persevere': 'kuvumilia',
  'persist': 'kuendelea',
  'persuade': 'kushawishi',
  'pervade': 'kuenea',
  'pet': 'kupapasa',
  'phase': 'kufanya kwa awamu',
  'phone': 'kupiga simu',
  'photograph': 'kupiga picha',
  'pick': 'kuchagua',
  'pile': 'kurundika',
  'pin': 'kuchomeka',
  'pine': 'kutamani',
  'pinpoint': 'kubainisha',
  'pipe': 'kupitisha kwa bomba',
  'pit': 'kushindanisha',
  'pity': 'kuhurumia',
  'pivot': 'kugeuka',
  'place': 'kuweka',
  'plan': 'kupanga',
  'plant': 'kupanda',
  'play': 'kucheza',
  'plce': 'kuweka',
  'plead': 'kusihi',
  'plug': 'kuziba',
  'plummet': 'kuporomoka',
  'plump': 'kunenepesha',
  'plunge': 'kutumbukia',
  'poach': 'kuwinda haramu',
  'point': 'kuonyesha',
  'poison': 'kutia sumu',
  'police': 'kudhibiti',
  'polish': 'kung\'arisha',
  'poll': 'kufanya kura ya maoni',
  'pollute': 'kuchafua',
  'pool': 'kuunganisha',
  'poop': 'kunya',
  'pop': 'kupasuka',
  'pore': 'kusoma kwa makini',
  'portray': 'kusawiri',
  'pose': 'kupiga pozi',
  'position': 'kuweka',
  'possess': 'kumiliki',
  'post': 'kuchapisha',
  'pound': 'kutwanga',
  'power': 'kuwezesha',
  'practice': 'kufanya mazoezi',
  'praise': 'kusifu',
  'preach': 'kuhubiri',
  'preclude': 'kuzuia',
  'predetermine': 'kuamua mapema',
  'predict': 'kutabiri',
  'prefer': 'kupendelea',
  'preoccupy': 'kushughulisha',
  'preserve': 'kuhifadhi',
  'press': 'kubonyeza',
  'presuppose': 'kudhania mapema',
  'prevail': 'kushinda',
  'prevent': 'kuzuia',
  'prey': 'kuwinda',
  'price': 'kupanga bei',
  'pride': 'kujivunia',
  'print': 'kuchapa',
  'probe': 'kuchunguza',
  'proceed': 'kuendelea',
  'process': 'kusindika',
  'proclaim': 'kutangaza',
  'procure': 'kupata',
  'prod': 'kuchokoza',
  'produce': 'kuzalisha',
  'profess': 'kudai',
  'profile': 'kueleza wasifu',
  'program': 'kuandika programu',
  'programme': 'kuandika programu',
  'progress': 'kupiga hatua',
  'prohibit': 'kukataza',
  'project': 'kukadiria',
  'promise': 'kuahidi',
  'promote': 'kukuza',
  'pronounce': 'kutamka',
  'prop': 'kuegemeza',
  'propose': 'kupendekeza',
  'prosper': 'kufanikiwa',
  'protest': 'kuandamana',
  'protrude': 'kutokeza',
  'prove': 'kuthibitisha',
  'provide': 'kutoa',
  'provoke': 'kuchokoza',
  'prune': 'kupogoa',
  'psych': 'kutisha',
  'publish': 'kuchapisha',
  'puke': 'kutapika',
  'pump': 'kusukuma',
  'punch': 'kupiga ngumi',
  'punish': 'kuadhibu',
  'purchase': 'kununua',
  'purport': 'kudai',
  'pursuant': '',
  'pursue': 'kufuatilia',
  'push': 'kusukuma',
  'put': 'kuweka',
  'quash': 'kubatilisha',
  'quench': 'kukata kiu',
  'question': 'kuhoji',
  'quit': 'kuacha',
  'quiver': 'kutetemeka',
  'quote': 'kunukuu',
  'race': 'kushindana mbio',
  'rack': 'kutesa',
  'rage': 'kuwaka hasira',
  'rain': 'kunyesha',
  'raise': 'kuinua',
  'rake': 'kukwangua',
  'rally': 'kuhamasisha',
  'range': 'kutofautiana',
  'rank': 'kupanga daraja',
  'rant': 'kufoka',
  'rap': 'kugonga',
  'rape': 'kubaka',
  'rat': 'kuchongea',
  'rate': 'kukadiria',
  'rattle': 'kutikisa',
  'ravish': 'kuvutia sana',
  'reach': 'kufikia',
  'react': 'kuitikia',
  'read': 'kusoma',
  'realise': 'kutambua',
  'realize': 'kutambua',
  'reap': 'kuvuna',
  'reason': 'kutoa hoja',
  'reboot': 'kuwasha upya',
  'rebuff': 'kukataa',
  'recall': 'kukumbuka',
  'receive': 'kupokea',
  'reckon': 'kudhani',
  'reclaim': 'kurudisha',
  'recognize': 'kutambua',
  'reconcile': 'kupatanisha',
  'record': 'kurekodi',
  'recoup': 'kufidia',
  'recover': 'kupona',
  'recycle': 'kurejeleza',
  'redact': 'kufuta maandishi',
  'redo': 'kufanya upya',
  'reduce': 'kupunguza',
  'reel': 'kupepesuka',
  'refactor': 'kuboresha msimbo',
  'reference': 'kurejelea',
  'refinance': 'kubadilisha mkopo',
  'refine': 'kusafisha',
  'reflect': 'kuakisi',
  'refocus': 'kuelekeza upya',
  'reform': 'kurekebisha',
  'refract': 'kupinda mwanga',
  'refresh': 'kuburudisha',
  'refuel': 'kujaza mafuta',
  'refund': 'kurudisha pesa',
  'refurbish': 'kukarabati',
  'refuse': 'kukataa',
  'regard': 'kuchukulia',
  'register': 'kusajili',
  'regret': 'kujuta',
  'regroup': 'kujipanga upya',
  'rehearse': 'kufanya mazoezi',
  'reheat': 'kupasha moto',
  'reimburse': 'kurudisha gharama',
  'reinforce': 'kuimarisha',
  'reject': 'kukataa',
  'rejoice': 'kushangilia',
  'relate': 'kuhusiana',
  'release': 'kuachilia',
  'relent': 'kulegeza msimamo',
  'relieve': 'kutuliza',
  'relinquish': 'kuachia',
  'relish': 'kufurahia',
  'relive': 'kupitia tena',
  'reload': 'kupakia upya',
  'rely': 'kutegemea',
  'remain': 'kubaki',
  'remake': 'kutengeneza upya',
  'remark': 'kutoa maoni',
  'remedy': 'kurekebisha',
  'remember': 'kukumbuka',
  'remove': 'kuondoa',
  'render': 'kufanya',
  'rendezvous': 'kukutana',
  'renew': 'kuhuisha',
  'renounce': 'kukana',
  'rent': 'kukodi',
  'reorder': 'kuagiza tena',
  'repair': 'kutengeneza',
  'repeal': 'kufuta sheria',
  'repeat': 'kurudia',
  'repel': 'kufukuza',
  'rephrase': 'kueleza upya',
  'replace': 'kubadilisha',
  'replenish': 'kujaza tena',
  'replicate': 'kunakili',
  'reply': 'kujibu',
  'report': 'kuripoti',
  'represent': 'kuwakilisha',
  'request': 'kuomba',
  'require': 'kuhitaji',
  'resemble': 'kufanana',
  'resent': 'kuchukizwa',
  'reserve': 'kuhifadhi',
  'reside': 'kuishi',
  'resign': 'kujiuzulu',
  'resist': 'kupinga',
  'resolve': 'kutatua',
  'resort': 'kukimbilia',
  'respect': 'kuheshimu',
  'respond': 'kujibu',
  'rest': 'kupumzika',
  'restart': 'kuanza upya',
  'restock': 'kujaza bidhaa',
  'restrain': 'kuzuia',
  'restrict': 'kuwekea mipaka',
  'restructure': 'kupanga upya',
  'result': 'kusababisha',
  'resume': 'kuendelea tena',
  'resurface': 'kuibuka tena',
  'retire': 'kustaafu',
  'retrieve': 'kurejesha',
  'retrofit': 'kuweka vifaa vipya',
  'return': 'kurudi',
  'reup': 'kuhuisha',
  'revamp': 'kuboresha',
  'reveal': 'kufichua',
  'revel': 'kufurahia',
  'revere': 'kuheshimu sana',
  'reverse': 'kugeuza',
  'revert': 'kurudi',
  'review': 'kupitia',
  'revisit': 'kutembelea tena',
  'revive': 'kufufua',
  'revoke': 'kubatilisha',
  'revolve': 'kuzunguka',
  'reward': 'kuzawadia',
  'rhyme': 'kuwa na vina',
  'rid': 'kuondokana',
  'ride': 'kupanda',
  'ring': 'kulia',
  'riot': 'kufanya ghasia',
  'rip': 'kurarua',
  'ripen': 'kuiva',
  'rise': 'kuinuka',
  'risk': 'kuhatarisha',
  'roam': 'kuzurura',
  'roast': 'kuchoma',
  'rock': 'kutikisa',
  'roll': 'kuviringisha',
  'roof': 'kuezeka',
  'root': 'kushangilia',
  'rope': 'kufunga kamba',
  'rot': 'kuoza',
  'rout': 'kushinda kabisa',
  'route': 'kuelekeza',
  'rub': 'kusugua',
  'ruin': 'kuharibu',
  'rule': 'kutawala',
  'run': 'kukimbia',
  'rush': 'kuharakisha',
  'rust': 'kupata kutu',
  'sack': 'kufukuza kazi',
  'sacrifice': 'kutoa mhanga',
  'sadden': 'kuhuzunisha',
  'safeguard': 'kulinda',
  'sail': 'kusafiri kwa meli',
  'sample': 'kuonja',
  'satisfy': 'kuridhisha',
  'say': 'kusema',
  'scale': 'kupanda',
  'scan': 'kuchanganua',
  'scar': 'kuacha kovu',
  'scare': 'kutisha',
  'scavenge': 'kutafuta mabaki',
  'schedule': 'kupanga ratiba',
  'score': 'kufunga',
  'scrape': 'kukwangua',
  'scratch': 'kukuna',
  'screen': 'kuchuja',
  'screw': 'kukaza parafujo',
  'scribble': 'kuchorachora',
  'scroll': 'kusogeza',
  'sculpt': 'kuchonga',
  'seal': 'kuziba',
  'search': 'kutafuta',
  'seat': 'kuketisha',
  'see': 'kuona',
  'seed': 'kupanda mbegu',
  'seek': 'kutafuta',
  'seem': 'kuonekana',
  'sell': 'kuuza',
  'send': 'kutuma',
  'sense': 'kuhisi',
  'sentence': 'kuhukumu',
  'sequester': 'kutenga',
  'serve': 'kuhudumia',
  'service': 'kufanyia matengenezo',
  'set': 'kuweka',
  'sever': 'kukata',
  'sew': 'kushona',
  'shack': 'kuishi pamoja',
  'shade': 'kutia kivuli',
  'shake': 'kutikisa',
  'shape': 'kuunda',
  'share': 'kugawana',
  'sharpen': 'kunoa',
  'shatter': 'kuvunjavunja',
  'shave': 'kunyoa',
  'shed': 'kumwaga',
  'sheild': 'kukinga',
  'shelter': 'kupa hifadhi',
  'shift': 'kuhamisha',
  'shine': 'kung\'aa',
  'ship': 'kusafirisha',
  'shiver': 'kutetemeka',
  'shock': 'kushtua',
  'shoot': 'kupiga risasi',
  'shop': 'kufanya manunuzi',
  'shore': 'kuimarisha',
  'shorten': 'kufupisha',
  'show': 'kuonyesha',
  'shrink': 'kusinyaa',
  'shrivel': 'kunyauka',
  'shuffle': 'kuchanganya',
  'shun': 'kuepuka',
  'side': 'kuunga mkono',
  'sift': 'kuchuja',
  'sign': 'kutia saini',
  'signal': 'kuashiria',
  'silence': 'kunyamazisha',
  'sing': 'kuimba',
  'sink': 'kuzama',
  'sip': 'kunywa polepole',
  'sit': 'kukaa',
  'size': 'kupima',
  'skateboard': 'kuteleza kwa ubao',
  'ski': 'kuteleza kwenye theluji',
  'skip': 'kuruka',
  'slam': 'kugonga kwa nguvu',
  'slay': 'kuua',
  'sleep': 'kulala',
  'slice': 'kukata vipande',
  'slide': 'kuteleza',
  'slip': 'kuteleza',
  'slit': 'kupasua',
  'slouch': 'kuinama',
  'smash': 'kuponda',
  'smell': 'kunusa',
  'smile': 'kutabasamu',
  'smirk': 'kutabasamu kwa dharau',
  'smoke': 'kuvuta sigara',
  'smuggle': 'kufanya magendo',
  'snake': 'kupindapinda',
  'snap': 'kukatika',
  'snatch': 'kunyakua',
  'sneak': 'kunyemelea',
  'sneeze': 'kupiga chafya',
  'sniff': 'kunusa',
  'snow': 'kunyesha theluji',
  'sob': 'kulia kwa kwikwi',
  'solicit': 'kuomba',
  'solve': 'kutatua',
  'soothe': 'kutuliza',
  'sound': 'kusikika',
  'sow': 'kupanda mbegu',
  'spam': 'kutuma barua taka',
  'span': 'kuvuka',
  'spark': 'kuchochea',
  'spawn': 'kuzaa',
  'speak': 'kuzungumza',
  'speed': 'kwenda kasi',
  'spell': 'kuendeleza',
  'spend': 'kutumia',
  'spill': 'kumwaga',
  'spin': 'kuzungusha',
  'spiral': 'kuzunguka',
  'spit': 'kutema mate',
  'spite': 'kuudhi',
  'splash': 'kurusha maji',
  'splay': 'kutandaza',
  'split': 'kugawanya',
  'spoil': 'kuharibu',
  'sponsor': 'kudhamini',
  'spoof': 'kuigiza kwa dhihaka',
  'spot': 'kubaini',
  'spray': 'kunyunyizia',
  'spread': 'kueneza',
  'spring': 'kuchupa',
  'sprinkle': 'kunyunyiza',
  'spruce': 'kupendezesha',
  'spur': 'kuchochea',
  'spy': 'kupeleleza',
  'squander': 'kutapanya',
  'square': 'kulinganisha',
  'squish': 'kufinya',
  'stab': 'kudunga',
  'stack': 'kurundika',
  'staff': 'kuajiri wafanyakazi',
  'stage': 'kuandaa',
  'stagger': 'kupepesuka',
  'stain': 'kutia doa',
  'stake': 'kuweka dau',
  'stalk': 'kunyemelea',
  'stall': 'kukwama',
  'stamp': 'kupiga muhuri',
  'stand': 'kusimama',
  'staple': 'kubana kwa stepla',
  'star': 'kuwa nyota',
  'stare': 'kukodolea macho',
  'start': 'kuanza',
  'startle': 'kushtua',
  'starve': 'kufa njaa',
  'state': 'kueleza',
  'stay': 'kukaa',
  'steal': 'kuiba',
  'steer': 'kuongoza',
  'stem': 'kutokana',
  'step': 'kukanyaga',
  'stick': 'kubandika',
  'stiffen': 'kukakamaa',
  'stifle': 'kukandamiza',
  'sting': 'kuuma',
  'stink': 'kunuka',
  'stitch': 'kushona',
  'stocking': 'kuweka akiba',
  'stockpile': 'kulimbikiza',
  'stoop': 'kuinama',
  'stop': 'kukoma',
  'store': 'kuhifadhi',
  'storm': 'kuvamia',
  'strain': 'kuchuja',
  'strangle': 'kunyonga',
  'stream': 'kutiririka',
  'strengthen': 'kuimarisha',
  'stress': 'kusisitiza',
  'stretch': 'kunyoosha',
  'strew': 'kutawanya',
  'strike': 'kupiga',
  'string': 'kutunga',
  'strive': 'kujitahidi',
  'stroke': 'kupapasa',
  'struggle': 'kupambana',
  'study': 'kusoma',
  'stuff': 'kujaza',
  'stumble': 'kujikwaa',
  'style': 'kupanga mtindo',
  'sub': 'kuchukua nafasi',
  'subject': 'kutiisha',
  'sublimate': 'kubadilisha mwelekeo',
  'submerge': 'kuzamisha',
  'submit': 'kuwasilisha',
  'subside': 'kupungua',
  'subsist': 'kujikimu',
  'subvert': 'kuhujumu',
  'succeed': 'kufaulu',
  'succumb': 'kusalimu amri',
  'suffer': 'kuteseka',
  'suffice': 'kutosha',
  'suggest': 'kupendekeza',
  'suit': 'kufaa',
  'sum': 'kujumlisha',
  'summarise': 'kutoa muhtasari',
  'summon': 'kuitisha',
  'supplement': 'kuongezea',
  'supply': 'kusambaza',
  'support': 'kuunga mkono',
  'suppose': 'kudhani',
  'suppress': 'kukandamiza',
  'surface': 'kuibuka',
  'surge': 'kupanda ghafla',
  'surmount': 'kushinda',
  'surpass': 'kuzidi',
  'surprise': 'kushangaza',
  'survey': 'kufanya utafiti',
  'survive': 'kunusurika',
  'swallow': 'kumeza',
  'sway': 'kuyumba',
  'swear': 'kuapa',
  'sweat': 'kutokwa jasho',
  'sweep': 'kufagia',
  'sweeten': 'kutia utamu',
  'swim': 'kuogelea',
  'swing': 'kubembea',
  'swipe': 'kutelezesha',
  'switch': 'kubadilisha',
  'tackle': 'kukabiliana',
  'tag': 'kuweka lebo',
  'tailor': 'kurekebisha',
  'take part': 'kushiriki',
  'take': 'kuchukua',
  'talk': 'kuongea',
  'tally': 'kuhesabu',
  'tamper': 'kuchezea',
  'tangle': 'kuchanganyika',
  'target': 'kulenga',
  'tarnish': 'kuchafua',
  'taste': 'kuonja',
  'tax': 'kutoza kodi',
  'teach': 'kufundisha',
  'tear': 'kurarua',
  'tease': 'kutania',
  'tee': '',
  'tell': 'kuambia',
  'temper': 'kupunguza makali',
  'tempt': 'kushawishi',
  'test': 'kupima',
  'text': 'kutuma ujumbe',
  'thank': 'kushukuru',
  'think': 'kufikiri',
  'thread': 'kutunga',
  'threaten': 'kutishia',
  'thrive': 'kustawi',
  'throw': 'kutupa',
  'thrust': 'kusukuma kwa nguvu',
  'thwart': 'kuvuruga mipango',
  'tick': 'kuweka alama',
  'tide': '',
  'tie': 'kufunga',
  'tile': 'kuweka vigae',
  'time': 'kupanga wakati',
  'tip': 'kutoa bakshishi',
  'tire': 'kuchoka',
  'toll': 'kulia',
  'tone': 'kupunguza makali',
  'top': 'kuzidi',
  'topple': 'kuangusha',
  'torture': 'kutesa',
  'toss': 'kurusha',
  'total': 'kujumlisha',
  'touch': 'kugusa',
  'toughen': 'kuimarisha',
  'tour': 'kuzuru',
  'track': 'kufuatilia',
  'trade': 'kufanya biashara',
  'traffick': 'kusafirisha haramu',
  'train': 'kufunza',
  'trample': 'kukanyaga',
  'transact': 'kufanya muamala',
  'transfer': 'kuhamisha',
  'transform': 'kugeuza',
  'transition': 'kubadilika',
  'transpire': 'kutokea',
  'transport': 'kusafirisha',
  'trap': 'kunasa',
  'travel': 'kusafiri',
  'treat': 'kutibu',
  'trek': 'kusafiri kwa miguu',
  'tremble': 'kutetemeka',
  'trend': 'kuvuma',
  'tribute': 'kutoa heshima',
  'trick': 'kulaghai',
  'trickle': 'kudondoka',
  'trigger': 'kuchochea',
  'trim': 'kupunguza',
  'trip': 'kujikwaa',
  'trot': 'kukimbia polepole',
  'trouble': 'kusumbua',
  'trust': 'kuamini',
  'tumble': 'kubingirika',
  'tune': 'kurekebisha sauti',
  'tunnel': 'kuchimba handaki',
  'turn': 'kugeuka',
  'twin': 'kuoanisha',
  'twist': 'kusokota',
  'type': 'kuchapa',
  'uncover': 'kufichua',
  'undercut': 'kushusha bei',
  'undergo': 'kupitia',
  'understand': 'kuelewa',
  'undervalue': 'kupunguza thamani',
  'underwhelm': 'kukosa kuvutia',
  'undo': 'kutengua',
  'unearth': 'kufukua',
  'unfounded': '',
  'unleash': 'kuachilia',
  'unlock': 'kufungua',
  'unplug': 'kuchomoa',
  'unravel': 'kufumua',
  'untie': 'kufungua',
  'unveil': 'kuzindua',
  'update': 'kusasisha',
  'upgrade': 'kupandisha daraja',
  'uphold': 'kudumisha',
  'uplift': 'kuinua',
  'upload': 'kupakia',
  'urge': 'kuhimiza',
  'vacuum': 'kufyonza vumbi',
  'validate': 'kuthibitisha',
  'value': 'kuthamini',
  'vanish': 'kutoweka',
  'vary': 'kutofautiana',
  'venture': 'kuthubutu',
  'vibe': '',
  'vie': 'kushindana',
  'view': 'kutazama',
  'visit': 'kutembelea',
  'voice': 'kutoa maoni',
  'void': 'kubatilisha',
  'vomit': 'kutapika',
  'vote': 'kupiga kura',
  'vow': 'kuapa',
  'wait': 'kusubiri',
  'waive': 'kusamehe',
  'wake': 'kuamka',
  'walk': 'kutembea',
  'wander': 'kuzurura',
  'want': 'kutaka',
  'war': 'kupigana vita',
  'warehouse': 'kuhifadhi ghalani',
  'warn': 'kuonya',
  'warrant': 'kuhalalisha',
  'wash': 'kuosha',
  'waste': 'kupoteza',
  'watch': 'kutazama',
  'wave': 'kupungia mkono',
  'wax': 'kutia nta',
  'wear': 'kuvaa',
  'weather': 'kustahimili',
  'weave': 'kufuma',
  'wed': 'kuoa',
  'weed': 'kupalilia',
  'weep': 'kulia',
  'welcome': 'kukaribisha',
  'wheel': 'kusukuma',
  'whip': 'kupiga viboko',
  'whisk': 'kukoroga',
  'whisper': 'kunong\'ona',
  'whistle': 'kupiga mluzi',
  'wick': 'kufyonza',
  'widen': 'kupanua',
  'wield': 'kutumia',
  'win': 'kushinda',
  'wind': 'kuzungusha',
  'wing': 'kufanya bila maandalizi',
  'wipe': 'kufuta',
  'wire': 'kuunganisha nyaya',
  'wish': 'kutamani',
  'withdraw': 'kujiondoa',
  'wither': 'kunyauka',
  'wonder': 'kujiuliza',
  'work': 'kufanya kazi',
  'workshop': '',
  'worry': 'kuhangaika',
  'worsen': 'kuzorota',
  'worship': 'kuabudu',
  'worth': 'kuwa na thamani',
  'wound': 'kujeruhi',
  'wrap': 'kufunga',
  'wreak': 'kuleta maafa',
  'wreck': 'kubomoa',
  'wrestle': 'kupigana mieleka',
  'wring': 'kukamua',
  'wrinkle': 'kukunjamana',
  'write': 'kuandika',
  'yawn': 'kupiga miayo',
  'yell': 'kupiga kelele',
  'yield': 'kutoa mazao',
  'zip': 'kufunga zipu',
  'zone': 'kupoteza umakini',
  'zoom': 'kukuza',
}
