export default {
  'zero': 'sifuri',
  'one': 'moja',
  'two': 'mbili',
  'three': 'tatu',
  'four': 'nne',
  'five': 'tano',
  'six': 'sita',
  'seven': 'saba',
  'eight': 'nane',
  'nine': 'tisa',
  'ten': 'kumi',
  'eleven': 'kumi na moja',
  'twelve': 'kumi na mbili',
  'thirteen': 'kumi na tatu',
  'fourteen': 'kumi na nne',
  'fifteen': 'kumi na tano',
  'sixteen': 'kumi na sita',
  'seventeen': 'kumi na saba',
  'eighteen': 'kumi na nane',
  'nineteen': 'kumi na tisa',
  'twenty': 'ishirini',
  'thirty': 'thelathini',
  'forty': 'arobaini',
  'fourty': 'arobaini',
  'fifty': 'hamsini',
  'sixty': 'sitini',
  'seventy': 'sabini',
  'eighty': 'themanini',
  'ninety': 'tisini',
  'thousands': 'maelfu',
  'millions': 'mamilioni',
  'billions': 'mabilioni',
  'trillions': 'matrilioni',
  'hundred': 'mia',
  'thousand': 'elfu',
  'million': 'milioni',
  'billion': 'bilioni',
  'trillion': 'trilioni',
  'quadrillion': 'kwadrilioni',
  'quintillion': 'kwintilioni',
  'sextillion': 'sekstilioni',
  'septillion': 'septilioni',
  'zeroth': 'ya sifuri',
  'first': 'ya kwanza',
  'second': 'ya pili',
  'third': 'ya tatu',
  'fourth': 'ya nne',
  'fifth': 'ya tano',
  'sixth': 'ya sita',
  'seventh': 'ya saba',
  'eighth': 'ya nane',
  'ninth': 'ya tisa',
  'tenth': 'ya kumi',
  'eleventh': 'ya kumi na moja',
  'twelfth': 'ya kumi na mbili',
  'thirteenth': 'ya kumi na tatu',
  'fourteenth': 'ya kumi na nne',
  'fifteenth': 'ya kumi na tano',
  'sixteenth': 'ya kumi na sita',
  'seventeenth': 'ya kumi na saba',
  'eighteenth': 'ya kumi na nane',
  'nineteenth': 'ya kumi na tisa',
  'twentieth': 'ya ishirini',
  'thirtieth': 'ya thelathini',
  'fortieth': 'ya arobaini',
  'fourtieth': 'ya arobaini',
  'fiftieth': 'ya hamsini',
  'sixtieth': 'ya sitini',
  'seventieth': 'ya sabini',
  'eightieth': 'ya themanini',
  'ninetieth': 'ya tisini',
}
