export default {
  'a lot': 'dużo',
  'abroad': 'za granicą',
  'ad nauseam': 'do znudzenia',
  'again': 'znowu',
  'all but': 'prawie',
  'all that': 'aż tak',
  'almost': 'prawie',
  'already': 'już',
  'also': 'także',
  'always': 'zawsze',
  'anymore': 'już nie',
  'anyway': 'w każdym razie',
  'alongside': 'obok',
  'apart': 'osobno',
  'aside': 'na bok',
  'as soon': 'jak tylko',
  'at best': 'w najlepszym razie',
  'at large': 'na wolności',
  'at least': 'przynajmniej',
  'at most': 'najwyżej',
  'at worst': 'w najgorszym razie',
  'away': 'z dala',
  'by far': 'zdecydowanie',
  'by now': 'do tej pory',
  'de jure': 'de iure',
  'de trop': 'za dużo',
  'definitely': 'zdecydowanie',
  'directly': 'bezpośrednio',
  'en masse': 'masowo',
  'enough': 'wystarczająco',
  'for example': 'na przykład',
  'for good': 'na dobre',
  'for sure': 'na pewno',
  'forever': 'na zawsze',
  'fully': 'w pełni',
  'further': 'dalej',
  'furthermore': 'ponadto',
  'hence': 'stąd',
  'indeed': 'rzeczywiście',
  'instead': 'zamiast tego',
  'just about': 'prawie',
  'just': 'tylko',
  'likewise': 'podobnie',
  'kinda': 'trochę',
  'maybe': 'może',
  'meanwhile': 'tymczasem',
  'awhile': 'przez chwilę',
  'more': 'więcej',
  'moreover': 'ponadto',
  'newly': 'nowo',
  'no longer': 'już nie',
  'not only': 'nie tylko',
  'not withstanding': 'niemniej',
  'of course': 'oczywiście',
  'often': 'często',
  'once again': 'jeszcze raz',
  'once more': 'jeszcze raz',
  'once': 'raz',
  'only': 'tylko',
  'par excellence': 'par excellence',
  'per se': 'samo w sobie',
  'perhaps': 'być może',
  'point blank': 'wprost',
  'quite': 'całkiem',
  'randomly': 'losowo',
  'rather': 'raczej',
  'really': 'naprawdę',
  'so': 'tak',
  'somehow': 'jakoś',
  'sometimes': 'czasami',
  'somewhat': 'nieco',
  'sort of': 'poniekąd',
  'seldom': 'rzadko',
  'such': 'taki',
  'then': 'potem',
  'thus': 'zatem',
  'too': 'też',
  'totally': 'całkowicie',
  'twice': 'dwa razy',
  'up to': 'do',
  'upwards of': 'ponad',
  'tiny bit': 'odrobinę',
  'very': 'bardzo',
  'well': 'dobrze',
  'backward': 'do tyłu',
  'hella': 'mega',
  'by no means': 'bynajmniej',
  'altogether': 'zupełnie',
  'outright': 'otwarcie',
  'ultimately': 'ostatecznie',
}
