export default {
  'abandon': 'porzucać',
  'abduct': 'porywać',
  'abet': 'podżegać',
  'abide': 'przestrzegać',
  'abolish': 'znosić',
  'abort': 'przerywać',
  'abound': 'obfitować',
  'abscond': 'uciekać',
  'absolve': 'rozgrzeszać',
  'abuse': 'nadużywać',
  'accent': 'akcentować',
  'accept': 'akceptować',
  'access': 'uzyskiwać dostęp',
  'acclimate': 'aklimatyzować się',
  'accommodate': 'mieścić',
  'accompany': 'towarzyszyć',
  'accomplish': 'dokonywać',
  'accord': 'przyznawać',
  'accost': 'zaczepiać',
  'account': 'rozliczać',
  'accrue': 'narastać',
  'accuse': 'oskarżać',
  'accustom': 'przyzwyczajać',
  'ace': 'zaliczać na piątkę',
  'ache': 'boleć',
  'achieve': 'osiągać',
  'acknowledge': 'uznawać',
  'acquiesce': 'przyzwalać',
  'acquire': 'nabywać',
  'act': 'działać',
  'activate': 'aktywować',
  'adapt': 'dostosowywać',
  'address': 'adresować',
  'adjourn': 'odraczać',
  'adjust': 'regulować',
  'administer': 'zarządzać',
  'admit': 'przyznawać',
  'adopt': 'adoptować',
  'adorn': 'zdobić',
  'adsorb': 'adsorbować',
  'advance': 'posuwać się naprzód',
  'advocate': 'orędować',
  'affix': 'przytwierdzać',
  'afford': 'pozwalać sobie',
  'age': 'starzeć się',
  'agree': 'zgadzać się',
  'aid': 'pomagać',
  'aim': 'celować',
  'air': 'wietrzyć',
  'alarm': 'alarmować',
  'align': 'wyrównywać',
  'allege': 'twierdzić',
  'allot': 'przydzielać',
  'allow': 'pozwalać',
  'allude': 'nawiązywać',
  'alter': 'zmieniać',
  'amalgamate': 'scalać',
  'amaze': 'zadziwiać',
  'amuse': 'bawić',
  'analyse': 'analizować',
  'anchor': 'kotwiczyć',
  'anger': 'złościć',
  'animate': 'ożywiać',
  'anneal': 'wyżarzać',
  'announce': 'ogłaszać',
  'annoy': 'irytować',
  'annul': 'unieważniać',
  'answer': 'odpowiadać',
  'anticipate': 'przewidywać',
  'appeal': 'apelować',
  'appear': 'pojawiać się',
  'appease': 'udobruchać',
  'apply': 'stosować',
  'appoint': 'mianować',
  'appraise': 'wyceniać',
  'approach': 'zbliżać się',
  'approve': 'zatwierdzać',
  'arch': 'wyginać',
  'archive': 'archiwizować',
  'argue': 'kłócić się',
  'arise': 'powstawać',
  'arm': 'zbroić',
  'armour': 'opancerzać',
  'arouse': 'pobudzać',
  'arrange': 'układać',
  'arrive': 'przybywać',
  'ask': 'pytać',
  'aspire': 'aspirować',
  'assail': 'napadać',
  'assemble': 'składać',
  'assert': 'twierdzić',
  'assess': 'oceniać',
  'assign': 'przydzielać',
  'assist': 'pomagać',
  'associate': 'kojarzyć',
  'assure': 'zapewniać',
  'astonish': 'zdumiewać',
  'attach': 'dołączać',
  'attack': 'atakować',
  'attain': 'osiągać',
  'attempt': 'próbować',
  'attest': 'poświadczać',
  'attract': 'przyciągać',
  'auction': 'licytować',
  'augment': 'powiększać',
  'automate': 'automatyzować',
  'avert': 'zapobiegać',
  'avoid': 'unikać',
  'await': 'oczekiwać',
  'awaken': 'budzić',
  'award': 'przyznawać',
  'babysit': 'niańczyć',
  'back': 'popierać',
  'backfire': 'przynosić odwrotny skutek',
  'baffle': 'zbijać z tropu',
  'bail': 'wpłacać kaucję',
  'balance': 'równoważyć',
  'ban': 'zakazywać',
  'band': 'zrzeszać się',
  'bang': 'walić',
  'bank': 'deponować',
  'bar': 'zagradzać',
  'bargain': 'targować się',
  'barge': 'wpychać się',
  'bark': 'szczekać',
  'base': 'opierać',
  'bash': 'tłuc',
  'bathe': 'kąpać się',
  'battle': 'walczyć',
  'be': 'być',
  'bear': 'znosić',
  'beat': 'bić',
  'become': 'stawać się',
  'beef': 'wzmacniać',
  'befriend': 'zaprzyjaźniać się',
  'beg': 'błagać',
  'begin': 'zaczynać',
  'beguile': 'mamić',
  'behave': 'zachowywać się',
  'behead': 'ścinać',
  'behold': 'ujrzeć',
  'believe': 'wierzyć',
  'belittle': 'umniejszać',
  'belt': 'walić',
  'bend': 'zginać',
  'benefit': 'korzystać',
  'bequeath': 'zapisywać w spadku',
  'bestow': 'obdarzać',
  'bet': 'zakładać się',
  'betray': 'zdradzać',
  'bewilder': 'oszałamiać',
  'bias': 'uprzedzać',
  'bid': 'licytować',
  'bide': 'wyczekiwać',
  'bike': 'jeździć na rowerze',
  'bill': 'fakturować',
  'bind': 'wiązać',
  'biopsy': 'robić biopsję',
  'bit': 'gryźć',
  'bitch': 'marudzić',
  'bite': 'gryźć',
  'blame': 'obwiniać',
  'bleed': 'krwawić',
  'blend': 'mieszać',
  'blink': 'mrugać',
  'blitz': 'bombardować',
  'block': 'blokować',
  'blow': 'dmuchać',
  'blur': 'rozmazywać',
  'board': 'wsiadać',
  'boast': 'chwalić się',
  'bog': 'grzęznąć',
  'boil': 'gotować',
  'bolster': 'wzmacniać',
  'bomb': 'bombardować',
  'bombard': 'bombardować',
  'bond': 'tworzyć więź',
  'bone': 'filetować',
  'book': 'rezerwować',
  'boost': 'zwiększać',
  'boot': 'uruchamiać',
  'border': 'graniczyć',
  'borrow': 'pożyczać',
  'bother': 'przeszkadzać',
  'bottle': 'butelkować',
  'box': 'boksować',
  'boycott': 'bojkotować',
  'brake': 'hamować',
  'branch': 'rozgałęziać się',
  'brand': 'znakować',
  'breach': 'naruszać',
  'break': 'łamać',
  'breastfeed': 'karmić piersią',
  'breathe': 'oddychać',
  'breed': 'hodować',
  'bribe': 'przekupywać',
  'bridge': 'łączyć',
  'bring': 'przynosić',
  'broadcast': 'nadawać',
  'broaden': 'poszerzać',
  'bruise': 'siniaczyć',
  'brush': 'szczotkować',
  'bubble': 'bulgotać',
  'buckle': 'zapinać',
  'budget': 'budżetować',
  'buffer': 'buforować',
  'build': 'budować',
  'bump': 'uderzać',
  'burden': 'obciążać',
  'burn': 'palić',
  'burst': 'pękać',
  'bury': 'zakopywać',
  'bust': 'rozbijać',
  'buy': 'kupować',
  'buzz': 'brzęczeć',
  'bypass': 'omijać',
  'cake': 'oblepiać',
  'call': 'dzwonić',
  'camp': 'biwakować',
  'cancel': 'odwoływać',
  'canoe': 'pływać kajakiem',
  'cap': 'ograniczać',
  'capture': 'chwytać',
  'card': 'legitymować',
  'care': 'troszczyć się',
  'careen': 'pędzić',
  'cash': 'spieniężać',
  'cast': 'rzucać',
  'catalog': 'katalogować',
  'catch': 'łapać',
  'cater': 'zaopatrywać',
  'caulk': 'uszczelniać',
  'cause': 'powodować',
  'caution': 'ostrzegać',
  'cave': 'zapadać się',
  'cease': 'zaprzestawać',
  'center': 'centrować',
  'centre': 'centrować',
  'chain': 'przykuwać',
  'chair': 'przewodniczyć',
  'challenge': 'rzucać wyzwanie',
  'change': 'zmieniać',
  'channel': 'kierować',
  'charge': 'ładować',
  'charm': 'oczarowywać',
  'chart': 'wykreślać',
  'chase': 'gonić',
  'cheat': 'oszukiwać',
  'check': 'sprawdzać',
  'cheer': 'wiwatować',
  'cherish': 'pielęgnować',
  'chew': 'żuć',
  'chip': 'odłupywać',
  'chirp': 'ćwierkać',
  'choose': 'wybierać',
  'chop': 'siekać',
  'circle': 'okrążać',
  'circumvent': 'obchodzić',
  'cite': 'cytować',
  'claim': 'twierdzić',
  'claw': 'drapać',
  'cleanse': 'oczyszczać',
  'click': 'klikać',
  'cling': 'przywierać',
  'clip': 'przycinać',
  'cloud': 'zaciemniać',
  'club': 'pałować',
  'coalesce': 'zlewać się',
  'coat': 'powlekać',
  'code': 'kodować',
  'coerce': 'zmuszać',
  'coexist': 'współistnieć',
  'cohabit': 'mieszkać razem',
  'coin': 'ukuć',
  'coincide': 'zbiegać się',
  'collapse': 'zawalać się',
  'collect': 'zbierać',
  'collide': 'zderzać się',
  'collude': 'zmawiać się',
  'color': 'kolorować',
  'colour': 'kolorować',
  'combat': 'zwalczać',
  'combine': 'łączyć',
  'combust': 'spalać się',
  'come': 'przychodzić',
  'comfort': 'pocieszać',
  'command': 'rozkazywać',
  'commence': 'rozpoczynać',
  'comment': 'komentować',
  'commit': 'popełniać',
  'commute': 'dojeżdżać',
  'compel': 'zmuszać',
  'compete': 'konkurować',
  'compile': 'kompilować',
  'complement': 'uzupełniać',
  'comply': 'stosować się',
  'compound': 'potęgować',
  'compromise': 'iść na kompromis',
  'conceal': 'ukrywać',
  'conceive': 'obmyślać',
  'concentrate': 'koncentrować się',
  'concern': 'dotyczyć',
  'conclude': 'wnioskować',
  'concur': 'zgadzać się',
  'condemn': 'potępiać',
  'condense': 'kondensować',
  'condone': 'tolerować',
  'conduct': 'prowadzić',
  'confess': 'wyznawać',
  'confide': 'zwierzać się',
  'configure': 'konfigurować',
  'confirm': 'potwierdzać',
  'conflict': 'kolidować',
  'conform': 'dostosowywać się',
  'confront': 'konfrontować',
  'confuse': 'mylić',
  'conglomerate': 'skupiać się',
  'conjure': 'wyczarowywać',
  'connote': 'konotować',
  'conquer': 'podbijać',
  'consent': 'wyrażać zgodę',
  'conserve': 'oszczędzać',
  'consider': 'rozważać',
  'consist': 'składać się',
  'consolidate': 'konsolidować',
  'conspire': 'spiskować',
  'constitute': 'stanowić',
  'constrain': 'ograniczać',
  'construct': 'konstruować',
  'consult': 'konsultować',
  'consume': 'konsumować',
  'contact': 'kontaktować się',
  'contain': 'zawierać',
  'continue': 'kontynuować',
  'contrast': 'kontrastować',
  'contribute': 'przyczyniać się',
  'control': 'kontrolować',
  'convene': 'zwoływać',
  'converge': 'zbiegać się',
  'convert': 'przekształcać',
  'convey': 'przekazywać',
  'convince': 'przekonywać',
  'coordinate': 'koordynować',
  'copy': 'kopiować',
  'core': 'wydrążać',
  'corrode': 'korodować',
  'cost': 'kosztować',
  'cough': 'kaszleć',
  'counsel': 'doradzać',
  'count': 'liczyć',
  'couple': 'sprzęgać',
  'court': 'zalecać się',
  'cover': 'przykrywać',
  'crack': 'pękać',
  'craft': 'wytwarzać',
  'crash': 'rozbijać się',
  'crave': 'pragnąć',
  'create': 'tworzyć',
  'credit': 'przypisywać',
  'creep': 'skradać się',
  'cripple': 'okaleczać',
  'crop': 'przycinać',
  'cross': 'przekraczać',
  'crowd': 'tłoczyć się',
  'crumble': 'kruszyć się',
  'crush': 'miażdżyć',
  'cry': 'płakać',
  'cube': 'kroić w kostkę',
  'cue': 'dawać znak',
  'curb': 'powściągać',
  'cure': 'leczyć',
  'curl': 'zwijać',
  'curtail': 'ograniczać',
  'curve': 'zakrzywiać',
  'cut': 'ciąć',
  'dab': 'muskać',
  'damage': 'uszkadzać',
  'dampen': 'tłumić',
  'dance': 'tańczyć',
  'dare': 'odważać się',
  'darken': 'przyciemniać',
  'dart': 'śmigać',
  'date': 'umawiać się',
  'daunt': 'zniechęcać',
  'deafen': 'ogłuszać',
  'deal': 'handlować',
  'debark': 'schodzić na ląd',
  'debate': 'debatować',
  'debrief': 'przesłuchiwać',
  'debug': 'debugować',
  'debunk': 'obalać',
  'debut': 'debiutować',
  'deceive': 'oszukiwać',
  'decide': 'decydować',
  'decimate': 'dziesiątkować',
  'decipher': 'odszyfrowywać',
  'declare': 'deklarować',
  'decline': 'odmawiać',
  'decode': 'dekodować',
  'decommission': 'wycofywać z użytku',
  'decompose': 'rozkładać się',
  'decouple': 'rozprzęgać',
  'decrease': 'zmniejszać',
  'decree': 'dekretować',
  'decry': 'potępiać',
  'decrypt': 'odszyfrowywać',
  'deduct': 'odliczać',
  'deepen': 'pogłębiać',
  'deface': 'oszpecać',
  'defeat': 'pokonywać',
  'defect': 'dezerterować',
  'define': 'definiować',
  'deform': 'deformować',
  'defraud': 'defraudować',
  'defy': 'przeciwstawiać się',
  'delay': 'opóźniać',
  'delegate': 'delegować',
  'delight': 'zachwycać',
  'delimit': 'wytyczać',
  'deliver': 'dostarczać',
  'demand': 'żądać',
  'demean': 'poniżać',
  'demolish': 'burzyć',
  'denote': 'oznaczać',
  'denounce': 'potępiać',
  'deny': 'zaprzeczać',
  'depart': 'odjeżdżać',
  'depict': 'przedstawiać',
  'deplore': 'ubolewać',
  'deploy': 'wdrażać',
  'deport': 'deportować',
  'deposit': 'wpłacać',
  'derail': 'wykolejać',
  'derive': 'wywodzić',
  'desert': 'porzucać',
  'design': 'projektować',
  'desire': 'pragnąć',
  'desist': 'zaniechać',
  'detach': 'odłączać',
  'detail': 'wyszczególniać',
  'develop': 'rozwijać',
  'devolve': 'przekazywać',
  'diagnose': 'diagnozować',
  'die': 'umierać',
  'differ': 'różnić się',
  'dig': 'kopać',
  'digest': 'trawić',
  'diminish': 'zmniejszać',
  'dine': 'jadać',
  'dip': 'zanurzać',
  'disable': 'wyłączać',
  'disarm': 'rozbrajać',
  'disband': 'rozwiązywać',
  'disburse': 'wypłacać',
  'discard': 'odrzucać',
  'discern': 'dostrzegać',
  'discharge': 'zwalniać',
  'disclaim': 'zrzekać się',
  'disclose': 'ujawniać',
  'discourage': 'zniechęcać',
  'discover': 'odkrywać',
  'discuss': 'omawiać',
  'disguise': 'przebierać',
  'dish': 'serwować',
  'dislike': 'nie lubić',
  'dislodge': 'usuwać',
  'dismantle': 'demontować',
  'dispatch': 'wysyłać',
  'dispense': 'wydawać',
  'disperse': 'rozpraszać',
  'displace': 'wypierać',
  'display': 'wyświetlać',
  'displease': 'drażnić',
  'dispose': 'pozbywać się',
  'disprove': 'obalać',
  'dispute': 'kwestionować',
  'disrupt': 'zakłócać',
  'dissolve': 'rozpuszczać',
  'dissuade': 'odwodzić',
  'distil': 'destylować',
  'distill': 'destylować',
  'distinguish': 'rozróżniać',
  'distort': 'zniekształcać',
  'disturb': 'niepokoić',
  'ditch': 'porzucać',
  'dive': 'nurkować',
  'diverge': 'rozchodzić się',
  'divert': 'przekierowywać',
  'divest': 'pozbywać się',
  'divide': 'dzielić',
  'divorce': 'rozwodzić się',
  'divulge': 'wyjawiać',
  'do': 'robić',
  'dock': 'dokować',
  'document': 'dokumentować',
  'dodge': 'uchylać się',
  'doubt': 'wątpić',
  'download': 'pobierać',
  'draft': 'sporządzać',
  'drag': 'ciągnąć',
  'drain': 'osuszać',
  'draw': 'rysować',
  'dream': 'śnić',
  'dredge': 'bagrować',
  'dress': 'ubierać',
  'drift': 'dryfować',
  'drill': 'wiercić',
  'drink': 'pić',
  'drip': 'kapać',
  'drive': 'prowadzić',
  'drone': 'buczeć',
  'drop': 'upuszczać',
  'drown': 'tonąć',
  'dub': 'dubbingować',
  'duel': 'pojedynkować się',
  'dump': 'wyrzucać',
  'duplicate': 'powielać',
  'dwindle': 'kurczyć się',
  'dye': 'farbować',
  'earmark': 'przeznaczać',
  'earn': 'zarabiać',
  'eat': 'jeść',
  'echo': 'odbijać się echem',
  'edge': 'przesuwać się',
  'edit': 'edytować',
  'effect': 'wywoływać',
  'elapse': 'upływać',
  'elect': 'wybierać',
  'elucidate': 'wyjaśniać',
  'elude': 'wymykać się',
  'embalm': 'balsamować',
  'embark': 'wsiadać',
  'embody': 'ucieleśniać',
  'embrace': 'obejmować',
  'embroider': 'haftować',
  'embroil': 'wikłać',
  'emerge': 'wyłaniać się',
  'emphasize': 'podkreślać',
  'empower': 'upoważniać',
  'enable': 'umożliwiać',
  'enact': 'uchwalać',
  'encircle': 'otaczać',
  'enclose': 'załączać',
  'encounter': 'napotykać',
  'encourage': 'zachęcać',
  'encroach': 'wkraczać',
  'encrypt': 'szyfrować',
  'encumber': 'obciążać',
  'end': 'kończyć',
  'endanger': 'zagrażać',
  'endorse': 'popierać',
  'endow': 'wyposażać',
  'endure': 'wytrzymywać',
  'enforce': 'egzekwować',
  'engage': 'angażować',
  'engender': 'rodzić',
  'engrave': 'grawerować',
  'engulf': 'pochłaniać',
  'enhance': 'ulepszać',
  'enjoy': 'cieszyć się',
  'enlarge': 'powiększać',
  'enlist': 'zaciągać się',
  'enquire': 'dowiadywać się',
  'enrich': 'wzbogacać',
  'enrol': 'zapisywać się',
  'enroll': 'zapisywać się',
  'ensue': 'następować',
  'ensure': 'zapewniać',
  'enter': 'wchodzić',
  'entice': 'wabić',
  'entrain': 'porywać',
  'entrench': 'okopywać',
  'entrust': 'powierzać',
  'envelop': 'spowijać',
  'envisage': 'przewidywać',
  'envision': 'wyobrażać sobie',
  'envy': 'zazdrościć',
  'equip': 'wyposażać',
  'erase': 'wymazywać',
  'erupt': 'wybuchać',
  'escape': 'uciekać',
  'eschew': 'wystrzegać się',
  'espouse': 'popierać',
  'establish': 'ustanawiać',
  'estimate': 'szacować',
  'etch': 'trawić',
  'evaluate': 'oceniać',
  'evoke': 'przywoływać',
  'evolve': 'ewoluować',
  'exalt': 'wywyższać',
  'examine': 'badać',
  'exceed': 'przekraczać',
  'excel': 'celować',
  'exchange': 'wymieniać',
  'exclaim': 'wykrzykiwać',
  'exclude': 'wykluczać',
  'excuse': 'usprawiedliwiać',
  'exercise': 'ćwiczyć',
  'exert': 'wywierać',
  'exhale': 'wydychać',
  'exhaust': 'wyczerpywać',
  'exhibit': 'wystawiać',
  'exhort': 'nawoływać',
  'exhume': 'ekshumować',
  'exist': 'istnieć',
  'exit': 'wychodzić',
  'expect': 'oczekiwać',
  'expedite': 'przyspieszać',
  'expel': 'wydalać',
  'experience': 'doświadczać',
  'experiment': 'eksperymentować',
  'expire': 'wygasać',
  'explain': 'wyjaśniać',
  'exploit': 'wykorzystywać',
  'explore': 'eksplorować',
  'export': 'eksportować',
  'expose': 'odsłaniać',
  'expunge': 'wykreślać',
  'extinguish': 'gasić',
  'extol': 'wychwalać',
  'extract': 'wydobywać',
  'exude': 'emanować',
  'eye': 'przyglądać się',
  'eyeball': 'mierzyć na oko',
  'face': 'stawiać czoła',
  'fail': 'zawodzić',
  'fall': 'spadać',
  'falter': 'chwiać się',
  'farm': 'uprawiać',
  'fasten': 'zapinać',
  'favour': 'faworyzować',
  'fear': 'bać się',
  'feature': 'prezentować',
  'feed': 'karmić',
  'feel': 'czuć',
  'fence': 'grodzić',
  'ferment': 'fermentować',
  'field': 'przyjmować',
  'fight': 'walczyć',
  'figure': 'obliczać',
  'file': 'składać',
  'film': 'filmować',
  'filter': 'filtrować',
  'finance': 'finansować',
  'find': 'znajdować',
  'finish': 'kończyć',
  'fire': 'zwalniać',
  'fish': 'łowić ryby',
  'fit': 'pasować',
  'fix': 'naprawiać',
  'flag': 'oznaczać',
  'flake': 'łuszczyć się',
  'flame': 'płonąć',
  'flare': 'rozbłyskać',
  'flash': 'błyskać',
  'flatter': 'schlebiać',
  'flavor': 'przyprawiać',
  'flavour': 'przyprawiać',
  'flee': 'uciekać',
  'flesh': 'konkretyzować',
  'fling': 'ciskać',
  'flip': 'przewracać',
  'float': 'unosić się',
  'flock': 'gromadzić się',
  'flood': 'zalewać',
  'flow': 'płynąć',
  'flower': 'kwitnąć',
  'fly': 'latać',
  'focus': 'skupiać się',
  'fog': 'zaparowywać',
  'foil': 'udaremniać',
  'fold': 'składać',
  'foot': 'pokrywać',
  'forbid': 'zabraniać',
  'force': 'zmuszać',
  'forecast': 'prognozować',
  'foreclose': 'przejmować',
  'forego': 'rezygnować',
  'foreshadow': 'zapowiadać',
  'forewarn': 'przestrzegać',
  'forfeit': 'tracić',
  'forge': 'podrabiać',
  'forget': 'zapominać',
  'forgive': 'wybaczać',
  'form': 'formować',
  'format': 'formatować',
  'forsake': 'porzucać',
  'forsee': 'przewidywać',
  'forward': 'przekazywać',
  'fracture': 'łamać',
  'fragment': 'rozdrabniać',
  'frame': 'oprawiać',
  'franchise': 'udzielać franczyzy',
  'freeze': 'zamarzać',
  'freshen': 'odświeżać',
  'frighten': 'straszyć',
  'frolic': 'baraszkować',
  'frost': 'lukrować',
  'frown': 'marszczyć brwi',
  'fry': 'smażyć',
  'fuck': 'pieprzyć',
  'fuel': 'podsycać',
  'fulfil': 'spełniać',
  'function': 'funkcjonować',
  'fund': 'finansować',
  'fundraise': 'zbierać fundusze',
  'furnish': 'meblować',
  'fuss': 'robić zamieszanie',
  'fuzz': 'rozmywać',
  'gag': 'kneblować',
  'gain': 'zyskiwać',
  'game': 'ogrywać',
  'gang': 'zmawiać się',
  'gas': 'gazować',
  'gate': 'ogradzać',
  'gather': 'zbierać',
  'gaze': 'wpatrywać się',
  'gear': 'przygotowywać',
  'get': 'dostawać',
  'gift': 'obdarowywać',
  'giggle': 'chichotać',
  'give': 'dawać',
  'glare': 'piorunować wzrokiem',
  'glean': 'wyławiać',
  'gloss': 'tuszować',
  'glow': 'jarzyć się',
  'glue': 'kleić',
  'go': 'iść',
  'gossip': 'plotkować',
  'govern': 'rządzić',
  'grab': 'chwytać',
  'grade': 'oceniać',
  'grapple': 'zmagać się',
  'grasp': 'pojmować',
  'graze': 'paść się',
  'greet': 'witać',
  'grill': 'grillować',
  'grind': 'mielić',
  'grip': 'ściskać',
  'ground': 'uziemiać',
  'grow': 'rosnąć',
  'growth': 'wzrost',
  'grumble': 'narzekać',
  'guarantee': 'gwarantować',
  'guard': 'strzec',
  'guess': 'zgadywać',
  'gulp': 'przełykać',
  'gun': 'dodawać gazu',
  'hack': 'hakować',
  'ham': 'szarżować',
  'hammer': 'wbijać',
  'hamper': 'utrudniać',
  'hand': 'podawać',
  'handle': 'obsługiwać',
  'hang': 'wieszać',
  'happen': 'zdarzać się',
  'harangue': 'prawić kazanie',
  'harass': 'nękać',
  'harbour': 'żywić',
  'harm': 'szkodzić',
  'harness': 'ujarzmiać',
  'harvest': 'zbierać plony',
  'hash': 'roztrząsać',
  'hasten': 'przyspieszać',
  'hatch': 'wykluwać się',
  'hate': 'nienawidzić',
  'haunt': 'nawiedzać',
  'have': 'mieć',
  'head': 'kierować',
  'hear': 'słyszeć',
  'heat': 'podgrzewać',
  'hedge': 'zabezpieczać się',
  'heighten': 'wzmagać',
  'help': 'pomagać',
  'hide': 'ukrywać',
  'highlight': 'podkreślać',
  'hijack': 'porywać',
  'hike': 'wędrować',
  'hinder': 'przeszkadzać',
  'hint': 'sugerować',
  'hire': 'zatrudniać',
  'hit': 'uderzać',
  'hoist': 'wciągać',
  'hold': 'trzymać',
  'hole': 'dziurawić',
  'honor': 'honorować',
  'honour': 'honorować',
  'hook': 'zahaczać',
  'hop': 'podskakiwać',
  'hope': 'mieć nadzieję',
  'horse': 'wygłupiać się',
  'house': 'mieścić',
  'hug': 'przytulać',
  'hunt': 'polować',
  'hurt': 'ranić',
  'ignore': 'ignorować',
  'imbue': 'przepajać',
  'immerse': 'zanurzać',
  'impact': 'wpływać',
  'impale': 'nadziewać',
  'impart': 'przekazywać',
  'imperil': 'narażać',
  'impinge': 'naruszać',
  'implement': 'wdrażać',
  'imply': 'sugerować',
  'import': 'importować',
  'impose': 'narzucać',
  'impoverish': 'zubażać',
  'impress': 'imponować',
  'imprison': 'więzić',
  'improve': 'poprawiać',
  'incite': 'podburzać',
  'incline': 'skłaniać',
  'include': 'uwzględniać',
  'increase': 'zwiększać',
  'index': 'indeksować',
  'indicate': 'wskazywać',
  'indulge': 'folgować',
  'infest': 'opanowywać',
  'influence': 'wpływać',
  'inform': 'informować',
  'infuse': 'zaparzać',
  'ingest': 'spożywać',
  'inhabit': 'zamieszkiwać',
  'inhale': 'wdychać',
  'inhibit': 'hamować',
  'initiate': 'inicjować',
  'injure': 'ranić',
  'ink': 'podpisywać',
  'inquire': 'dowiadywać się',
  'insert': 'wstawiać',
  'insist': 'nalegać',
  'inspire': 'inspirować',
  'install': 'instalować',
  'instil': 'wpajać',
  'instruct': 'instruować',
  'insure': 'ubezpieczać',
  'intent': 'zamierzać',
  'interact': 'współdziałać',
  'interest': 'interesować',
  'interface': 'łączyć się',
  'intern': 'odbywać staż',
  'interpret': 'interpretować',
  'interrupt': 'przerywać',
  'interview': 'przeprowadzać wywiad',
  'intimidate': 'zastraszać',
  'intoxicate': 'odurzać',
  'introduce': 'przedstawiać',
  'intrude': 'wtrącać się',
  'inundate': 'zalewać',
  'invade': 'najeżdżać',
  'invent': 'wynajdywać',
  'invert': 'odwracać',
  'invest': 'inwestować',
  'invoice': 'fakturować',
  'invoke': 'przywoływać',
  'involve': 'angażować',
  'irk': 'drażnić',
  'iron': 'prasować',
  'issue': 'wydawać',
  'jam': 'zakleszczać',
  'jazz': 'ożywiać',
  'join': 'dołączać',
  'joke': 'żartować',
  'juggle': 'żonglować',
  'juice': 'wyciskać sok',
  'jump': 'skakać',
  'juxtapose': 'zestawiać',
  'keel': 'przewracać się',
  'keep': 'zachowywać',
  'key': 'wpisywać',
  'kick': 'kopać',
  'kid': 'żartować',
  'kidnap': 'porywać',
  'kill': 'zabijać',
  'kiss': 'całować',
  'kneel': 'klękać',
  'knock': 'pukać',
  'know': 'wiedzieć',
  'label': 'etykietować',
  'labor': 'trudzić się',
  'labour': 'trudzić się',
  'lace': 'sznurować',
  'lack': 'brakować',
  'land': 'lądować',
  'languish': 'marnieć',
  'lap': 'chłeptać',
  'latch': 'zatrzaskiwać',
  'laugh': 'śmiać się',
  'launch': 'uruchamiać',
  'launder': 'prać',
  'leach': 'ługować',
  'lead': 'prowadzić',
  'leak': 'przeciekać',
  'leap': 'skakać',
  'learn': 'uczyć się',
  'lease': 'dzierżawić',
  'leave': 'opuszczać',
  'lecture': 'wykładać',
  'leech': 'pasożytować',
  'lend': 'pożyczać',
  'lengthen': 'wydłużać',
  'lessen': 'zmniejszać',
  'level': 'wyrównywać',
  'levy': 'nakładać',
  'license': 'licencjonować',
  'lick': 'lizać',
  'lie': 'kłamać',
  'lift': 'podnosić',
  'like': 'lubić',
  'limit': 'ograniczać',
  'line': 'wyściełać',
  'linger': 'ociągać się',
  'link': 'łączyć',
  'liquefy': 'skraplać',
  'liquidate': 'likwidować',
  'list': 'wymieniać',
  'liven': 'ożywiać',
  'load': 'ładować',
  'loan': 'pożyczać',
  'lobby': 'lobbować',
  'lock': 'zamykać',
  'log': 'rejestrować',
  'look': 'patrzeć',
  'loot': 'plądrować',
  'lose': 'tracić',
  'love': 'kochać',
  'lump': 'grupować',
  'lurk': 'czaić się',
  'lust': 'pożądać',
  'mail': 'wysyłać pocztą',
  'maim': 'okaleczać',
  'maintain': 'utrzymywać',
  'make': 'robić',
  'manage': 'zarządzać',
  'mandate': 'nakazywać',
  'manner': 'sposób',
  'manoeuvre': 'manewrować',
  'map': 'mapować',
  'market': 'promować',
  'mash': 'tłuc',
  'mask': 'maskować',
  'master': 'opanowywać',
  'match': 'dopasowywać',
  'matter': 'mieć znaczenie',
  'measure': 'mierzyć',
  'meet': 'spotykać',
  'mention': 'wspominać',
  'merge': 'scalać',
  'merit': 'zasługiwać',
  'mess': 'bałaganić',
  'milk': 'doić',
  'mimic': 'naśladować',
  'mimick': 'naśladować',
  'mince': 'siekać',
  'mind': 'pilnować',
  'mine': 'wydobywać',
  'mingle': 'mieszać się',
  'minus': 'odejmować',
  'mirror': 'odzwierciedlać',
  'misplace': 'zapodziewać',
  'miss': 'tęsknić',
  'mistake': 'mylić',
  'mix': 'mieszać',
  'mock': 'wyśmiewać',
  'model': 'modelować',
  'mold': 'formować',
  'molest': 'molestować',
  'monitor': 'monitorować',
  'monkey': 'majstrować',
  'mop': 'mopować',
  'mount': 'montować',
  'mourn': 'opłakiwać',
  'mouth': 'wymawiać bezgłośnie',
  'move': 'ruszać',
  'mow': 'kosić',
  'multiply': 'mnożyć',
  'murder': 'mordować',
  'name': 'nazywać',
  'need': 'potrzebować',
  'neglect': 'zaniedbywać',
  'net': 'zgarniać',
  'network': 'nawiązywać kontakty',
  'nod': 'kiwać głową',
  'note': 'notować',
  'notice': 'zauważać',
  'nourish': 'odżywiać',
  'nurse': 'pielęgnować',
  'obey': 'słuchać się',
  'object': 'sprzeciwiać się',
  'observe': 'obserwować',
  'obsess': 'mieć obsesję',
  'obtain': 'uzyskiwać',
  'occupy': 'zajmować',
  'occur': 'występować',
  'offer': 'oferować',
  'oil': 'oliwić',
  'omit': 'pomijać',
  'ooze': 'sączyć się',
  'operate': 'operować',
  'opine': 'wyrażać opinię',
  'oppose': 'sprzeciwiać się',
  'orbit': 'orbitować',
  'order': 'zamawiać',
  'orient': 'orientować',
  'outgrow': 'wyrastać',
  'outline': 'zarysowywać',
  'outnumber': 'przewyższać liczebnie',
  'outpace': 'wyprzedzać',
  'overlap': 'nakładać się',
  'overpass': 'przekraczać',
  'oversee': 'nadzorować',
  'overshadow': 'przyćmiewać',
  'overturn': 'uchylać',
  'overuse': 'nadużywać',
  'overwhelm': 'przytłaczać',
  'owe': 'być winnym',
  'pack': 'pakować',
  'package': 'pakować',
  'paint': 'malować',
  'pair': 'łączyć w pary',
  'paise': 'chwalić',
  'pamper': 'rozpieszczać',
  'pan': 'krytykować',
  'panic': 'panikować',
  'paralyse': 'paraliżować',
  'park': 'parkować',
  'part': 'rozstawać się',
  'participate': 'uczestniczyć',
  'party': 'imprezować',
  'pass': 'mijać',
  'paste': 'wklejać',
  'patch': 'łatać',
  'patent': 'patentować',
  'patrol': 'patrolować',
  'pause': 'pauzować',
  'pave': 'brukować',
  'pay': 'płacić',
  'peak': 'osiągać szczyt',
  'pee': 'sikać',
  'peel': 'obierać',
  'peer': 'przyglądać się',
  'pen': 'pisać',
  'pencil': 'zapisywać ołówkiem',
  'perceive': 'postrzegać',
  'perform': 'wykonywać',
  'perfume': 'perfumować',
  'perish': 'ginąć',
  'permeate': 'przenikać',
  'permit': 'zezwalać',
  'perplex': 'wprawiać w zakłopotanie',
  'persevere': 'wytrwać',
  'persist': 'trwać',
  'persuade': 'przekonywać',
  'pervade': 'przenikać',
  'pet': 'głaskać',
  'phase': 'wprowadzać etapami',
  'phone': 'telefonować',
  'photograph': 'fotografować',
  'pick': 'wybierać',
  'pile': 'układać w stos',
  'pin': 'przypinać',
  'pine': 'usychać z tęsknoty',
  'pinpoint': 'dokładnie określać',
  'pipe': 'doprowadzać rurami',
  'pit': 'przeciwstawiać',
  'pity': 'litować się',
  'pivot': 'obracać się',
  'place': 'umieszczać',
  'plan': 'planować',
  'plant': 'sadzić',
  'play': 'grać',
  'plce': 'umieszczać',
  'plead': 'błagać',
  'plug': 'zatykać',
  'plummet': 'gwałtownie spadać',
  'plump': 'ubijać',
  'plunge': 'zanurzać się',
  'poach': 'kłusować',
  'point': 'wskazywać',
  'poison': 'truć',
  'police': 'pilnować',
  'polish': 'polerować',
  'poll': 'ankietować',
  'pollute': 'zanieczyszczać',
  'pool': 'łączyć zasoby',
  'poop': 'robić kupę',
  'pop': 'strzelać',
  'pore': 'ślęczeć',
  'portray': 'portretować',
  'pose': 'pozować',
  'position': 'pozycjonować',
  'possess': 'posiadać',
  'post': 'publikować',
  'pound': 'walić',
  'power': 'zasilać',
  'practice': 'ćwiczyć',
  'praise': 'chwalić',
  'preach': 'głosić',
  'preclude': 'wykluczać',
  'predetermine': 'z góry określać',
  'predict': 'przewidywać',
  'prefer': 'woleć',
  'preoccupy': 'zaprzątać',
  'preserve': 'zachowywać',
  'press': 'naciskać',
  'presuppose': 'zakładać z góry',
  'prevail': 'przeważać',
  'prevent': 'zapobiegać',
  'prey': 'żerować',
  'price': 'wyceniać',
  'pride': 'szczycić się',
  'print': 'drukować',
  'probe': 'sondować',
  'proceed': 'przystępować',
  'process': 'przetwarzać',
  'proclaim': 'obwieszczać',
  'procure': 'pozyskiwać',
  'prod': 'szturchać',
  'produce': 'produkować',
  'profess': 'deklarować',
  'profile': 'profilować',
  'program': 'programować',
  'programme': 'programować',
  'progress': 'postępować',
  'prohibit': 'zabraniać',
  'project': 'rzutować',
  'promise': 'obiecywać',
  'promote': 'promować',
  'pronounce': 'wymawiać',
  'prop': 'podpierać',
  'propose': 'proponować',
  'prosper': 'prosperować',
  'protest': 'protestować',
  'protrude': 'wystawać',
  'prove': 'udowadniać',
  'provide': 'dostarczać',
  'provoke': 'prowokować',
  'prune': 'przycinać',
  'psych': 'nakręcać',
  'publish': 'publikować',
  'puke': 'rzygać',
  'pump': 'pompować',
  'punch': 'uderzać pięścią',
  'punish': 'karać',
  'purchase': 'nabywać',
  'purport': 'utrzymywać',
  'pursuant': 'zgodnie z',
  'pursue': 'ścigać',
  'push': 'pchać',
  'put': 'kłaść',
  'quash': 'tłumić',
  'quench': 'gasić',
  'question': 'kwestionować',
  'quit': 'rzucać',
  'quiver': 'drżeć',
  'quote': 'cytować',
  'race': 'ścigać się',
  'rack': 'dręczyć',
  'rage': 'szaleć',
  'rain': 'padać',
  'raise': 'podnosić',
  'rake': 'grabić',
  'rally': 'mobilizować',
  'range': 'wahać się',
  'rank': 'klasyfikować',
  'rant': 'pomstować',
  'rap': 'rapować',
  'rape': 'gwałcić',
  'rat': 'donosić',
  'rate': 'oceniać',
  'rattle': 'grzechotać',
  'ravish': 'zniewalać',
  'reach': 'sięgać',
  'react': 'reagować',
  'read': 'czytać',
  'realise': 'zdawać sobie sprawę',
  'realize': 'zdawać sobie sprawę',
  'reap': 'żąć',
  'reason': 'rozumować',
  'reboot': 'restartować',
  'rebuff': 'odtrącać',
  'recall': 'przypominać sobie',
  'receive': 'otrzymywać',
  'reckon': 'sądzić',
  'reclaim': 'odzyskiwać',
  'recognize': 'rozpoznawać',
  'reconcile': 'godzić',
  'record': 'nagrywać',
  'recoup': 'odzyskiwać',
  'recover': 'odzyskiwać',
  'recycle': 'poddawać recyklingowi',
  'redact': 'zaczerniać',
  'redo': 'robić od nowa',
  'reduce': 'redukować',
  'reel': 'zataczać się',
  'refactor': 'refaktoryzować',
  'reference': 'odwoływać się',
  'refinance': 'refinansować',
  'refine': 'udoskonalać',
  'reflect': 'odbijać',
  'refocus': 'ponownie skupiać',
  'reform': 'reformować',
  'refract': 'załamywać',
  'refresh': 'odświeżać',
  'refuel': 'tankować',
  'refund': 'zwracać pieniądze',
  'refurbish': 'odnawiać',
  'refuse': 'odmawiać',
  'regard': 'uważać',
  'register': 'rejestrować',
  'regret': 'żałować',
  'regroup': 'przegrupowywać się',
  'rehearse': 'robić próbę',
  'reheat': 'odgrzewać',
  'reimburse': 'zwracać koszty',
  'reinforce': 'wzmacniać',
  'reject': 'odrzucać',
  'rejoice': 'radować się',
  'relate': 'odnosić się',
  'release': 'uwalniać',
  'relent': 'ustępować',
  'relieve': 'odciążać',
  'relinquish': 'zrzekać się',
  'relish': 'rozkoszować się',
  'relive': 'przeżywać na nowo',
  'reload': 'przeładowywać',
  'rely': 'polegać',
  'remain': 'pozostawać',
  'remake': 'przerabiać',
  'remark': 'nadmieniać',
  'remedy': 'zaradzać',
  'remember': 'pamiętać',
  'remove': 'usuwać',
  'render': 'czynić',
  'rendezvous': 'spotykać się',
  'renew': 'odnawiać',
  'renounce': 'wyrzekać się',
  'rent': 'wynajmować',
  'reorder': 'zmieniać kolejność',
  'repair': 'naprawiać',
  'repeal': 'uchylać',
  'repeat': 'powtarzać',
  'repel': 'odpychać',
  'rephrase': 'przeformułowywać',
  'replace': 'zastępować',
  'replenish': 'uzupełniać',
  'replicate': 'replikować',
  'reply': 'odpowiadać',
  'report': 'zgłaszać',
  'represent': 'reprezentować',
  'request': 'prosić',
  'require': 'wymagać',
  'resemble': 'przypominać',
  'resent': 'żywić urazę',
  'reserve': 'rezerwować',
  'reside': 'rezydować',
  'resign': 'rezygnować',
  'resist': 'opierać się',
  'resolve': 'rozwiązywać',
  'resort': 'uciekać się',
  'respect': 'szanować',
  'respond': 'odpowiadać',
  'rest': 'odpoczywać',
  'restart': 'restartować',
  'restock': 'uzupełniać zapasy',
  'restrain': 'powstrzymywać',
  'restrict': 'ograniczać',
  'restructure': 'restrukturyzować',
  'result': 'skutkować',
  'resume': 'wznawiać',
  'resurface': 'wypływać na powierzchnię',
  'retire': 'przechodzić na emeryturę',
  'retrieve': 'odzyskiwać',
  'retrofit': 'doposażać',
  'return': 'wracać',
  'reup': 'przedłużać',
  'revamp': 'modernizować',
  'reveal': 'ujawniać',
  'revel': 'hulać',
  'revere': 'czcić',
  'reverse': 'odwracać',
  'revert': 'powracać',
  'review': 'recenzować',
  'revisit': 'ponownie rozpatrywać',
  'revive': 'ożywiać',
  'revoke': 'cofać',
  'revolve': 'obracać się',
  'reward': 'nagradzać',
  'rhyme': 'rymować',
  'rid': 'pozbywać się',
  'ride': 'jeździć',
  'ring': 'dzwonić',
  'riot': 'buntować się',
  'rip': 'rozdzierać',
  'ripen': 'dojrzewać',
  'rise': 'wznosić się',
  'risk': 'ryzykować',
  'roam': 'włóczyć się',
  'roast': 'piec',
  'rock': 'kołysać',
  'roll': 'toczyć',
  'roof': 'pokrywać dachem',
  'root': 'kibicować',
  'rope': 'wciągać',
  'rot': 'gnić',
  'rout': 'rozgramiać',
  'route': 'kierować',
  'rub': 'trzeć',
  'ruin': 'rujnować',
  'rule': 'rządzić',
  'run': 'biegać',
  'rush': 'spieszyć się',
  'rust': 'rdzewieć',
  'sack': 'zwalniać',
  'sacrifice': 'poświęcać',
  'sadden': 'zasmucać',
  'safeguard': 'chronić',
  'sail': 'żeglować',
  'sample': 'próbkować',
  'satisfy': 'zaspokajać',
  'say': 'mówić',
  'scale': 'skalować',
  'scan': 'skanować',
  'scar': 'pozostawiać blizny',
  'scare': 'straszyć',
  'scavenge': 'żerować',
  'schedule': 'planować',
  'score': 'zdobywać punkty',
  'scrape': 'skrobać',
  'scratch': 'drapać',
  'screen': 'przesiewać',
  'screw': 'przykręcać',
  'scribble': 'bazgrać',
  'scroll': 'przewijać',
  'sculpt': 'rzeźbić',
  'seal': 'pieczętować',
  'search': 'szukać',
  'seat': 'sadzać',
  'see': 'widzieć',
  'seed': 'siać',
  'seek': 'szukać',
  'seem': 'wydawać się',
  'sell': 'sprzedawać',
  'send': 'wysyłać',
  'sense': 'wyczuwać',
  'sentence': 'skazywać',
  'sequester': 'izolować',
  'serve': 'służyć',
  'service': 'serwisować',
  'set': 'ustawiać',
  'sever': 'zrywać',
  'sew': 'szyć',
  'shack': 'mieszkać razem',
  'shade': 'cieniować',
  'shake': 'trząść',
  'shape': 'kształtować',
  'share': 'dzielić się',
  'sharpen': 'ostrzyć',
  'shatter': 'roztrzaskiwać',
  'shave': 'golić',
  'shed': 'zrzucać',
  'sheild': 'osłaniać',
  'shelter': 'dawać schronienie',
  'shift': 'przesuwać',
  'shine': 'świecić',
  'ship': 'wysyłać',
  'shiver': 'drżeć',
  'shock': 'szokować',
  'shoot': 'strzelać',
  'shop': 'robić zakupy',
  'shore': 'podpierać',
  'shorten': 'skracać',
  'show': 'pokazywać',
  'shrink': 'kurczyć się',
  'shrivel': 'więdnąć',
  'shuffle': 'tasować',
  'shun': 'unikać',
  'side': 'stawać po stronie',
  'sift': 'przesiewać',
  'sign': 'podpisywać',
  'signal': 'sygnalizować',
  'silence': 'uciszać',
  'sing': 'śpiewać',
  'sink': 'tonąć',
  'sip': 'sączyć',
  'sit': 'siedzieć',
  'size': 'mierzyć',
  'skateboard': 'jeździć na deskorolce',
  'ski': 'jeździć na nartach',
  'skip': 'pomijać',
  'slam': 'trzaskać',
  'slay': 'zabijać',
  'sleep': 'spać',
  'slice': 'kroić',
  'slide': 'ślizgać się',
  'slip': 'poślizgnąć się',
  'slit': 'rozcinać',
  'slouch': 'garbić się',
  'smash': 'roztrzaskiwać',
  'smell': 'pachnieć',
  'smile': 'uśmiechać się',
  'smirk': 'uśmiechać się drwiąco',
  'smoke': 'palić',
  'smuggle': 'przemycać',
  'snake': 'wić się',
  'snap': 'pstrykać',
  'snatch': 'wyrywać',
  'sneak': 'skradać się',
  'sneeze': 'kichać',
  'sniff': 'wąchać',
  'snow': 'prószyć',
  'sob': 'szlochać',
  'solicit': 'nagabywać',
  'solve': 'rozwiązywać',
  'soothe': 'koić',
  'sound': 'brzmieć',
  'sow': 'siać',
  'spam': 'spamować',
  'span': 'obejmować',
  'spark': 'wzniecać',
  'spawn': 'rodzić',
  'speak': 'mówić',
  'speed': 'pędzić',
  'spell': 'literować',
  'spend': 'wydawać',
  'spill': 'rozlewać',
  'spin': 'kręcić',
  'spiral': 'wirować',
  'spit': 'pluć',
  'spite': 'robić na złość',
  'splash': 'chlapać',
  'splay': 'rozpościerać',
  'split': 'rozdzielać',
  'spoil': 'psuć',
  'sponsor': 'sponsorować',
  'spoof': 'parodiować',
  'spot': 'dostrzegać',
  'spray': 'rozpylać',
  'spread': 'rozprzestrzeniać',
  'spring': 'wyskakiwać',
  'sprinkle': 'posypywać',
  'spruce': 'stroić',
  'spur': 'pobudzać',
  'spy': 'szpiegować',
  'squander': 'trwonić',
  'square': 'wyrównywać',
  'squish': 'zgniatać',
  'stab': 'dźgać',
  'stack': 'układać w stos',
  'staff': 'obsadzać',
  'stage': 'wystawiać',
  'stagger': 'zataczać się',
  'stain': 'plamić',
  'stake': 'stawiać',
  'stalk': 'prześladować',
  'stall': 'grać na zwłokę',
  'stamp': 'stemplować',
  'stand': 'stać',
  'staple': 'zszywać',
  'star': 'grać główną rolę',
  'stare': 'gapić się',
  'start': 'zaczynać',
  'startle': 'płoszyć',
  'starve': 'głodować',
  'state': 'stwierdzać',
  'stay': 'zostawać',
  'steal': 'kraść',
  'steer': 'sterować',
  'stem': 'wynikać',
  'step': 'stąpać',
  'stick': 'przyklejać',
  'stiffen': 'usztywniać',
  'stifle': 'tłumić',
  'sting': 'żądlić',
  'stink': 'śmierdzieć',
  'stitch': 'zszywać',
  'stocking': 'zaopatrywać',
  'stockpile': 'gromadzić zapasy',
  'stoop': 'schylać się',
  'stop': 'zatrzymywać',
  'store': 'przechowywać',
  'storm': 'szturmować',
  'strain': 'wytężać',
  'strangle': 'dusić',
  'stream': 'transmitować',
  'strengthen': 'wzmacniać',
  'stress': 'podkreślać',
  'stretch': 'rozciągać',
  'strew': 'rozrzucać',
  'strike': 'uderzać',
  'string': 'nawlekać',
  'strive': 'dążyć',
  'stroke': 'głaskać',
  'struggle': 'zmagać się',
  'study': 'studiować',
  'stuff': 'wypychać',
  'stumble': 'potykać się',
  'style': 'stylizować',
  'sub': 'zastępować',
  'subject': 'poddawać',
  'sublimate': 'sublimować',
  'submerge': 'zatapiać',
  'submit': 'przedkładać',
  'subside': 'opadać',
  'subsist': 'utrzymywać się',
  'subvert': 'podkopywać',
  'succeed': 'odnosić sukces',
  'succumb': 'ulegać',
  'suffer': 'cierpieć',
  'suffice': 'wystarczać',
  'suggest': 'sugerować',
  'suit': 'pasować',
  'sum': 'sumować',
  'summarise': 'podsumowywać',
  'summon': 'wzywać',
  'supplement': 'uzupełniać',
  'supply': 'dostarczać',
  'support': 'wspierać',
  'suppose': 'przypuszczać',
  'suppress': 'tłumić',
  'surface': 'wynurzać się',
  'surge': 'gwałtownie rosnąć',
  'surmount': 'pokonywać',
  'surpass': 'przewyższać',
  'surprise': 'zaskakiwać',
  'survey': 'ankietować',
  'survive': 'przeżywać',
  'swallow': 'połykać',
  'sway': 'kołysać się',
  'swear': 'przeklinać',
  'sweat': 'pocić się',
  'sweep': 'zamiatać',
  'sweeten': 'słodzić',
  'swim': 'pływać',
  'swing': 'huśtać się',
  'swipe': 'przesuwać palcem',
  'switch': 'przełączać',
  'tackle': 'brać się za',
  'tag': 'oznaczać',
  'tailor': 'dopasowywać',
  'take part': 'brać udział',
  'take': 'brać',
  'talk': 'rozmawiać',
  'tally': 'podliczać',
  'tamper': 'majstrować',
  'tangle': 'plątać',
  'target': 'celować',
  'tarnish': 'plamić',
  'taste': 'smakować',
  'tax': 'opodatkowywać',
  'teach': 'uczyć',
  'tear': 'drzeć',
  'tease': 'dokuczać',
  'tee': 'ustawiać',
  'tell': 'opowiadać',
  'temper': 'hartować',
  'tempt': 'kusić',
  'test': 'testować',
  'text': 'esemesować',
  'thank': 'dziękować',
  'think': 'myśleć',
  'thread': 'nawlekać',
  'threaten': 'grozić',
  'thrive': 'prosperować',
  'throw': 'rzucać',
  'thrust': 'pchać',
  'thwart': 'udaremniać',
  'tick': 'tykać',
  'tide': 'pomagać przetrwać',
  'tie': 'wiązać',
  'tile': 'kafelkować',
  'time': 'mierzyć czas',
  'tip': 'przechylać',
  'tire': 'męczyć',
  'toll': 'bić',
  'tone': 'tonować',
  'top': 'przewyższać',
  'topple': 'obalać',
  'torture': 'torturować',
  'toss': 'podrzucać',
  'total': 'sumować',
  'touch': 'dotykać',
  'toughen': 'hartować',
  'tour': 'zwiedzać',
  'track': 'śledzić',
  'trade': 'handlować',
  'traffick': 'handlować nielegalnie',
  'train': 'trenować',
  'trample': 'deptać',
  'transact': 'dokonywać transakcji',
  'transfer': 'przenosić',
  'transform': 'przekształcać',
  'transition': 'przechodzić',
  'transpire': 'okazywać się',
  'transport': 'transportować',
  'trap': 'łapać w pułapkę',
  'travel': 'podróżować',
  'treat': 'traktować',
  'trek': 'wędrować',
  'tremble': 'drżeć',
  'trend': 'mieć tendencję',
  'tribute': 'oddawać hołd',
  'trick': 'oszukiwać',
  'trickle': 'sączyć się',
  'trigger': 'wyzwalać',
  'trim': 'przycinać',
  'trip': 'potykać się',
  'trot': 'kłusować',
  'trouble': 'trapić',
  'trust': 'ufać',
  'tumble': 'koziołkować',
  'tune': 'stroić',
  'tunnel': 'drążyć tunel',
  'turn': 'obracać',
  'twin': 'łączyć w pary',
  'twist': 'skręcać',
  'type': 'pisać na klawiaturze',
  'uncover': 'odkrywać',
  'undercut': 'podcinać',
  'undergo': 'przechodzić',
  'understand': 'rozumieć',
  'undervalue': 'niedoceniać',
  'underwhelm': 'rozczarowywać',
  'undo': 'cofać',
  'unearth': 'odgrzebywać',
  'unfounded': 'bezpodstawny',
  'unleash': 'rozpętywać',
  'unlock': 'odblokowywać',
  'unplug': 'odłączać',
  'unravel': 'rozplątywać',
  'untie': 'rozwiązywać',
  'unveil': 'odsłaniać',
  'update': 'aktualizować',
  'upgrade': 'ulepszać',
  'uphold': 'podtrzymywać',
  'uplift': 'podnosić na duchu',
  'upload': 'przesyłać',
  'urge': 'nakłaniać',
  'vacuum': 'odkurzać',
  'validate': 'walidować',
  'value': 'cenić',
  'vanish': 'znikać',
  'vary': 'różnić się',
  'venture': 'ryzykować',
  'vibe': 'czuć klimat',
  'vie': 'rywalizować',
  'view': 'oglądać',
  'visit': 'odwiedzać',
  'voice': 'wyrażać',
  'void': 'unieważniać',
  'vomit': 'wymiotować',
  'vote': 'głosować',
  'vow': 'ślubować',
  'wait': 'czekać',
  'waive': 'zrzekać się',
  'wake': 'budzić się',
  'walk': 'chodzić',
  'wander': 'wałęsać się',
  'want': 'chcieć',
  'war': 'wojować',
  'warehouse': 'magazynować',
  'warn': 'ostrzegać',
  'warrant': 'uzasadniać',
  'wash': 'myć',
  'waste': 'marnować',
  'watch': 'oglądać',
  'wave': 'machać',
  'wax': 'woskować',
  'wear': 'nosić',
  'weather': 'przetrwać',
  'weave': 'tkać',
  'wed': 'poślubiać',
  'weed': 'pielić',
  'weep': 'płakać',
  'welcome': 'witać',
  'wheel': 'toczyć',
  'whip': 'biczować',
  'whisk': 'ubijać',
  'whisper': 'szeptać',
  'whistle': 'gwizdać',
  'wick': 'odprowadzać wilgoć',
  'widen': 'poszerzać',
  'wield': 'dzierżyć',
  'win': 'wygrywać',
  'wind': 'nawijać',
  'wing': 'improwizować',
  'wipe': 'wycierać',
  'wire': 'przelewać',
  'wish': 'życzyć',
  'withdraw': 'wycofywać',
  'wither': 'usychać',
  'wonder': 'zastanawiać się',
  'work': 'pracować',
  'workshop': 'dopracowywać',
  'worry': 'martwić się',
  'worsen': 'pogarszać',
  'worship': 'czcić',
  'worth': 'być wartym',
  'wound': 'ranić',
  'wrap': 'owijać',
  'wreak': 'wyrządzać',
  'wreck': 'niszczyć',
  'wrestle': 'mocować się',
  'wring': 'wykręcać',
  'wrinkle': 'marszczyć',
  'write': 'pisać',
  'yawn': 'ziewać',
  'yell': 'krzyczeć',
  'yield': 'ustępować',
  'zip': 'zapinać na zamek',
  'zone': 'dzielić na strefy',
  'zoom': 'przybliżać',
}
