export default {
  'a lot': 'много',
  'abroad': 'за границей',
  'ad nauseam': 'до тошноты',
  'again': 'снова',
  'all but': 'почти',
  'all that': 'настолько',
  'almost': 'почти',
  'already': 'уже',
  'also': 'также',
  'always': 'всегда',
  'anymore': 'больше не',
  'anyway': 'всё равно',
  'alongside': 'рядом',
  'apart': 'врозь',
  'aside': 'в сторону',
  'as soon': 'как только',
  'at best': 'в лучшем случае',
  'at large': 'на свободе',
  'at least': 'по крайней мере',
  'at most': 'самое большее',
  'at worst': 'в худшем случае',
  'away': 'прочь',
  'by far': 'намного',
  'by now': 'к этому времени',
  'de jure': 'де-юре',
  'de trop': 'лишний',
  'definitely': 'определённо',
  'directly': 'прямо',
  'en masse': 'массово',
  'enough': 'достаточно',
  'for example': 'например',
  'for good': 'навсегда',
  'for sure': 'наверняка',
  'forever': 'навсегда',
  'fully': 'полностью',
  'further': 'дальше',
  'furthermore': 'более того',
  'hence': 'следовательно',
  'indeed': 'действительно',
  'instead': 'вместо',
  'just about': 'почти',
  'just': 'просто',
  'likewise': 'так же',
  'kinda': 'вроде',
  'maybe': 'может быть',
  'meanwhile': 'тем временем',
  'awhile': 'некоторое время',
  'more': 'больше',
  'moreover': 'к тому же',
  'newly': 'недавно',
  'no longer': 'больше не',
  'not only': 'не только',
  'not withstanding': 'тем не менее',
  'of course': 'конечно',
  'often': 'часто',
  'once again': 'ещё раз',
  'once more': 'ещё раз',
  'once': 'однажды',
  'only': 'только',
  'par excellence': 'по преимуществу',
  'per se': 'сам по себе',
  'perhaps': 'возможно',
  'point blank': 'в упор',
  'quite': 'довольно',
  'randomly': 'случайно',
  'rather': 'скорее',
  'really': 'действительно',
  'so': 'так',
  'somehow': 'как-то',
  'sometimes': 'иногда',
  'somewhat': 'немного',
  'sort of': 'вроде',
  'seldom': 'редко',
  'such': 'такой',
  'then': 'тогда',
  'thus': 'таким образом',
  'too': 'тоже',
  'totally': 'совершенно',
  'twice': 'дважды',
  'up to': 'до',
  'upwards of': 'свыше',
  'tiny bit': 'чуть-чуть',
  'very': 'очень',
  'well': 'хорошо',
  'backward': 'назад',
  'hella': 'чертовски',
  'by no means': 'отнюдь не',
  'altogether': 'совсем',
  'outright': 'откровенно',
  'ultimately': 'в конечном счёте',
}
