export default {
  'a': '',
  'an': '',
  'another': 'другой',
  'any': 'любой',
  'both': 'оба',
  'each': 'каждый',
  'else': 'ещё',
  'every': 'каждый',
  'few': 'мало',
  'least': 'меньше всего',
  'much': 'много',
  'neither': 'ни тот ни другой',
  'own': 'собственный',
  'plenty': 'множество',
  'some': 'несколько',
  'several': 'несколько',
  'that': 'то',
  'the': '',
  'these': 'эти',
  'this': 'это',
  'those': 'те',
  'various': 'различные',
  'whatever': 'что угодно',
  'whichever': 'какой угодно',
  'it': 'оно',
  'they': 'они',
  'i': 'я',
  'them': 'их',
  'you': 'ты',
  'she': 'она',
  'me': 'меня',
  'he': 'он',
  'him': 'его',
  'us': 'нас',
  'we': 'мы',
  'her': 'её',
  'hers': 'её',
  'his': 'его',
  'its': 'его',
  'mine': 'мой',
  'my': 'мой',
  'none': 'ни один',
  'our': 'наш',
  'ours': 'наш',
  'thy': 'твой',
  'their': 'их',
  'theirs': 'их',
  'your': 'твой',
  'yours': 'твой',
  'whatsoever': '',
  'whichsoever': '',
  'whoever': 'кто угодно',
  'whom': 'кого',
  'whomever': 'кого угодно',
  'whomsoever': 'кого угодно',
  'whose': 'чей',
  'whosesoever': '',
  'whosoever': 'кто угодно',
  'whenever': 'когда угодно',
  'although': 'хотя',
  'and': 'и',
  'because': 'потому что',
  'before': 'до',
  'but': 'но',
  'if': 'если',
  'how': 'как',
  'nor': 'ни',
  'now': 'сейчас',
  'or': 'или',
  'since': 'с тех пор как',
  'though': 'хотя',
  'while': 'пока',
  'yet': 'ещё',
  'amen': 'аминь',
  'argh': 'аргх',
  'boo': 'бу',
  'brr': 'бр-р',
  'bye': 'пока',
  'congratulations': 'поздравляю',
  'dammit': 'чёрт',
  'damn': 'чёрт',
  'damnit': 'чёрт',
  'dang': 'блин',
  'drat': 'тьфу',
  'duh': '',
  'eww': 'фу',
  'fuck': 'блядь',
  'goodbye': 'до свидания',
  'gosh': 'боже',
  'haha': 'хаха',
  'hello': 'здравствуйте',
  'hey': 'эй',
  'hi': 'привет',
  'holy': 'святой',
  'hooray': 'ура',
  'huh': 'а',
  'lol': 'лол',
  'meh': 'так себе',
  'mmm': 'ммм',
  'nah': 'не-а',
  'nope': 'нет',
  'oh': 'ох',
  'oops': 'ой',
  'ouch': 'ай',
  'ow': 'ай',
  'phew': 'уф',
  'phooey': 'фу',
  'please': 'пожалуйста',
  'shit': 'чёрт',
  'tsk': 'ц-ц',
  'ugh': 'фу',
  'uh huh': 'ага',
  'uh oh': 'ой-ой',
  'whew': 'уф',
  'whoa': 'ого',
  'wtf': 'что за чёрт',
  'ya': 'ага',
  'yay': 'ура',
  'yeah': 'ага',
  'yep': 'ага',
  'yes': 'да',
  'yikes': 'ой',
  'yipee': 'ура',
  'heck': 'блин',
  'yippee': 'ура',
  'yuck': 'фу',
  'yup': 'ага',
  'about': 'о',
  'across': 'через',
  'after': 'после',
  'along': 'вдоль',
  'amid': 'среди',
  'amidst': 'среди',
  'among': 'среди',
  'amongst': 'среди',
  'apropos': 'кстати',
  'around': 'вокруг',
  'as': 'как',
  'at': 'в',
  'atop': 'поверх',
  'barring': 'кроме',
  'besides': 'кроме',
  'between': 'между',
  'bout': 'о',
  'by': 'у',
  'despite': 'несмотря на',
  'down': 'вниз',
  'during': 'во время',
  'except': 'кроме',
  'for': 'для',
  'from': 'из',
  'in': 'в',
  'into': 'в',
  'notwithstanding': 'несмотря на',
  'of': '',
  'off': 'прочь',
  'on': 'на',
  'onto': 'на',
  'out': 'наружу',
  'than': 'чем',
  'thereby': 'тем самым',
  'through': 'через',
  'throughout': 'повсюду',
  'thru': 'через',
  'till': 'до',
  'towards': 'к',
  'unlike': 'в отличие от',
  'until': 'до',
  'up': 'вверх',
  'upon': 'на',
  'versus': 'против',
  'via': 'через',
  'whereas': 'тогда как',
  'with': 'с',
  'within': 'внутри',
  'without': 'без',
}
